### PR TITLE
Remove incubating from doc

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Remove incubating from doc

### What type of PR is it?
Documentation

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by cloverhearts** [comment]
Congratulations, apache zeppelin!
LGTM +1

**Comment by lresende** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
@minahlee Could you check 
 - [https://github.com/apache/incubator-zeppelin/blob/803ebc253928d68f6a72531b744c1c6741c2c535/docs/development/howtocontributewebsite.md#L11](https://github.com/apache/incubator-zeppelin/blob/803ebc253928d68f6a72531b744c1c6741c2c535/docs/development/howtocontributewebsite.md#L11)
 - [https://github.com/apache/incubator-zeppelin/blob/a313e492c43d3346b1e69cf5719e1e29a129ee67/docs/interpreter/r.md#L11](https://github.com/apache/incubator-zeppelin/blob/a313e492c43d3346b1e69cf5719e1e29a129ee67/docs/interpreter/r.md#L11)
 - [https://github.com/apache/incubator-zeppelin/blob/be0871490231109e3a3553862a61cfdf537f0ed1/docs/interpreter/spark.md#L207](https://github.com/apache/incubator-zeppelin/blob/be0871490231109e3a3553862a61cfdf537f0ed1/docs/interpreter/spark.md#L207)

**Comment by minahlee** [comment]
@AhyoungRyu Thanks for review I just handled them in bcb6b54

**Comment by AhyoungRyu** [comment]
@minahlee Cool! LGTM 👍

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by astroshim** [comment]
LGTM

**Comment by jongyoul** [comment]
LGTM

**Comment by minahlee** [comment]
@prabhjyotsingh thanks for pointing it out. I removed doap.rdf file from doc since it already exists in https://github.com/apache/incubator-zeppelin/blob/gh-pages/doap.rdf

**Comment by felixcheung** [comment]
LGTM

**Comment by minahlee** [comment]
I updated road.pdf file in master branch and removed it from gh-page branch in #948 for better search and maintenance.

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
