### PR TITLE
ZEPPELIN-216: Update ACE version, Change theme from Github to Chrome, add 'SH' mode.

### PR DESCRIPTION
**Pull request by tzolov**
Note that this PR has merged ZEPPELIN-141!

### CODE REVIEW

**Comment by tzolov** [comment]
In the first version i have:
* upgraded ACE from 1.1.8 to 1.1.9
* changed the theme from `github` to `chrome`
* added `sh` editor mode

Below are some sample screenshots of the same notes before and after the change:

#### Spark + SparkSQL Before:
spark-before
#### Spark + SparkSQL After:
spark-after
#### PostgreSQL Before:
psql-before
#### PostgreSQL After:
psql-after
#### SH Before:
sh-before
#### SH After:
sh-after
#### Geode OQL Before:
geode-oql-before
#### Geode OQL After:
geode-oql-after

**Comment by tzolov** [comment]
IMO this is ready for review. 

Note that i've upgraded the ace-builds from 1.1.8 to 1.1.9.  The is 1.2.0 version which provides even better syntax highlighting experience (for the SQL based languages) but it may require some other component upgrade was well.

**Comment by nberserk** [comment]
+1, much better than the current one.

**Comment by Leemoonsoo** [comment]
Tested and Looks good to me.

**Pull request closed without merging**
