### PR TITLE
ZEPPELIN-106: Display interactive form in Iframe mode of paragraph

### PR DESCRIPTION
**Pull request by tribbloid**
ZEPPELIN-106: Display interactive form in Iframe mode of paragraph

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the contribution. Looks good to me.
By the way, Does mvn-pkg.sh supposed to be included in this PR?

**Comment by tribbloid** [comment]
WTH How does that came to pull request?. Sorry please delete that file or merge the previous version. Never use github before

Yours Peng

**Comment by corneadoug** [comment]
@tribbloid I'm digging into old PR's
This issue was already resolved into master, could you close the PR?
Thank you

**Comment by tribbloid** [comment]
Sorry about that

**Pull request closed without merging**
