### PR TITLE
Update the How to contribute to Zeppelin

### PR DESCRIPTION
**Pull request by anthonycorbacho**
I light update of the `How to contribute to Zeppelin`, including:
 * Update the link (jira, mailling list, zeppelin)
 * Add a list of things to do before creating a new PR

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
LGTM~

**Comment by jongyoul** [comment]
@anthonycorbacho Please fix the build command of 74th line of your file for more details.

From,
```
mvn install -Dspark.version=1.0.1 -Dhadoop.version=2.2.0
```

To,
```
mvn install -Phadoop-2.2 -Dhadoop.version=2.2.0 -Pspark-1.3 -Dspark.version=1.3.0
```

**Comment by anthonycorbacho** [comment]
thankx for the catch

**Comment by jongyoul** [comment]
LGTM

**Comment by swkimme** [comment]
LGTM! Great!

**Pull request closed without merging**
