### PR TITLE
minor doc update for running on YARN

### PR DESCRIPTION
**Pull request by felixcheung**
Include info on SPARK_YARN_JAR can be HDFS

### CODE REVIEW

**Comment by felixcheung** [comment]
@jongyoul @swkimme Could you please review?

**Comment by Leemoonsoo** [comment]
LGTM :+1:

**Comment by felixcheung** [comment]
Great! Congrats for the move to apache!

**Comment by Leemoonsoo** [comment]
Thanks. :-) 
Many thanks for the contribution!

**Comment by jongyoul** [comment]
LGTM. Thanks again for fixing my typo. :+1:

**Comment by swkimme** [comment]
LGTM!

**Pull request closed without merging**
