### PR TITLE
Add firebug and firepath for debugging

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
Hi, 

I've refactored some of the selenium related test case, and added firebug and firepath for debugging so that if CI is failing on travis it can be debugged on local.

Also I feel that we should delete notebook once selenium test case is finished.

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Also, is it a good idea to get rid of, this, as well ? and let selenium test case be part of regular test as well.

    boolean endToEndTestEnabled() {
        return null != System.getenv("CI");
    }

**Comment by corneadoug** [comment]
It depends if they are working :)
One problem we had in the past was that selenium test tends to not work on classic machine.
Build is already hard to finish for some, but it was almost impossible with selenium tests running

**Comment by corneadoug** [comment]
Anybody with selenium experience to test that? :p

**Comment by prabhjyotsingh** [comment]
Testing should be easy; change the following

    boolean endToEndTestEnabled() {
        return true; //null != System.getenv("CI");
    }

and execute ZeppelinIT test suit.

PS: this version of selenium doesn't support latest version of firefox, I did a fix on FF25. which will be fixed with https://github.com/apache/incubator-zeppelin/pull/504

**Comment by prabhjyotsingh** [comment]
Can we merge this, if there is discussion around this ?

**Comment by Leemoonsoo** [comment]
Thanks @prabhjyotsingh for the nice improvement.

Will it be possible remove binaries under `zeppelin-server/src/test/resources/firebug` from source tree and download them on the fly during the test?

**Comment by prabhjyotsingh** [comment]
Yes, I thought about it as well (to download from https://getfirebug.com/releases/firebug/1.11/)  and then continue. But then I didn't wanted CI to break in case it fails to download.

Also we don't expect to those "*.xpi" to change anytime.

**Comment by Leemoonsoo** [comment]
I think we need to avoid ship binaries in source release. But in this way, firebug binaries are going to be included in the source release.

**Comment by prabhjyotsingh** [comment]
Sure @Leemoonsoo appreciate your point. Thanks for the suggestion. Removed binaries from the project.

**Comment by Leemoonsoo** [comment]
@prabhjyotsingh Thanks for addressing removal of binary.
LGTM

**Comment by r-kamath** [comment]
@prabhjyotsingh please rebase

**Comment by prabhjyotsingh** [comment]
@Leemoonsoo @corneadoug @r-kamath   rebased. Thanks.

**Comment by corneadoug** [comment]
CI is green, merging if there is no more discussions

**Pull request closed without merging**
