### PR TITLE
update error message and output style

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
Styling text and error output

### What type of PR is it?
Improvement

### How should this be tested?
Run a paragraph to see the output text style

### Screenshots
Before
before
<hr>
After (error)
after1
<hr>
After (success)
after2

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
LGTM. Looks nicer.

**Comment by jongyoul** [comment]
Looks nice, too.

**Comment by Leemoonsoo** [comment]
Thanks @r-kamath for the contribution.

The reason in the beginning code editor has vertical bar was, to distinguish it from the output.
If output has the same vertical bar, it's bit confusing.

see this screenshot
image

And it 'simple' looknfeel designed to have minimal view, 'report' looknfeel designed to have clear dashboard/documentation like view, and i'm not sure it fits there.


In this project, some GUI changes may suitable for some users but not for the others. We'll need to make a decision for those changes. To do that, how about we discuss and define some kind of GUI design guidelines / principles (e.g. https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61328042) first ?

**Comment by gauravkumar37** [comment]
I agree with both @Leemoonsoo as well as @r-kamath.
I suggest we remove the vertical bar from the output and have the color of the output differentiate errors from success. We could leave the vertical bar of the editor as it is, or we could change the color of the vertical bar w.r.t. error/success. So vertical bar's color could say about it's output.
Grey: normal
Orange: edited
Red: output contains atleast 1 error
Green: output contains no error

While we are at it, we could, if possible, have different colors of different lines within the same output. For example, if there are are 4 lines in the output- 3 are fine while the 4th has an error. We show first 3 in green and the error in red within the same output area.

**Comment by corneadoug** [comment]
Agree with moon, the left bar was to differentiate the text editor from the output, so it makes it more confusing.
I'm not sure a color code is needed since the status of the query is shown (READY, FINISHED, ERROR, ABORT)

**Comment by r-kamath** [comment]
@Leemoonsoo @corneadoug cool. Thanks for the feedback

**Pull request closed without merging**
