### PR TITLE
ZEPPELIN-238: Remove unused swagger code

### PR DESCRIPTION
**Pull request by mindprince**

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Looks good to me!

**Comment by nberserk** [comment]
no use of swagger in the future also ?

**Comment by mindprince** [comment]
We can add swagger back if and when it is required. Right now, this was just dead code.

**Comment by eranwitkon** [comment]
I think having an updated Swagger information including swagger.json for swagger UI is a good thing for zeppelin as it allows developers to integrate with zeppelin through services.

I am in the process of writing more REST tests and documenting the use of REST API (per the community request) and having Swagger working could help me a lot :-)

**Comment by mindprince** [comment]
@Leemoonsoo Why was swagger removed earlier? Do we want to document the REST API using swagger now? If not we can merge this. If we do want to document using swagger, we should file a JIRA to fix swagger and make it workable.

**Comment by nberserk** [comment]
I think we need more rest apis for enterprise support. and then swagger will be useful soon.

**Comment by Leemoonsoo** [comment]
@mindprince zeppelin-docs has old, outdated, documentation. With the preparation of moving to ASF, zeppelin-docs was removed (https://github.com/NFLabs/zeppelin/pull/289) while it's got some third-party dependencies. And that makes error on swagger, and swagger is disabled by https://github.com/NFLabs/zeppelin/pull/311 to remove the error.

**Comment by Leemoonsoo** [comment]
One question. I think document for REST api will be more useful when it is published in the website.
Can swagger help it?

**Comment by mindprince** [comment]
Yeah, I think we should rather have static documentation of REST API on the website. Something like https://spark.apache.org/docs/latest/monitoring.html#rest-api
Running a swagger servlet wherever you are running Zeppelin Server seems like an overkill to me.

**Comment by mindprince** [comment]
I see that we merged https://github.com/apache/incubator-zeppelin/pull/256 which added REST API documentation to the website.

@eranwitkon @Leemoonsoo Do you think we can merge this now?

**Comment by eranwitkon** [comment]
I think we should merge PR #266 which touches the same files and PR #268 which adds the REST API test and the re-base this one and merge.

**Comment by mindprince** [comment]
@Leemoonsoo @eranwitkon I see that the PRs which you mentioned were merged into master. So, I have rebased my changes on top of the current master. Please take a look. Thanks!

**Comment by eranwitkon** [comment]
+1 from me. merged, build and tested.

On Wed, Sep 9, 2015 at 9:11 AM Rohit Agarwal <notifications@github.com>
wrote:

> @Leemoonsoo <https://github.com/Leemoonsoo> @eranwitkon
> <https://github.com/eranwitkon> I see that the PRs which you mentioned
> were merged into master. So, I have rebased my changes on top of the
> current master. Please take a look. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-zeppelin/pull/226#issuecomment-138795929>
> .
>
-- 
Eran | "You don't need eyes to see, you need vision" (Faithless)

**Comment by Leemoonsoo** [comment]
I'm merging if there're no more discussions

**Pull request closed without merging**
