### PR TITLE
[ZEPPELIN-952] Refine website style

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
- update document style (font, line-spacing)
- apply same formats for documents
- fix broke document styles

### What type of PR is it?
Documentation

### What is the Jira issue?
[ZEPPELIN-952](https://issues.apache.org/jira/browse/ZEPPELIN-952)

### Screenshots (if appropriate)
**Before**
screen shot 2016-06-04 at 9 51 38 pm

**After**
screen shot 2016-06-04 at 9 15 08 pm

**Before**
screen shot 2016-06-04 at 10 08 53 pm

**After**
screen shot 2016-06-04 at 10 08 18 pm

**Before**
screen shot 2016-06-04 at 10 10 47 pm

**After**
screen shot 2016-06-04 at 10 11 22 pm

**Before**
screen shot 2016-06-04 at 10 12 36 pm

**After**
screen shot 2016-06-04 at 10 12 55 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@minahlee Nice work! Definitely it looks much better than before 👍

**Comment by bzz** [comment]
👍  looks great to me!

**Comment by Leemoonsoo** [comment]
Looks good to me!

**Comment by minahlee** [comment]
Merge if there is no more discussion

**Pull request closed without merging**
