### PR TITLE
increase implicitlyWait for WebDriver

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
This is with respect to travis build failure on `sendKeys`.

An implicit wait is to tell WebDriver to poll the DOM for a certain amount of time when trying to find an element or elements if they are not immediately available. The default setting is 0. Once set, the implicit wait is set for the life of the WebDriver object instance.

#### Update
Travis mostly fails on `sendKeys`; hence, change the way text is sent to paragraph.

### What type of PR is it?
Hot Fix

### What is the Jira issue?
N/A

### How should this be tested?
CI should be green.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
This seems to fix PR https://github.com/apache/incubator-zeppelin/pull/783

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Merge this ?

**Comment by Leemoonsoo** [comment]
I'm merging it into the master.

**Pull request closed without merging**
