### PR TITLE
Zeppelin 639

### PR DESCRIPTION
**Pull request by cjmatta**
### What is this PR for?
JDBCInterpreter should check for a null object before simply calling `getString`. This will prevent poorly implemented JDBC drivers from causing a NullPointerException.

### What type of PR is it?
Improvement

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-639

### How should this be tested?
Run the `testSelectQueryWithNull` test included with this PR.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by cjmatta** [comment]
Could someone give some guidance as to why this build failed in CI? The error seems to be related to the test:
```
[ERROR] /home/travis/build/apache/incubator-zeppelin/jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java:[130,65] constructor InterpreterContext in class org.apache.zeppelin.interpreter.InterpreterContext cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.Map<java.lang.String,java.lang.Object>,org.apache.zeppelin.display.GUI,org.apache.zeppelin.display.AngularObjectRegistry,org.apache.zeppelin.resource.ResourcePool,java.util.List<org.apache.zeppelin.interpreter.InterpreterContextRunner>,org.apache.zeppelin.interpreter.InterpreterOutput
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String,<nulltype>,<nulltype>,<nulltype>,<nulltype>,<nulltype>
  reason: actual and formal argument lists differ in length
```

This builds fine on my machine, and the test is set up exactly like the other tests...

**Comment by Leemoonsoo** [comment]
Could you try merge current master branch?

**Comment by jongyoul** [comment]
@cjmatta This PR has irrelative commits. Could you please remove them and push your change only? For example, @vgmartinez's commit is reviewed by #667. Check it, please.

**Comment by cjmatta** [comment]
@jongyoul whoops my bad on that. Those commits have been reverted.

**Comment by jongyoul** [comment]
@cjmatta Thanks for fixing it. There's one more request that it's not recommended to update ``note.json``  without adding extra example. Could you please also fix it?

**Comment by cjmatta** [comment]
Oops, totally missed that, sorry about that.

**Comment by cjmatta** [comment]
The latest web server code is failing the CI tests. The JDBC project compiled without error though.

**Comment by jongyoul** [comment]
@cjmatta No problem. Thanks for fixing it. And I will try it.

**Comment by jongyoul** [comment]
@cjmatta I've tested it.

Merging if there's no more discussion

**Pull request closed without merging**
