### PR TITLE
MapR 4 Profile corrected, Added Apache Drill Interpreter

### PR DESCRIPTION
**Pull request by pfcurtis**
* Corrected the "mapr4" profile to correctly pull the Maven artifacts from the MapR Maven repository. Added the MapR Maven repo to the POM.

* Added an Apache Drill interpreter. This interpreter **requires** the builder to obtain the Apache Drill JDBC and add it to their local Maven repository prior to building. This will incorporate the Drill JDBC driver into the build-dist profile

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for making pullrequest!

It looks like org.apache.drill:drill-jdbc-all:jar:1.0.0-mapr-r1 is not published in any maven repository that's why build is failing. How do you usually use drill-jdbc driver? download from some package?

Another one is, could you explain little bit about `spark/dependency-reduced-pom.xml`?

**Comment by pfcurtis** [comment]
On 6/20/15 6:44 PM, Lee moon soo wrote:
>
> Thanks for making pullrequest!
>
> It looks like org.apache.drill:drill-jdbc-all:jar:1.0.0-mapr-r1 is not 
> published in any maven repository that's why build is failing. How do 
> you usually use drill-jdbc driver? download from some package?
>
The Drill driver is only contained in the Drill distribution at this 
time. I have entered a JIRA to provide the driver via some Maven repo. 
In order to accomplish the build, I retrieved the driver from the Drill 
distribution, and used mvn install to place it in my local repo. The 
command line is in the commit message.
>
> Another one is, could you explain little bit about 
> |spark/dependency-reduced-pom.xml|?
>
I do not know where this file came from exactly .... I did not create 
it, and when I performed a git fetch from the upstream (the Apache 
Zeppelin github), this file was created. I assumed it was a part of the 
Zeppelin build. If it is not required, remove it as I don't reference or 
use it.

Regards,
Paul

**Comment by pfcurtis** [comment]
I've removed the incorrect POM file that was created during packaging.

**Comment by Leemoonsoo** [comment]
@pfcurtis 
Could you link here a JIRA issue that publishing drill-jdbc driver to maven repo?

**Comment by pfcurtis** [comment]
https://issues.apache.org/jira/browse/DRILL-3329

**Comment by pfcurtis** [comment]
Fetched the upstream master and checked that everything still compiles and executes properly. I think this (and the Drill interpreter) are ready to merge. The Drill JDBC will be in the Apache public repo with this newly released Drill version 1.1.

**Comment by Leemoonsoo** [comment]
Thanks. if adding a basic unittest is not too difficult, can we have one?
I've seen drill have some facilities for testing jdbc (eg. https://github.com/apache/drill/blob/master/exec/jdbc/src/test/java/org/apache/drill/jdbc/test/JdbcTestQueryBase.java), and it looks like it does not need external drill running (i'm not sure).

If the test facilities can be run without any external dependency, can we have one basic unittest? So later, anyone can simply add more test to this interpreter module when there're some problem.
And let me know if you need any help.

**Comment by WalterDalton** [comment]
I would be interested in seeing this merged!

**Comment by jongyoul** [comment]
It would be better to split this PR to two separate issues of drill interpreter and MapR profile.

**Comment by bzz** [comment]
+1 for splitting. @WalterDalton which part are you interested in particular?

**Comment by pfcurtis** [comment]
@WalterDalton: I agree. Let me split this into two pull requests. The reason the Apache Drill PR hasn't been merged is I haven't had the time to build out unit tests.

**Comment by WalterDalton** [comment]
I'd love to see both parts merged actually, I'd love to start hitting drill with Zeppelin AND I am running MapR :)

**Comment by pfcurtis** [comment]
I think it is a good idea to split the profiles from the Drill interpreter. As the Drill interpreter is simply a JDBC connection, that should be almost no effort to maintain.

The MapR profiles just need to be kept up-to-date.

Regards.

----- Original Message -----

**Comment by WalterDalton** [comment]
Any further update or beer I could buy someone to get this merged in? :)

**Comment by jongyoul** [comment]
@pfcurtis Hi, #361 works in progress. And Drill also uses a jdbc connection. How about removing drill interpreter and updating the mapr profile up-to-date?

**Comment by pfcurtis** [comment]
I will rework the pull request for the MapR profiles, and drop the code 
for the Drill interpreter.

paul

**Comment by jongyoul** [comment]
@pfcurtis Sounds great!! Thanks!!

**Comment by Leemoonsoo** [comment]
@pfcurtis :+1:

**Comment by pfcurtis** [comment]
I'm closing this pull request, and re-opening a new one with only the MapR profile updates.

**Pull request closed without merging**
