### PR TITLE
[ZEPPELIN-484] A small utility to help review the pullrequest.

### PR DESCRIPTION
**Pull request by Leemoonsoo**
This PR address https://issues.apache.org/jira/browse/ZEPPELIN-484.

We've got discussions recently about impasse of pullrequest and speeding up of accepting pullrequest.
This small utility can be used when reviewer want to test the pullrequest.

Usage is 
```
dev/test.py [#PR]
```

for example
```
dev/test.py 500
```
will create local branch `pr500` and add remote repository of contribution, fetch and merge it for the test.

This script will help reduce small bit of time of reviewing.

### CODE REVIEW

**Comment by r-kamath** [comment]
@Leemoonsoo I do `curl https://patch-diff.githubusercontent.com/raw/apache/incubator-zeppelin/pull/<PR#>.patch | git apply` in master, review it and reset!

**Comment by prabhjyotsingh** [comment]
@r-kamath solution looks simpler, both are hacky though :smiley:

**Comment by jongyoul** [comment]
I've tested. Looks good. It's enough to me to test pr. Thanks.

**Comment by corneadoug** [comment]
Should we also include some:
``git clean -dxf`` and then launch build then?

**Comment by bzz** [comment]
Looks great to me.

Another way to do the same is a small `hub` [github/hub](https://github.com/github/hub) that allows you to do, apart from many other useful things, PR checkouts like
```
hub checkout https://github.com/apache/incubator-zeppelin/pull/513
```

**Comment by bzz** [comment]
@Leemoonsoo If we want to go further with this tool, as we already have `./dev/merge_zeppelin_pr.py` may be we could name it something like `./dev/test_zeppelin_pr.py`? 

I feel that this, as well as a couple of lines of text comments in the header after the licence boilerplate, will give a better idea of it's purpose for people who will just notice it in the filesystem, what do you think?

**Comment by Leemoonsoo** [comment]
Thanks all the feedbacks and alternative solutions.

I have changed script name from `test.py` to `test_zeppelin_pr.py` and add more comment.
Adding `git clean -dxf` will remove untracked files. I think it's better leave it up to developers.

**Comment by bzz** [comment]
Looks great to me

**Comment by Leemoonsoo** [comment]
merging into master

**Pull request closed without merging**
