### PR TITLE
ZEPPELIN-406 Handle license issue found in 0.5.5-incubating rc2

### PR DESCRIPTION
**Pull request by Leemoonsoo**
This issue addresses license problem found in 0.5.5-incubating rc2 
https://issues.apache.org/jira/browse/ZEPPELIN-406

* Removes unnecessary files 

         docs/assets/bootstrap-3.0.2-dist.zip
         docs/assets/themes/twitter/

* Add Apache license header if applicable
* Add license info to LICENSE 

         GLYPHICONS Halflings
         jekyll-bootstrap
         jekyll

* Adjust rat plugin exclude rule

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Ready to merge. This PR addresses license of files in /docs (website src) directory.
Please review and comment here if there're any other license related issues found.

**Comment by felixcheung** [comment]
looks good. it's a bit odd to have a html license header on the json content - should we just put the json sample on the API doc page instead of separate files?

**Comment by bzz** [comment]
Tested and looks good to me.

The only thing though (not sure if that is relevant) is that somehow a downloads page for me is missing the content of the #387 like KEYS file, src, binary section, etc.

**Comment by Leemoonsoo** [comment]
@felixcheung 
Thanks for review. I think that make sense.

@bzz 
#387 is merged into master branch only. And it was for 0.5.0 release, not this release. Download page for this release will be handled by https://issues.apache.org/jira/browse/ZEPPELIN-390 after vote completed. I'll add bootstrap to LICENSE.


Additionally i've found it's better to mention 3rd party dependency version in LICENSE, and different LICENSE file for binary package.

So, i'll do

* [ ] put the json example on the doc page instead of separate file
* [ ] add version of 3rd party dependency in LICENSE
* [ ] add bootstrap to LICENSE
* [ ] add license of dependencies bundled in binary package into LICENSE when building binary package

**Comment by Leemoonsoo** [comment]
3rd party dependency licenses are handled 

/LICENSE - for source package
/NOTICE  - for source package
/licenses - copies of 3rd party dependency license

/zeppelin-distribution/src/bin_license/LICENSE - for binary package
/zeppelin-distribution/src/bin_license/NOTICE - for binary package
/zeppelin-distribution/src/bin_license/licenses - copies of 3rd party dependency license for binary package

/zeppelin-distribution/src/bin_license is merged into /LICENSE, /NOTICE, /licenses by /dev/create_release.sh when creating release package.

Please review it.

**Comment by Leemoonsoo** [comment]
I'll merge if there're no more discussions and restart vote with rc3

**Comment by khalidhuseynov** [comment]
+1 for merge

**Comment by minahlee** [comment]
LGTM

**Comment by felixcheung** [comment]
looks good. this is closed?

**Comment by Leemoonsoo** [comment]
It is merged into branch-0.5.5, but not master since master diverged too much to merge directly.
I'll create another PR to merge this changes to master.

**Pull request closed without merging**
