### PR TITLE
ZEPPELIN-463: UI freezes if table renders a lot of rows

### PR DESCRIPTION
**Pull request by prabhjyotsingh**

### CODE REVIEW

**Comment by r-kamath** [comment]
@prabhjyotsingh is there a way to tweak Perfect Scrollbar to make it work on large dataset ?

**Comment by corneadoug** [comment]
Large table dataset will always be slow.
The best way to limit that would be to have pagination on the result

**Comment by prabhjyotsingh** [comment]
Yes, I thought of doing pagination(https://github.com/samu/angular-table) as well, but was not too sure. And this looked like not breaking any of the UI elements and/or formatting.

screen shot 2015-11-25 at 9 59 57 pm

**Comment by felixcheung** [comment]
I'm not sure about truncating it at the angular level - it seems we should cut it off from the source (eg. collect on Spark DataFrame), and we would need some kind of feedback to the user - would be bad if some rows are missing from the table view without any clue.

**Comment by prabhjyotsingh** [comment]
agreed @felixcheung, but truncating data from source means the graph/chart that are drawn on UI will also based on truncated data (incomplete data).

And with this work around (not using perfectScrollbar if there are more than 10,000 rows), we are able go atleast 10x (95,212 rows for batting; data imported from http://seanlahman.com/files/database/lahman-csv_2015-01-24.zip)

**Comment by prabhjyotsingh** [comment]
Is it ok, if we don't use perfectScrollbar if there are more than 10,000 rows ?

**Comment by corneadoug** [comment]
Well, that's a hack. it doesn't really take care of the actual performance problem.
We can Merge it as a quick fix. However we should take care of those issues later.

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
