### PR TITLE
Add basic documentation for Markdown

### PR DESCRIPTION
**Pull request by r-kamath**

### CODE REVIEW

**Comment by felixcheung** [comment]
looks good. we use markdown4j you might want to link to https://code.google.com/p/markdown4j/ for additional extension it supports

**Comment by r-kamath** [comment]
@felixcheung thanks for the suggestion. I've included the markdown4j link in d839992

**Comment by prabhjyotsingh** [comment]
LGTM :+1:

**Comment by Leemoonsoo** [comment]
Because of changes introduced by https://issues.apache.org/jira/browse/ZEPPELIN-445, 

You'll need to change menu, too
https://github.com/apache/incubator-zeppelin/blob/master/docs/_includes/themes/zeppelin/_navigation.html#L43

And asset path need to be 
{{BASE_PATH}}/assets/themes/zeppelin/img/docs-img/markdown-interpreter-setting.png

**Comment by Leemoonsoo** [comment]
Looks good to me. CI build failing is irrelevant.
Merge if there're no more discussions

**Pull request closed without merging**
