### PR TITLE
[ZEPPELIN-696] Add notification system for AngularJS z functions

### PR DESCRIPTION
**Pull request by doanduyhai**
### What is this PR for?
Add notification system for AngularJS z functions. Now that we expose the `z` Angular object, we should also catch error/exceptions and display error messages properly to the user.

I changed a little bit the default settings for **ngToast**. Instead of having notifications on **bottom right**, I let the default value undefined.

For **Interpreter** page notification, I force the position to **bottom right** as before when using default config.

For `z` functions error messages, I choose to display notifications on **top right** corner because it's clearer. See screen capture

_This is a sub-task of epic **[ZEPPELIN-635]**_

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Code Review
* [ ] - Simple Test

### Is there a relevant Jira issue?
**[ZEPPELIN-696]**

### How should this be tested?
* `git fetch origin pull/744/head:AngularJSNotification`
* `git checkout AngularJSNotification`
* `mvn clean package -DskipTests`
* `bin/zeppelin-daemon.sh restart`
* Create a new note
* In the first paragraph, put the following code

```html
%angular

<form class="form-inline">
  <button type="submit" class="btn btn-primary" ng-click="z.runParagraph()"> Run Paragraph Without Id</button>
  <button type="submit" class="btn btn-primary" ng-click="z.runParagraph('20160223-141919_305734436')"> Run Paragraph Without Wrong Id</button>
  <button type="submit" class="btn btn-primary" ng-click="z.angularBind('superhero', superhero)"> Angular Bind Without Paragraph Id</button>
  <button type="submit" class="btn btn-primary" ng-click="z.angularUnbind('superhero')"> Angular UnBind Without Paragraph Id</button>
</form>
```
* Click on each button to see the appropriate error message

### Screenshots (if appropriate)
angularnotification

### Questions:
* Does the licenses files need update? --> **No**
* Is there breaking changes for older versions?  --> **No**
* Does this needs documentation?  --> **Yes**

[angular-growl-2]: http://janstevens.github.io/angular-growl-2/
[ZEPPELIN-635]: https://issues.apache.org/jira/browse/ZEPPELIN-635
[ZEPPELIN-696]: https://issues.apache.org/jira/browse/ZEPPELIN-696

### CODE REVIEW

**Comment by corneadoug** [comment]
We already have ngtoast for that

**Comment by doanduyhai** [comment]
Right, didn't know that we had ngToast. I never see it in action. Will remove angular-growl-2

**Comment by doanduyhai** [comment]
@corneadoug @Leemoonsoo 

Rebased from master, only JS change, can be reviewed and merged quickly. 

Do you want me to add also a test in ZeppelinIT to test for the presence at the notification in case of error ,

**Comment by Leemoonsoo** [comment]
I have tested and working well. 
Looks good to me. 

@corneadoug Can you take a look, too?

**Comment by Leemoonsoo** [comment]
@corneadoug ping

**Comment by doanduyhai** [comment]
Can we merge this PR so I can move to the next sub-task ?

**Comment by doanduyhai** [comment]
ping @Leemoonsoo @corneadoug

**Comment by corneadoug** [comment]
@doanduyhai LGTM

**Pull request closed without merging**
