### PR TITLE
[ZEPPELIN-788] Update Lens interpreter to Lens 2-5-0-beta

### PR DESCRIPTION
**Pull request by lresende**
### What is this PR for?
Update Lens interpreter to use Lens 2.5.0-beta release

### What type of PR is it?
[Improvement]

### What is the Jira issue?
[ZEPPELIN-788](https://issues.apache.org/jira/browse/ZEPPELIN-788)

### CODE REVIEW

**Comment by bzz** [comment]
CI failure is not relevant here and is due to spark download failure. 
I have re-opened [ZEPPELIN-786](https://issues.apache.org/jira/browse/ZEPPELIN-786) to take care of it.

**Comment by lresende** [comment]
@bzz Thanks, I was wondering if this was just a side effect of something else other then the release update.

**Comment by felixcheung** [comment]
This was failing because of a corrupted download as wellhttps://s3.amazonaws.com/archive.travis-ci.org/jobs/120505168/log.txt

**Comment by bzz** [comment]
Yup, let's just keep track of those under ZEPPELIN-786 What I meant is - I think it should not block this PR.

**Comment by lresende** [comment]
@bzz are we still having some issues with the ci environment for zeppelin ?

**Comment by lresende** [comment]
@bzz @felixcheung Ok, all tests are passing, ready for review

**Comment by felixcheung** [comment]
LGTM
merging if no more comment

**Pull request closed without merging**
