### PR TITLE
upgrade angularJS from 1.3.x to 1.5.0 (stable)

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
upgrade angularJS from 1.3.x to 1.5.0 (stable)

### What type of PR is it?
Improvement

### Todos
* [x] - Upgrade in bower.json
* [x] - make upgrade change in app.js

### Is there a relevant Jira issue?
N/A

### How should this be tested?
Try `grunt test` on zeppelin-web

### Questions:
* Does the licenses files need update?
No
* Is there breaking changes for older versions?
No
* Does this needs documentation?
No

### CODE REVIEW

**Comment by felixcheung** [comment]
looks like the zeppelin page is up in the screenshot when selenium test failed:
```
10:37:56,531 ERROR org.apache.zeppelin.AbstractZeppelinIT:173 - Exception in ParagraphActionsIT while testCreateNewButton 
org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 8 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'testing-worker-linux-docker-7b2e2a82-3397-linux-9', ip: '172.17.8.24', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-40-generic', java.version: '1.7.0_76'
Session ID: 240c3bb6-eb48-4e3c-9917-046f70a6b4a7
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by prabhjyotsingh** [comment]
Thank you @felixcheung. Yes, I noticed CI was continuously failing for this.

    https://travis-ci.org/apache/incubator-zeppelin/builds/116868449
    https://travis-ci.org/apache/incubator-zeppelin/builds/116864607
    https://travis-ci.org/apache/incubator-zeppelin/builds/116860666
    https://travis-ci.org/apache/incubator-zeppelin/builds/116834473

Hence, created a new PR https://github.com/apache/incubator-zeppelin/pull/785. Tried to merge that here, and check if this works.

**Comment by prabhjyotsingh** [comment]
Last build errors with 

    [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:install-node-and-npm (install node and npm) on project zeppelin-web: Could not download Node.js: Got error code 522 from the server. -> [Help 1]

But, now its green.

**Comment by felixcheung** [comment]
so looks like this is merged with #785 ?
let's get that PR committed first...

**Comment by prabhjyotsingh** [comment]
Yes, have merged this with #785.

**Comment by prabhjyotsingh** [comment]
I've merged with master, and this can now be review.

**Comment by felixcheung** [comment]
looks good.
@corneadoug any issue with this angular version?

**Comment by prabhjyotsingh** [comment]
Merge this?

**Pull request closed without merging**
