### PR TITLE
ZEPPELIN-426 - Allowing new paragraph under the last one

### PR DESCRIPTION
**Pull request by corneadoug**
Adding a paragraph under the last one of the notebook was not allowed.
I tested a lot of different cases:
* While running the full note
* With or Without content in the last paragraph
* with or Without saved content in the last paragraph

And didn't find any issue to allow that feature on that last paragraph

### CODE REVIEW

**Comment by corneadoug** [comment]
Ready for tests/reviews

**Comment by r-kamath** [comment]
LGTM!

**Comment by prabhjyotsingh** [comment]
This may be totally unrelated, but, both $.fn.jquery and jQuery.fn.jquery returns "2.1.4"; which means $ is pointing to jQuery. Shouldn't we allow only one of these, so that its always more readable.

Otherwise Looks good to me, gets compiled well, runs well.

**Comment by jongyoul** [comment]
Working well. LGTM

**Comment by corneadoug** [comment]
@prabhjyotsingh good point, actually none of them should be authorized.
Usually we ask people not to use $ or jQuery if it's not in a directive, however it was done in some cases.
However since people use it, we ask that to be made with the help of ``angular.element``.
There might be a few leftover in the code that are not using it, bit this should be the work of another PR

**Pull request closed without merging**
