### PR TITLE
[ZEPPELIN-742] Add documentation for front-end AngularJS AP

### PR DESCRIPTION
**Pull request by doanduyhai**
### What is this PR for?
This JIRA:

* add documentation for the new paragraphId display in the paragraph command dialog. Instead of just adding some description to the paragraphId, I took the opportunity to also document the entire Zeppelin UI Layout and added a menu entry **UI Layout** under menu **QuickStart**. It is inspired by the content of the talk on Zeppelin at different conferences
* rename the menu **Display System** / **Angular** to **Display System** / **Back-end Angular Interactions**  
* add a new entry **Front-end Angular Interactions** under the menu **Display System** to describe the new front-end AngularJS API introduced by this epic

_This is a sub-task of epic **[ZEPPELIN-635]**_

### What type of PR is it?
[Documentation]

### Todos
* [ ] - Check documentation

### What is the Jira issue?
**[ZEPPELIN-6742]**

### How should this be tested?
Build Zeppelin documentation locally and check

### Screenshots (if appropriate)

New **QuickStart** / **UI Layout** documentation which mentions the **paragraphId**

zeppelin_ui_layout

New **Display System** / **Front-end Angular Interactions** menu to describe the new front-end AngularJS API introduced by this epic

front-end angular interactions

### Questions:
* Does the licenses files need update? --> No
* Is there breaking changes for older versions?  --> No 
* Does this needs documentation?  --> No

[ZEPPELIN-635]: https://issues.apache.org/jira/browse/ZEPPELIN-635
[ZEPPELIN-742]: https://issues.apache.org/jira/browse/ZEPPELIN-742

### CODE REVIEW

**Comment by doanduyhai** [comment]
Ping @Leemoonsoo  &  @felixcheung 

Finally the **LAST** JIRA for this **EPIC** !

**Comment by felixcheung** [comment]
LGTM

**Comment by doanduyhai** [comment]
Build green :)

**Comment by Leemoonsoo** [comment]
Great work @doanduyhai. 

One thing is, instead of 'Back-end Angular Interactions' and 'Front-end Angular Interactions', how about 'Angular (backend API)', 'Angular (frontend API)' ? Because, they're both api for front-end <-> back-end interactions.

**Comment by doanduyhai** [comment]
@Leemoonsoo Done

**Comment by doanduyhai** [comment]
Ping @Leemoonsoo  @felixcheung

**Comment by Leemoonsoo** [comment]
LGTM and merge if there're no more discussions!

**Pull request closed without merging**
