### PR TITLE
ZEPPELIN-458 Fix testAbortParagraphStatusOnInterpreterRestart

### PR DESCRIPTION
**Pull request by jongyoul**
- Changed how to check some paragraph is aborted
- See the https://issues.apache.org/jira/browse/ZEPPELIN-458 for more details

### CODE REVIEW

**Comment by jongyoul** [comment]
I've changed restart timing and checked the status of paragraphs. The test passed if at least one of paragraphs has Status.ABORT.

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by jongyoul** [comment]
Thanks.

**Comment by bzz** [comment]
Looks good to me

**Comment by jongyoul** [comment]
Ready to merge

**Comment by jongyoul** [comment]
Merging if there isn't another discussion.

**Comment by khalidhuseynov** [comment]
Thanks for the fix, LGTM!

**Pull request closed without merging**
