### PR TITLE
[ZEPPELIN-809] Add annotation to public API

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Implement @ZeppelinApi @Experimental annotations and apply them in the public api.
Also mark @deprecated global scope angular object methods

### What type of PR is it?
Feature

### Todos
* [x] - Implement @ZeppelinApi, @Experimental annotations
* [x] - Apply annotation to public Api
* [x] - Mark deprecated global scope angular object related methods

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-809

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
Looks goot to me +1

**Comment by felixcheung** [comment]
what's our guideline on what is experimental?
should that be added to https://zeppelin.incubator.apache.org/docs/0.6.0-incubating-SNAPSHOT/rest-api/rest-interpreter.html?

**Comment by bzz** [comment]
Documenting stable API with annotations looks great to me.

**Comment by Leemoonsoo** [comment]
@felixcheung 

I have added @ZeppelinApi annotation to REST api endpoint.

Here's javadoc comment about two annotations. 

ZeppelinApi
```
APIs exposed to extends pluggable components or exposed to enduser
```

Experimental
```
Might change or be removed at anytime, or be adopted as ZeppelinApi
```

What do you think?

**Comment by felixcheung** [comment]
sounds good, but how does a contributor/developer decides whether something new should be annotated as "Experimental" or "ZeppelinApi"?

**Comment by Leemoonsoo** [comment]
I think it can be decided by consensus. If community can not sure API will stay unchanged until next major release (at least), it should be annotated as 'Experimental' otherwise we can annotate 'ZeppelinApi'. Once we get enough experiences of these annotation, then we can build more detailed guideline. 

Do you have any good idea about how does a contributor decides?

**Comment by felixcheung** [comment]
Agreed. I think the model used in Spark is that if an API is:
- new
- expecting (significant) discussions/changes in this or the next minor release
Then it should be "Experimental".

**Comment by felixcheung** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Thanks @cloverhearts @felixcheung @bzz taking a look.
Merge if there're no more discussions

**Pull request closed without merging**
