### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by cyhsutw**
### What is this PR for?

Update README.md
    
- Unify code block styles (fenced code blocks).
- Add syntax highlighting in some code blocks.
- Fix unwanted link in option: `-Pmapr[version]`.
- General formatting.

### What type of PR is it?
Documentation

### Todos
None.

### What is the Jira issue?
N/A

### How should this be tested?
Preview the rendered README.md on GitHub.
View `README.md` on [cyhsutw/incubator-zeppelin:better-readme](https://github.com/cyhsutw/incubator-zeppelin/tree/better-readme)

### Screenshots (if appropriate)

Unwanted link in option: `-Pmapr[version]`:
screen shot 2016-04-16 at 12 21 34 am

### Questions:
* Does the licenses files need update? *no*
* Is there breaking changes for older versions? *no*
* Does this needs documentation? *no*

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Nice improvements. LGTM

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by felixcheung** [comment]
LGTM

**Comment by jeffsteinmetz** [comment]
Right after the `-Ppyspark` section you could also add a short section about the `-Psparkr` profile

```
-Psparkr (optional)

enable SparkR support for local mode
```

**Comment by darionyaphet** [comment]
Could add more info about sparkR install ?

**Comment by cyhsutw** [comment]
@jeffsteinmetz just added the option as you suggested.

@darionyaphet I think maybe we can make it another PR after this is merged.

**Comment by cyhsutw** [comment]
Hi all, 

I've made some changes according to @jeffsteinmetz's comment.
It would be appreciate if you could review my work again.

**Comment by jeffsteinmetz** [comment]
Thank you for the quick add @cyhsutw
@darionyaphet, A detailed SparkR readme is starting to take shape in the interpreter documentation subfolder

**Comment by elbamos** [comment]
Its missing a reference to -Pr.  I suggest

-Pr or -Psparkr (optional)

Alternative interpreters for R and sparkR.

**Comment by elbamos** [comment]
@jeffsteinmetz Which PR concerns the documentation?

**Comment by jeffsteinmetz** [comment]
mainly referring to 
https://github.com/apache/incubator-zeppelin/blob/master/docs/interpreter/r.md

**Comment by Leemoonsoo** [comment]
I think it would be better if both -Psparkr and -Pr are included with some description for them

**Comment by cyhsutw** [comment]
@Leemoonsoo I update the file with some description and links, you would please have a look at it?

**Comment by Leemoonsoo** [comment]
@cyhsutw. Thanks for taking care both profiles.

In the last commit, the description looks like

```
##### `-Pr` (optional)

enable [R](https://www.r-project.org/) support for local mode.
  
##### `-Psparkr` (optional)
enable [SparkR](https://spark.apache.org/docs/latest/sparkr.html) support for local mode.
```

Although i personally think your description is quite good separation of -Pr and -Psparkr for the future, currently both '-Pr' and '-Psparkr' integrated with pyspark. and '-Psparkr' is the one support local mode.

How about something like

```
##### `-Pr` (optional)

enable [R](https://www.r-project.org/) support with [SparkR](https://spark.apache.org/docs/latest/sparkr.html) integration.
  
##### `-Psparkr` (optional)

Another [R](https://www.r-project.org/) support with [SparkR](https://spark.apache.org/docs/latest/sparkr.html) integration as well as local mode support
```

What do you think @cyhsutw @elbamos @echarles @jeffsteinmetz ?

**Comment by cyhsutw** [comment]
@Leemoonsoo thanks for the explanation!

I'm +1 for your version of the description.
Just updated the file based on your comment.
I think it would be more clear to use yours than mine.

@elbamos @echarles @jeffsteinmetz what do you think about this 😄

**Comment by jeffsteinmetz** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
