### PR TITLE
[ZEPPELIN-35] Icons should have tool tips

### PR DESCRIPTION
**Pull request by minahlee**
Fix the issue that tooltip doesn't show by forcing angular version to 1.2.x.
angular-bootstrap doesn't support angular 1.3 for now.
Also downgraded ng-sortable to 1.1.6 since current one requires angular 1.3.

### CODE REVIEW

**Comment by corneadoug** [comment]
using ~1.2.0 doesn't fix the version, it sets only the minimum version

**Comment by Leemoonsoo** [comment]
This branch shows Tooltip. but seems like has some side effect. Like, click 'Notebook' in the menu bar refresh the page instead of showing notes available. Could you verify it?

**Comment by minahlee** [comment]
@Leemoonsoo I pushed a fix, can you review it please?

**Comment by corneadoug** [comment]
Just tested that branch since this PR has been here forever.
Everything works fine, however you need to merge master inside (no conflicts).
Also, there is one tooltip missing for the scheduler, so it would be nice to add:
* ``` tooltip-placement="top" tooltip="Run scheduler" ``` to the div on line 54 of notebook.html
* Change ``` tooltip="Run all the note" ``` to `` tooltip="Run all the notes" `` on line 26 of notebook.html

**Comment by corneadoug** [comment]
@minahlee Test were fixed, so I think it should be good

**Comment by corneadoug** [comment]
+1 for Merge!

**Comment by corneadoug** [comment]
Please? :D

**Comment by Leemoonsoo** [comment]
Existing user who has build zeppelin will see this error without removing zeppelin-web/bower_components directory.
```
[INFO] --- frontend-maven-plugin:0.0.23:bower (bower install) @ zeppelin-web ---
[INFO] Running 'bower --allow-root install' in /Users/moon/Projects/zeppelin/zeppelin-web
[INFO] bower angular-sanitize#1.2.28   cached git://github.com/angular/bower-angular-sanitize.git#1.2.28
[INFO] bower angular-sanitize#1.2.28 validate 1.2.28 against git://github.com/angular/bower-angular-sanitize.git#1.2.28
[INFO] bower angular-cookies#1.2.28    cached git://github.com/angular/bower-angular-cookies.git#1.2.28
[INFO] bower angular-cookies#1.2.28  validate 1.2.28 against git://github.com/angular/bower-angular-cookies.git#1.2.28
[INFO] bower angular-route#1.2.28      cached git://github.com/angular/bower-angular-route.git#1.2.28
[INFO] bower angular-route#1.2.28    validate 1.2.28 against git://github.com/angular/bower-angular-route.git#1.2.28
[INFO] bower angular-animate#1.2.28    cached git://github.com/angular/bower-angular-animate.git#1.2.28
[INFO] bower angular-animate#1.2.28  validate 1.2.28 against git://github.com/angular/bower-angular-animate.git#1.2.28
[INFO] bower ng-sortable#1.1.6         cached git://github.com/a5hik/ng-sortable.git#1.1.6
[INFO] bower ng-sortable#1.1.6       validate 1.1.6 against git://github.com/a5hik/ng-sortable.git#1.1.6
[INFO] bower angular-scenario#1.2.28   cached git://github.com/angular/bower-angular-scenario.git#1.2.28
[INFO] bower angular-scenario#1.2.28 validate 1.2.28 against git://github.com/angular/bower-angular-scenario.git#1.2.28
[INFO] bower angular-mocks#1.2.28      cached git://github.com/angular/bower-angular-mocks.git#1.2.28
[INFO] bower angular-mocks#1.2.28    validate 1.2.28 against git://github.com/angular/bower-angular-mocks.git#1.2.28
[INFO] bower angular-touch#1.2.28      cached git://github.com/angular/bower-angular-touch.git#1.2.28
[INFO] bower angular-touch#1.2.28    validate 1.2.28 against git://github.com/angular/bower-angular-touch.git#1.2.28
[INFO] bower angular#1.2.x             cached git://github.com/angular/bower-angular.git#1.2.28
[INFO] bower angular#1.2.x           validate 1.2.28 against git://github.com/angular/bower-angular.git#1.2.x
[INFO] bower angular#1.2.28            cached git://github.com/angular/bower-angular.git#1.2.28
[INFO] bower angular#1.2.28          validate 1.2.28 against git://github.com/angular/bower-angular.git#1.2.28
[INFO] bower angular#>=1               cached git://github.com/angular/bower-angular.git#1.4.1
[INFO] bower angular#>=1             validate 1.4.1 against git://github.com/angular/bower-angular.git#>=1
[INFO] bower angular#*                 cached git://github.com/angular/bower-angular.git#1.4.1
[INFO] bower angular#*               validate 1.4.1 against git://github.com/angular/bower-angular.git#*
[INFO] bower angular#>=1.0.6           cached git://github.com/angular/bower-angular.git#1.4.1
[INFO] bower angular#>=1.0.6         validate 1.4.1 against git://github.com/angular/bower-angular.git#>=1.0.6
[INFO] bower angular#~1.x              cached git://github.com/angular/bower-angular.git#1.4.1
[INFO] bower angular#~1.x            validate 1.4.1 against git://github.com/angular/bower-angular.git#~1.x
[INFO] bower angular#1.3.x             cached git://github.com/angular/bower-angular.git#1.3.16
[INFO] bower angular#1.3.x           validate 1.3.16 against git://github.com/angular/bower-angular.git#1.3.x
[ERROR] bower                        ECONFLICT Unable to find suitable version for angular
```

Therefore, a lot of users will report building failure into the mailing list and JIRA.
That's what we went through last time we changed angular version.
Any idea of avoiding it?

**Comment by bzz** [comment]
May be removing bower_components on mvn clean of the web submodule will help?

**Comment by Leemoonsoo** [comment]
@bzz I think that would help.

**Comment by bzz** [comment]
Please see if that helps

**Comment by minahlee** [comment]
I rebased master branch and made a small change.
When I created this PR, there was no angular-bootstrap version supporting angular 1.3.x so I had to downgrade angular version to 1.2.x to bring tooltip feature back.
Meanwhile new angular-bootstrap has released which supports angular 1.3.x, so I bumped only angular-bootstrap version.

@cdfhuang @Leemoonsoo Can you review this please?

**Comment by Leemoonsoo** [comment]
Tested and looks good to me.

**Pull request closed without merging**
