### PR TITLE
Hot fix grunt failure

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
This is a fix for grunt failure due to jshint warnings

Grunt error:
`src/app/notebook/paragraph/paragraph.controller.js
  line 117   col 80  Strings must use singlequote.
  line 2122  col 83  Expected '!==' and instead saw '!='.`

### What type of PR is it?
Hot Fix

### What is the Jira issue?
no

### How should this be tested?
`cd zeppelin-web` and run `grunt` should build without any error/warning

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Thanks for the fix, and making grunt run again.
LGTM.

**Comment by corneadoug** [comment]
This issue made me see a bug in the grunt file. (Since build is not failing)
Could you fix it at the same time?

In Gruntfile.js: (Around [those lines](https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-web/Gruntfile.js#L451))
* The default task content should be: `'build', 'test'`
* The `'newer:jshint'` that is currently in the default, should be move to the first line of the build task

**Comment by r-kamath** [comment]
@corneadoug good find. fixed in 23638b6. thanks

**Comment by corneadoug** [comment]
LGTM, I'm trying to figure out why the CI is failing

**Comment by r-kamath** [comment]
looks like the failure is not related to this change

31m*** 1 TEST FAILED ***[0m
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [01:50 min]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 37.746 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [ 17.118 s]
[INFO] Zeppelin: Display system apis ...................... FAILURE [ 29.541 s]
[INFO] Zeppelin: Spark dependencies ....................... SKIPPED
[INFO] Zeppelin: Spark .................................... SKIPPED

**Comment by felixcheung** [comment]
earlier test failure was:
```
[31m- should provide onclick method *** FAILED ***[0m
[31m  The code passed to eventually never returned normally. Attempted 1 times over 670.613569 milliseconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:72)[0m
```

**Comment by corneadoug** [comment]
@r-kamath Could you re-trigger the CI to be sure?

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by felixcheung** [comment]
right, CI passed clean as of the last run from yesterday.

**Pull request closed without merging**
