### PR TITLE
Fix styles of documentation about interpreters

### PR DESCRIPTION
**Pull request by yoonjs2**
Due to the documentation of interpreters written by various authors, styles of documentations are vary and has broken tags and inconsistent spaces. This fix cleans those little glitches to make documentation more readable and look cleaner to users.

1) Clean up unnecessary or wrong HTML tags ex: \<hr/\> after titles
2) Fix too wide spaces between paragraph and tables
3) Remove unnecessary spaces at end of paragraph and lines

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @yoonjs2 for the good contribution.
Just merged another documentation improvement  #578 from @AhyoungRyu. That seems make this branch conflict to master. Do you mind resolve the conflict once again?

**Comment by yoonjs2** [comment]
Hi @Leemoonsoo, I just merged my branch with #578.
And also I fixed & matched more unnecessary spaces and indention in every interpreter documentations to make them more looks like written by one author. But while I merging documentations I found contents and numbering of titles are also varies between documents. 

* Some documents has overview but some are not.
* Some documents use numbering at titles but some are not.
* Some documents has spaces between titles and paragraph but some are not.
* Some documents use \<br/\> tags to make line spaces but some are not.

So It may need to build some standard guidelines in documentation styles to give ground rules for users to start documentation on their proposing features. If that guidelines goes well with the community, It will be easy to add nice design and document format in the future. (like http://getbootstrap.com or other OSS projects)

Any suggestions?

**Comment by AhyoungRyu** [comment]
@yoonjs2 
It's really good idea to make a standard guideline. I always think that we need it!

**Comment by Leemoonsoo** [comment]
The change looks good to me. Merge if there're no more discussions.
And big +1 for guidelines for documentation style.

**Comment by felixcheung** [comment]
looks good

**Pull request closed without merging**
