### PR TITLE
Distribution Management

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
To manage distribution of the artifact and supporting files generated throughout the build process

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Could you explain little bit more what this trying to change?

**Comment by prabhjyotsingh** [comment]
This is a generic configuration to be be picked maven-deploy-plugin for "mvn deploy" task. 

https://maven.apache.org/pom.html#Distribution_Management

If i'm trying to setup up my own private nexus, and say use command "mvn deploy -Phadoop-2.3 -Ppyspark -B" it tries to upload the dependencies to "https://repository.apache.org/service/local/staging/deploy/maven2", but if I use "distributionManagement" in pom.xml and run following. 

    mvn deploy -Phadoop-2.3 -Ppyspark -B -Drepoid="IN-QA" -Dreponame="centos6" -Drepourl="http://nexus-private.my-domain.com/nexus/content/repositories/IN-QA/"

the above command will upload the dependencies to http://nexus-private.my-domain.com/nexus/content/repositories/IN-QA/

**Comment by Leemoonsoo** [comment]
Thanks for explanation. Looks good to me.

**Comment by jongyoul** [comment]
Nice description. LGTM.

**Comment by jongyoul** [comment]
Merging if there is no more discussion

**Pull request closed without merging**
