### PR TITLE
ZEPPELIN-223 fix: reconection in case of disconnection.

### PR DESCRIPTION
**Pull request by prabhjyotsingh**

### CODE REVIEW

**Comment by djoelz** [comment]
This will get rid of an unnecessary browser refresh for stale sessions. +1

**Comment by Leemoonsoo** [comment]
Thanks @prabhjyotsingh for fix.

I've tested this branch and i can see reconnection is working.
Once reconnected, however, any command is not working but raising exceptions such as 
```
6:09:06,063 ERROR org.apache.zeppelin.socket.NotebookServer:141 - Can't handle message
java.lang.NullPointerException
	at org.apache.zeppelin.socket.NotebookServer.updateParagraph(NotebookServer.java:373)
	at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:107)
	at org.apache.zeppelin.socket.NotebookSocket.onMessage(NotebookSocket.java:56)
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameHandler.onFrame(WebSocketConnectionRFC6455.java:835)
	at org.eclipse.jetty.websocket.WebSocketParserRFC6455.parseNext(WebSocketParserRFC6455.java:349)
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455.handle(WebSocketConnectionRFC6455.java:225)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```
Therefore, user can not be benefit by re-connected websocket.

It is because of NotebookServer searches Note by websocket connection in [NoteSocketMap](https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java#L59).
To creates information into NoteSocketMap, client need to send [GET_NOTE](https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java#L113) message, once it is reconnected.

**Comment by prabhjyotsingh** [comment]
@Leemoonsoo I missed out testing that scenario. This should do the job.

**Comment by Leemoonsoo** [comment]
Tested and Looks great! merging it!

**Comment by corneadoug** [comment]
@Leemoonsoo @prabhjyotsingh Since that issue, it takes around 10seconds to get the page content (while having a disconnected status) on each page refresh.

Furthermore, this PR doesn't have any description explaining what this is supposed to solve.
I'd like to hear about it, before I potentially revert that commit.

**Comment by prabhjyotsingh** [comment]
>Since that issue, it takes around 10seconds to get the page content (while having a disconnected status) on each page refresh.

It works for me, with or without refreshing the browser (tested on Firefox 39 and Chrome 44) 
https://drive.google.com/file/d/0B9mQvsdi5HQDbWtwVjBpbm80aU0/view
However, it take 10sec to reconnect if its status was disconnected, but if any operation is performed over web-socket before that, it will reconnect immediately.
Let me know steps to reproduce, so I can debug it further.


>Furthermore, this PR doesn't have any description explaining what this is supposed to solve.
I'd like to hear about it, before I potentially revert that commit.

This solves https://issues.apache.org/jira/browse/ZEPPELIN-223, i.e.;
Zeppelin UI page displays connection status (connected/disconnected) to the zeppelin server. When it gets to disconnected state, user has to copy the url and paste it in another window to get to connected state. From the existing window, it is not possible to reconnect to zeppelin server (by clicking on home page or any other link).

**Comment by corneadoug** [comment]
I have a totally different result after this PR: https://drive.google.com/file/d/0B1fr6-wITX3PNDdRU0h3MDB6NjQ/view

@Leemoonsoo could you tell me if you have the same result as me?

**Comment by corneadoug** [comment]
After doing a thorough git checkout on the commits, I tracked it to a different commit: https://github.com/apache/incubator-zeppelin/commit/d5ab911bf4419fa7c6f38945c6c8ad4946f8abf6
However I wonder why I am the only one with that problem :/

**Comment by prabhjyotsingh** [comment]
@corneadoug thanks from the find.

**Comment by djoelz** [comment]
I have a theory that the host name look up in IPv6 might be the issue. Can one of you try to set the mentioned flag?
http://www-01.ibm.com/support/docview.wss?uid=swg21170467

If so we can think of another way to get the host name.

**Pull request closed without merging**
