### PR TITLE
Update/shiro docs

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
Currently, Zeppelin has two authentication docs. One is  [**Authentication**](https://zeppelin.incubator.apache.org/docs/0.6.0-incubating-SNAPSHOT/security/authentication.html) and the other is [**Shiro Authentication**](https://zeppelin.incubator.apache.org/docs/0.6.0-incubating-SNAPSHOT/manual/shiroauthentication.html). As a user, it's little bit confused. So I changed the category of `shiroauthentication.md` file from `manual` to `security` and also changed the name of `Authentication` to `Authentication for NGINX`. Please see the below screenshot images :)

### What type of PR is it?
Improvement

### Todos
* [x] - Add `conf/shiro.ini` file to `.gitignore` 
* [x] - Update `zeppelin-login.png` screenshot image file in `shiroauthentication.md`
* [x] - Change the category of `shiroauthentication.md` file from `manual` -> `security`
* [x] - Change `Authentication` -> `Authentication for NGINX`  

### Screenshots (if appropriate)
1. Updating  zeppelin-login.png 
    - before
zeppelin-login 1

    - after
zeppelin-login

2. Changing the category of **Shiro Authentication** & Changing **Authentication** -> **Authentication for NGINX**
    - before
screen shot 2016-05-20 at 5 31 34 pm

 - after
screen shot 2016-05-20 at 5 31 19 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by vinayshukla** [comment]
@AhyoungRyu Thanks for this change. I am happy to see this doc improvement.

But I think we have an issue with authentication performed by upstream servers ( (e.g NGINX/Oracle HTTP Server, Apache WebServer,...)

In reviewing this pull request I looked at existing NGINX authentication doc and I can't find any instructions to propagate identity from NGINX to Zeppelin.

If we allow any upstream server to authenticate, the next step is to have the identity authenticated upstream to be propagated to Zeppelin and have Zeppelin use that identity for it's own access control decisions and Zeppelin should then send this identity downstream to submit jobs.

I am happy to file another JIRA to track this, please advise.

**Comment by prabhjyotsingh** [comment]
@AhyoungRyu big 👍 for taking this up.

**Comment by AhyoungRyu** [comment]
@vinayshukla Thanks for sharing your opinion! It's really important feedback to Zeppelin indeed. Many other people might need the instructions like you. So my point is it's good idea to file an issue for that :)

@prabhjyotsingh Thanks!

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by bzz** [comment]
Looks great to me. 
Thank you @AhyoungRyu for your efforts improving the documentation!

**Comment by cloverhearts** [comment]
LGTM!

**Comment by AhyoungRyu** [comment]
@vinayshukla I made an issue as you mentioned. Please check this out :  [ZEPPELIN-879](https://issues.apache.org/jira/browse/ZEPPELIN-879)

**Pull request closed without merging**
