### PR TITLE
ZEPPELIN-487 Change supporting multiple statements to multiple connections

### PR DESCRIPTION
**Pull request by jongyoul**
Changed multiple statements to multiple connection. Some JDBC don't support parallel executions with one connection.

### CODE REVIEW

**Comment by prasadwagle** [comment]
I tested the pull request and it allowed Vertica queries to execute in parallel with one modification. Thanks!

I had to comment:
//    if (statement.isClosed()) {
//      connection = getConnection(propertyKey);
//      statement = connection.createStatement();
//    }
since I ran into:
java.lang.AbstractMethodError: com.vertica.jdbc.VerticaStatementImpl.isClosed()Z
        at org.apache.zeppelin.hive.HiveInterpreter.getStatement(HiveInterpreter.java:208)

Can you help me understand the need for the statement.isClosed() check in line 208 since the statement is created in line 207?

**Comment by jongyoul** [comment]
It's soft of defensive code for avoiding error. Do you think it's redundant? I'll fix this code more general :-). Thanks for the review quickly.

**Comment by jongyoul** [comment]
@praagarw Could you please review this PR again?

**Comment by prasadwagle** [comment]
Hi Jongyoul, since createStatement is implemented in the JDBC drivers, I think it is unlikely it will return a closed statement. However, I am all for defensive coding and your fix in ZEPPELIN-487 looks good to me.

**Comment by jongyoul** [comment]
@praagarw Sure, but I couldn't guarantee all of jdbc connections create statement when it's alive. Thus double check might be helpful in that case. And thanks for kind review. I'm merging in three day.

**Comment by jongyoul** [comment]
Merging without additional discussion

**Pull request closed without merging**
