### PR TITLE
Keyboard Shortcut - Map Alt or Opt Based on Device

### PR DESCRIPTION
**Pull request by MikeTYChen**
### What is this PR for?
Right now the keyboard shortcut modal shows 'alt' but on macs 'alt' maps to 'opt'. Could be confusing to some people who don't see 'alt' on the keyboard on their macs.

There are many way to achieve this mapping. I used this to minimize code change and take advantage of when paragraphs check for appVersion to set keyboard shortcuts. 

Open to suggestions on best approach to solve this problem. 

### What type of PR is it?
Improvement

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-626
### How should this be tested?
1. Emulate browser to be Mac and open keyboard shortcut
2. Emulate browser to be Windows and open keyboard shortcut

### Screenshots (if appropriate)
Macs:
mac

Windows:
others

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
looks good I think - is it possible to use the fancy mac key like `⌥` `⌃`?
Seem like either we have `Option` or its short form is usually `⌥`

https://support.apple.com/en-us/HT201236

**Comment by MikeTYChen** [comment]
@felixcheung good suggestions. However, for consistency (since we don't have symbols for shift, ctrl, enter etc), I think Opt would be better than ⌥. What do you think?

**Comment by felixcheung** [comment]
There's in fact symbols for each of shift, ctrl and enter which are fairly commonly used on mac in apps.
But in any case, how about we put Option in full? It's just not common to see "Opt"

**Comment by corneadoug** [comment]
Maybe we could change:
Control in Note -> Note Shortcuts
Control in Note Editor -> Editor Shortcuts

What do you guys think?

**Comment by MikeTYChen** [comment]
@felixcheung : yeah. I know. I meant that in Zeppelin currently, we're not using any of the symbols, so to stay consistent with Zeppelin's current shortcuts, we should stay with Option. I updated the code to spell out option. 

@corneadoug : Thanks for suggestion. That's a good idea. I updated the title to reflect that change.

**Comment by felixcheung** [comment]
looks good, thanks!
merging if no more discussion.

**Pull request closed without merging**
