### PR TITLE
[ZEPPELIN-552] Shadow on focused paragraph in default looknfeel

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Add visual indication of focused paragraph by adding shadow in 'default' looknfeel.

### What type of PR is it?
Improvement

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-552

### How should this be tested?
focus paragraph by click editor or output of paragraph

### Screenshots (if appropriate)
focus_new

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I have added shadow on focused paragraph in 'default' looknfeel, just like 'simple' looknfeel does.
Any opinion and feedback on this change is very appreciated

**Comment by corneadoug** [comment]
Looks good, However when we focus by clicking on the output, shortcut are not working.

**Comment by prabhjyotsingh** [comment]
Tested, works well, LGTM.

**Comment by Leemoonsoo** [comment]
@corneadoug While this PR only adds shadow by editing css, if keyboard shortcut does not work, i think it must be different problem. Please create jira issue when you find problem on keyboard shortcut and let me handle it.

I'm merging this PR if adding shadow to focused paragraph looks fine and there're no more discussions.

**Comment by corneadoug** [comment]
LGTM

**Pull request closed without merging**
