### PR TITLE
Remove incubating from pom files

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Remove `incubating` term from pom files

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Comment by jongyoul** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by astroshim** [comment]
LGTM

**Comment by iemejia** [comment]
Just one curious question. 
When is the incubator- been removed from the github mirror ? So we can have github.com/apache/zeppelin ?

**Comment by cloverhearts** [comment]
LGTM

**Comment by felixcheung** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
