### PR TITLE
[ZEPPELIN-951] Update cron expression link and fix broken cron container style

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Update cron expression link and fix broken cron container style

### What type of PR is it?
Bug Fix

### What is the Jira issue?
ZEPPELIN-951

### Screenshots (if appropriate)
**Before**
screen shot 2016-06-03 at 7 01 00 pm

**After**
screen shot 2016-06-03 at 7 00 39 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by cloverhearts** [comment]
LGTM

**Comment by minahlee** [comment]
Same test failure is already reported by @bzz in https://issues.apache.org/jira/browse/ZEPPELIN-942

**Comment by astroshim** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Hi @minahlee,
This CI failure is fixed with #958. Can you rebase with master and re-trigger ?

**Comment by minahlee** [comment]
@prabhjyotsingh Test is passing now! Thanks for taking care of it

**Comment by prabhjyotsingh** [comment]
LGTM. Will Merge this if no more discussion.

**Pull request closed without merging**
