### PR TITLE
[Zeppelin 537] Improve behavior of reloading notebooks from storage

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Improve behavior of reloading notebooks from storage

### What type of PR is it?
Improvement

### Is there a relevant Jira issue?
[ZEPPELIN-537](https://issues.apache.org/jira/browse/ZEPPELIN-537?jql=project%20%3D%20ZEPPELIN)

### How should this be tested?
1. Add new `notebookId/note.json` under `ZEPPELIN_HOME/notebook`
2. Click reload button next to 'Notebook'
3. Check if the new added note is loaded

### Screenshots (if appropriate)
reload fig

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested and LGTM.

**Comment by minahlee** [comment]
@khalidhuseynov Keeping notebookRepo class for the flexibility makes perfect sense. I just addressed it please review

**Comment by khalidhuseynov** [comment]
Looks good to me!

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
LGTM, merge if there're no more discussions

**Pull request closed without merging**
