### PR TITLE
ZEPPELIN-441 Make SparkInterpreter work even if Spark version is not listed

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-441

Currently when spark version is not listed in SparkVersion.java, it throws 

```
java.lang.IllegalArgumentException
    at org.apache.zeppelin.spark.SparkVersion.fromVersionString(SparkVersion.java:58)
    at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:477)
```

This PR changes SparkVersion from 'enum' to 'class' and make Spark Interpreter work with unlisted version.

### CODE REVIEW

**Comment by felixcheung** [comment]
generally I think it's ok if it is minor/patch version [differences](http://semver.org/).
but for 1.5.x vs 1.6 or 1.x vs 2.0 - I am not sure we should automatically assume compatibility.

for instance there is a new version with py4j jar that I plan to address in https://issues.apache.org/jira/browse/ZEPPELIN-395

**Comment by Leemoonsoo** [comment]
That make sense.

Which do you prefer? When Spark is future version, we can either print some warning log or raise exception to not working with it.

**Comment by felixcheung** [comment]
If it's minor/patch version difference, maybe we could warn and continue?
I think it would be nice to have a message in the notebook output, if it's in the log file then it's not very discoverable.

**Comment by Leemoonsoo** [comment]
@felixcheung  I have updated code to allow minor/patch version difference, but print error message on the notebook when major version is unsupported.

**Comment by felixcheung** [comment]
looks good

**Comment by Leemoonsoo** [comment]
Test added. and version check in SparkSqlInterperter, SparkInterpreter, PySparkInterpreter.

Ready to merge.

**Comment by felixcheung** [comment]
looks good

**Pull request closed without merging**
