### PR TITLE
Add PR template for github

### PR DESCRIPTION
**Pull request by felixcheung**
### What is this PR for?
PR template can be added automatically by GitHub when a PR is opened.
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
Proposing some changes to PR template wordings.

### What type of PR is it?
Improvement

### Todos
* [x] - Add template

### Is there a relevant Jira issue?
N/A

### How should this be tested?
Open a new PR.

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by jongyoul** [comment]
Wow! LGTM

**Comment by AhyoungRyu** [comment]
Really cool! :+1:

**Comment by bzz** [comment]
Looks great to me!

**Comment by bzz** [comment]
CI failure is due to
```
Unapproved licenses:

  .github/PULL_REQUEST_TEMPLATE

*******************************
```
.. but you got it ;)

**Comment by felixcheung** [comment]
yea ;)

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by corneadoug** [comment]
Should we remove the PR template part from the Contributing.md then?

**Comment by felixcheung** [comment]
I think it's useful to have that in contributing.md so newcomers would have an idea what to expect before actually opening a new PR. We might want to leave out the bookmarklet tip though?

**Comment by corneadoug** [comment]
Then lets remove the bookmarklet and update the template in the contributing.md

**Pull request closed without merging**
