### PR TITLE
add new selenium test  case for move paragraph up and down

### PR DESCRIPTION
**Pull request by ravicodder**
### What is this PR for?
Add new  selenium test case for move paragraph up and down

### What type of PR is it?
Test 

### Is there a relevant Jira issue?
NA

### How should this be tested?
On OSX, you'll need firefox 42.0 installed, then you can run with
 
  PATH=~/Applications/Firefox.app/Contents/MacOS/:$PATH CI="" \
     mvn -Dtest=org.apache.zeppelin.ParagraphActionsIT -Denforcer.skip=true \
     test -pl zeppelin-server

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation?No

### CODE REVIEW

**Comment by ravicodder** [comment]
Job #2977.2 and #2977.4 are failing with non related issue details as follows:

Tests in error: 
  DepInterpreterTest.testDefault:96 Â» NullPointer

[INFO] Zeppelin: Spark .................................... FAILURE [01:33 min]


Ready for review.

**Comment by prabhjyotsingh** [comment]
CI is green. Tested on my FF44.
LGTM !

**Comment by Leemoonsoo** [comment]
Great! LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
