### PR TITLE
Remove duplicated java option concats in common.sh

### PR DESCRIPTION
**Pull request by zhongneu**
### What is this PR for?
There are some java option concats in common.sh, which are executed twice when start an interpreter. This makes some of the options invalid, such as remote debugging options

### What type of PR is it?
Bug Fix

### Is there a relevant Jira issue?
[ZEPPELIN-686](https://issues.apache.org/jira/browse/ZEPPELIN-686)

### How should this be tested?
Set remote debug options:
```
export ZEPPELIN_INTP_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n
```

Start the Zeppelin daemon, then create & run a job to trigger starting an interpreter. The job should fail without the fix.

### Questions:
* Does the licenses files need update?
NO

* Is there breaking changes for older versions?
NO

* Does this needs documentation?
NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @zhongneu for the patch.
Looks good to me.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discsussions

**Comment by felixcheung** [comment]
what if someone has set JAVA_OPTS in the env? shouldn't we be additive?

**Comment by zhongneu** [comment]
@felixcheung I am not sure about this, but I would like to make it additive if we have such case.

**Comment by Leemoonsoo** [comment]
I think @felixcheung got valid point. It's incompatible change to people who has JAVA_OPTS.
One alternative is document changes in 
https://github.com/apache/incubator-zeppelin/blob/master/docs/install/upgrade.md

**Comment by felixcheung** [comment]
That sounds like a reasonable approach, we could say something like
"if you are setting JAVA_OPT, set ZEPPELIN_JAVA_OPTS instead for Zeppelin, set ZEPPELIN_INTP_JAVA_OPTS instead for interpreter process" in more words ;)

**Comment by zhongneu** [comment]
I've reverted the change for JAVA_OPTS, which is fine, because it is not used by bin/interpreter.sh

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by felixcheung** [comment]
looks good. I think we might want to deprecate JAVA_INTP_OPTS and replace with something more Zeppelin specific for clarify, and allow for admin to override it.
merging if no more comment.

**Pull request closed without merging**
