### PR TITLE
Move Spark specific things from pom.xml to spark/pom.xml

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Move Spark specific dependencyManagement and properties from pom.xml to spark/pom.xml.
Which interfere other interpreter's dependency version.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I have moved spark related dependency configuration from pom.xml -> spark/pom.xml
I've verified local mode works fine. I'm going to verify with spark cluster, too.
This PR will help #75 that test is failing because of version of dependency library.

**Comment by Leemoonsoo** [comment]
This PR is ready to merge. Here's summary of changes.

##### Move spark specific dependency configuration from pom.xml -> spark/pom.xml

Because of spark specific dependency configuration were inside of common parent pom.xml, all other interpreter were influenced by this. Flink is one of example that conflict dependency library version with the version spark uses. This PR moves spark specific configuration from pom.xml to spark/pom.xml

##### Removal of huge dependencyManagement block

dependencyManagement block introduced to pom.xml for resolving dependency conflict between Zeppelin and Spark. However, since Zeppelin changed to run interpreter as separate process, we don't have massive dependency conflict. So most dependency management blocks are just removed.

##### Automated test against standalone spark cluster.
   Incompatible version of dependency can raise error especially when spark runs against spark cluster. While this PR brings big changes to dependency, i've made our CI (travis) test against spark standalone cluster.
##### Automated test multiple profile spark-1.3, spark-1.2, spark-1.1

**Comment by Leemoonsoo** [comment]
Merging if there're not more discussions.

**Comment by corneadoug** [comment]
+1

**Pull request closed without merging**
