### PR TITLE
ZEPPELIN-188 Display of line numbers

### PR DESCRIPTION
**Pull request by r-kamath**
Partial check-in with reference to : ZEPPELIN-188.
- Add an option under the paragraph settings to show/hide line numbers in ace editor

Since Ace editor is already integrated, with minor changes, this patch will get us line numbers. Based on comments, would like to work on improving - syntax highlighting & auto-complete. 

Thanks!

### CODE REVIEW

**Comment by felixcheung** [comment]
is there a way to have this a sticky setting persisted across sections?
is this settable from the interpreter tab?

**Comment by r-kamath** [comment]
> is there a way to have this a sticky setting persisted across sections?

In 19aecb2 show/hide line number action is in the paragraph settings and is persisted only in the instance where it's turned on.

> is this settable from the interpreter tab?

We can have a new option in the Notebook settings to invoke show/hide action for all paragraphs.
notebook-actions

**Comment by corneadoug** [comment]
Current action bar is pretty full right now (and hard to understand)
The less actions buttons, the better

**Comment by Leemoonsoo** [comment]
This is screenshot comes from this branch
image

**Comment by Leemoonsoo** [comment]
It looks good to me. It enables display line numbers while it does not change any default behavior.  We can still discuss about action button in separate issue.

If there're no more discussions, i'm merging it.

**Comment by eranwitkon** [comment]
Just found out that when we turn on line number or turn of line numbers it always reset the paragraph title.
selection_014

Now, after adding the line numbers:
selection_015

**Comment by eranwitkon** [comment]
The problem above is due to the ```commitParagraph``` call within ```$scope.showLineNumbers``` and ```$scope.hideLineNumbers```

**Pull request closed without merging**
