### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by cyhsutw**
### What is this PR for?

1. Fix some typos in docs.
2. Remove trailing white spaces for each line.
3. Remove leading white spaces if a line contains no content.
4. Add trailing new line for each file.

### What type of PR is it?
Improvement | Documentation

### Todos
None

### What is the Jira issue?
N/A

### How should this be tested?
Build the doc site and check.

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? *no*
* Is there breaking changes for older versions? *no*
* Does this needs documentation? *no*

### CODE REVIEW

**Comment by jongyoul** [comment]
LGTM

**Comment by felixcheung** [comment]
thanks for fixing all of those!

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
Looks good!

**Pull request closed without merging**
