### PR TITLE
Update external links to project code style guides

### PR DESCRIPTION
**Pull request by bzz**
### What is this PR for?
Update external links to project code style guides in CONTRIBUTING.md as old ones give 404 now

### What type of PR is it?
Bug Fix

### How should this be tested?
Lins should be clickable and return 200

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
Ready to be merged.

CI failure is un-related and is tracked under [ZEPPELIN-862](https://issues.apache.org/jira/browse/ZEPPELIN-862)

```
05:13:41,508  INFO org.apache.zeppelin.notebook.Paragraph:241 - run paragraph 20160606-051341_688938155 using pyspark org.apache.zeppelin.interpreter.LazyOpenInterpreter@2b5b1f5f

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by lresende** [comment]
As we have some scala code, do we also want to update with scala style guide (http://docs.scala-lang.org/style/) ?

**Comment by bzz** [comment]
That is a great suggesting, @lresende ! There already were discussions about if I recall.

Let's do so in separate PR though, so we could narrow the scope of discussion there.

**Pull request closed without merging**
