### PR TITLE
ZEPPELIN-141: Show only the Interpreters suggestions. Move the 'local…

### PR DESCRIPTION
**Pull request by tzolov**
…' suggestions to the bottom of the list

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tried this branch. but can not see completion list popup in my browser (chrome) when i press `ctrl-.`

**Comment by tzolov** [comment]
@Leemoonsoo thanks for reviewing this. Not seeing the completions for the current Spark completion implementation was expected (due to [ZEPPELIN-204](https://issues.apache.org/jira/browse/ZEPPELIN-204) ). My solution though was far too restrictive because it use to exclude the default ACE completers leaving in only the Interpreter completers. Although this seemed to work for my PSQL and OQL completers (not committed yet) it was affecting all other interpreters that have not implemented completers. 
So i added few improvements that hopefully solve the problem with less drawbacks. Here are the additions: 

1. I've (re)included the default ACE completers: `keyWordCompleter`, `snippetCompleter`, `textCompleter`. But i've inserted them after the interpreter completer. That means that the interpreter completions (if provided) will be shown before the Keyword and Local completions (note that the snippet completion is disabled).
2. The main issue of showing Spark completion results in the SQL paragraphs was due to the incorrectly set paragraph Mode. The old paragraph.controller.js implementation use to set the mode one - during paragraph's initialization and never changed it. Even if the interpreter marker was changed from %spark to %sql the mode would remain Spark and the completion will show the Spark keywords. Furthermore the insertion of new paragraph is initialized with the default (spark) mode and the only way to update it is to update the page (F5). 
To resolve this i've factored out the mode setting functionality into a separate function: `setParagraphMode`. Now this function is called in two places. Once during the initialization (as it use to be) but now it is called also on (Ctrl+.) attempt.  In this way the editor mode will be corrected before the completion request. The correct mode will be set and in turn the correct completer will be called. 
3. I've fixed a nasty CSS bug in ACE that was hiding the selected item in the completion popup menu.  

Above improvements are committed and waiting to be reviewed :)

**Comment by Leemoonsoo** [comment]
@tzolov Thanks for the update and good explanation.
Looks good to me!

**Comment by felixcheung** [comment]
For 2, instead of getCompletions, should we call setParagraphMode when the editor is dirty?

**Comment by felixcheung** [comment]
This way I think the problem with https://issues.apache.org/jira/browse/ZEPPELIN-188 will be fixed.

**Comment by felixcheung** [comment]
I think we need to make that extensible from the interpreters, that way it could support other modes like Python.
Maybe a follow up PR.

**Comment by tzolov** [comment]
@felixcheung, thanks for the suggestion. i've thought of ZEPPELIN-188 as well. Indeed the dirty page event is a good trigger but i am worried of the performance impact. Perhaps it is neglectable, also we can improve the set logic to SET-ONLY-IF-DIFFERENT. 

But let us first merge the current fix. This will resolve ZEPPELIN-141 and fix the broken autocompletion. Then we can generalize the solution (the way you have suggested) in the context of ZEPPELIN-188. What do you think?

I agree about the extensible interpreters. IMHO this will require extending the Interpreter interface, may be extend the websocket protocol with an additional command and figuring out how to enable the ACE  features in the front-end. For example now only few ACE modes are defined in the bower.json. If you need more (like SH or PYTHON for example) one have to add them to bower.json and re-build. Maybe we can (pre)enable large set of the ACE modes upfront. 
Anyway i think this work deserves its one JIRA ticket (e.g. this would be the 3rd step)?

**Comment by felixcheung** [comment]
Agreed, 2 follow up PR/JIRAs

**Comment by felixcheung** [comment]
FYI: created https://issues.apache.org/jira/browse/ZEPPELIN-214

**Comment by tzolov** [comment]
thanks @felixcheung

**Pull request closed without merging**
