### PR TITLE
ZEPPELIN-545.  Include Ignite 1.5.0.final into next release of Zeppelin

### PR DESCRIPTION
**Pull request by c0s**
Ready for the review. The latest Ignite release will be published in the next day or so

### CODE REVIEW

**Comment by jongyoul** [comment]
@c0s There is not 1.5.0.final in a maven repository and I've found 1.5.0-b1 only. Would it be resolved?

**Comment by c0s** [comment]
That's what I've said - the bits will be available in a day or two once the vote is over. Don't pull this one in yet. I have validated it to work just in my local setup for now. Thanks!

**Comment by jongyoul** [comment]
@c0s Okay. Thanks for quick fix.

**Comment by c0s** [comment]
The 1.5.0.final release has been published and this PR should be able to clear the CI. Thanks!

**Comment by bzz** [comment]
So cool! 
@c0s AFAIK the simplest way to re-trigger the CI would be to close and re-open the PR by the author

**Comment by c0s** [comment]
Re-opening to trigger the CI

**Comment by bzz** [comment]
Looking though [CI logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/100251649/log.txt) it looks like one test is failing 

```
SEVERE: Got exception while starting (will rollback startup routine).
class org.apache.ignite.IgniteCheckedException: Failed to start manager: GridManagerAdapter [enabled=true, name=org.apache.ignite.internal.managers.discovery.GridDiscoveryManager]
	at org.apache.ignite.internal.IgniteKernal.startManager(IgniteKernal.java:1510)
	at org.apache.ignite.internal.IgniteKernal.start(IgniteKernal.java:917)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start0(IgnitionEx.java:1688)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start(IgnitionEx.java:1547)
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1003)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:534)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:515)
	at org.apache.ignite.Ignition.start(Ignition.java:322)
	at org.apache.ignite.internal.jdbc2.JdbcConnection.getIgnite(JdbcConnection.java:172)
	at org.apache.ignite.internal.jdbc2.JdbcConnection.<init>(JdbcConnection.java:141)
	at org.apache.ignite.IgniteJdbcDriver.connect(IgniteJdbcDriver.java:350)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at org.apache.zeppelin.ignite.IgniteSqlInterpreter.open(IgniteSqlInterpreter.java:95)
	at org.apache.zeppelin.ignite.IgniteSqlInterpreterTest.setUp(IgniteSqlInterpreterTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: class org.apache.ignite.IgniteCheckedException: Failed to start SPI: TcpDiscoverySpi [addrRslvr=null, sockTimeout=5000, ackTimeout=5000, reconCnt=10, maxAckTimeout=600000, forceSrvMode=false, clientReconnectDisabled=false]
	at org.apache.ignite.internal.managers.GridManagerAdapter.startSpi(GridManagerAdapter.java:258)
	at org.apache.ignite.internal.managers.discovery.GridDiscoveryManager.start(GridDiscoveryManager.java:660)
	at org.apache.ignite.internal.IgniteKernal.startManager(IgniteKernal.java:1505)
	... 38 more
Caused by: class org.apache.ignite.spi.IgniteSpiException: Local node's marshaller differs from remote node's marshaller (to make sure all nodes in topology have identical marshaller, configure marshaller explicitly in configuration) [locMarshaller=org.apache.ignite.marshaller.optimized.OptimizedMarshaller, rmtMarshaller=org.apache.ignite.internal.binary.BinaryMarshaller, locNodeAddrs=[testing-worker-linux-docker-a1225458-3234-linux-7.prod.travis-ci.org/0:0:0:0:0:0:0:1%1, /127.0.0.1, /172.17.12.239], locPort=0, rmtNodeAddr=[testing-worker-linux-docker-a1225458-3234-linux-7.prod.travis-ci.org/0:0:0:0:0:0:0:1%1, /127.0.0.1, /172.17.12.239], locNodeId=8fa598a2-9986-4f29-ba8d-8f857048e227, rmtNodeId=3aa33408-afea-48c7-941c-8ea87429f44d]
	at org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi.checkFailedError(TcpDiscoverySpi.java:1647)
	at org.apache.ignite.spi.discovery.tcp.ClientImpl$MessageWorker.body(ClientImpl.java:1460)
	at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)

[00:59:41] Ignite node stopped OK [name=ignite-jdbc-driver-a26bd4ee-2b36-4d62-9502-9d42c05062f3, uptime=00:00:01:281]
[00:59:41] Ignite node stopped OK [name=test, uptime=00:00:01:403]
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.749 sec <<< FAILURE! - in org.apache.zeppelin.ignite.IgniteSqlInterpreterTest
testSql(org.apache.zeppelin.ignite.IgniteSqlInterpreterTest)  Time elapsed: 2.133 sec  <<< FAILURE!
java.lang.AssertionError: expected:<SUCCESS> but was:<ERROR>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.apache.zeppelin.ignite.IgniteSqlInterpreterTest.testSql(IgniteSqlInterpreterTest.java:94)


Results :

Failed tests: 
  IgniteSqlInterpreterTest.testSql:94 expected:<SUCCESS> but was:<ERROR>

Tests run: 4, Failures: 1, Errors: 0, Skipped: 0

[INFO] Zeppelin: Apache Ignite interpreter ................ FAILURE [ 14.645 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by c0s** [comment]
Looks like it is cause by a missing configuration piece...
```Caused by: class org.apache.ignite.spi.IgniteSpiException: Local node's marshaller differs from remote node's marshaller (to make sure all nodes in topology have identical marshaller, configure marshaller explicitly in configuration) [locMarshaller=org.apache.ignite.marshaller.optimized.OptimizedMarshaller, rmtMarshaller=org.apache.ignite.internal.binary.BinaryMarshaller, locNodeAddrs=[testing-worker-linux-docker-a1225458-3234-linux-7.prod.travis-ci.org/0:0:0:0:0:0:0:1%1, /127.0.0.1, /172.17.12.239], locPort=0, rmtNodeAddr=[testing-worker-linux-docker-a1225458-3234-linux-7.prod.travis-ci.org/0:0:0:0:0:0:0:1%1, /127.0.0.1, /172.17.12.239], locNodeId=8fa598a2-9986-4f29-ba8d-8f857048e227, rmtNodeId=3aa33408-afea-48c7-941c-8ea87429f44d]```
Is there any way for me to run *only* ignite tests locally? Thanks!

**Comment by Leemoonsoo** [comment]
Command such as ```mvn package -pl 'zeppelin-interpreter,ignite'``` will run ignite (and zeppelin-interpreter module) only.

**Comment by c0s** [comment]
Looks like CI didn't pick up correct commit. Restarting once again.

**Comment by c0s** [comment]
Looks like it is good to go. There might be a bigger issue with different default marshallers for different node modes, which I am discussing on dev@ignite right now.

**Comment by Leemoonsoo** [comment]
Looks good to me

**Comment by bzz** [comment]
Looks good to me, thank you for taking care!
Will merging if there is no further discussion.

**Pull request closed without merging**
