### PR TITLE
Create a release tool

### PR DESCRIPTION
**Pull request by Leemoonsoo**
It'll be nice Zeppelin projects has tool that helps making releases. https://issues.apache.org/jira/browse/ZEPPELIN-130

* [x] Ability to create a source release. 
* [x] Ability to create binary releases.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Here's example usage and output
```
GPG_PASSPHRASE=[MYGPGPASS] dev/create_release.sh 0.5.0-incubating branch-0.5
```
generates packages under /tmp/incubator-zeppelin-release/
```
zeppelin-0.5.0-incubating-bin-spark-1.3.1_hadoop-2.3.tgz
zeppelin-0.5.0-incubating-bin-spark-1.3.1_hadoop-2.3.tgz.asc
zeppelin-0.5.0-incubating-bin-spark-1.3.1_hadoop-2.3.tgz.md5
zeppelin-0.5.0-incubating-bin-spark-1.3.1_hadoop-2.3.tgz.sha
zeppelin-0.5.0-incubating-bin-spark-1.4.0_hadoop-2.3.tgz
zeppelin-0.5.0-incubating-bin-spark-1.4.0_hadoop-2.3.tgz.asc
zeppelin-0.5.0-incubating-bin-spark-1.4.0_hadoop-2.3.tgz.md5
zeppelin-0.5.0-incubating-bin-spark-1.4.0_hadoop-2.3.tgz.sha
zeppelin-0.5.0-incubating.tgz
zeppelin-0.5.0-incubating.tgz.asc
zeppelin-0.5.0-incubating.tgz.md5
zeppelin-0.5.0-incubating.tgz.sha
```

**Comment by hsaputra** [comment]
+1

LGTM

**Comment by Leemoonsoo** [comment]
@hsaputra Thanks for review.

Currently this tool generates binary package that compiled with
 - spark-1.4.0 and hadoop-2.3
 - spark-1.3.1 and hadoop-2.3
If release includes pre-built binary, i think it's better to have  more spark/hadoop version combination.
But It's not really good idea to create every possible combination. So, the question is, which combination should be added in the release tool?

**Comment by hsaputra** [comment]
HI @Leemoonsoo, I think we could add more combo later. For now we need to have next release under Apache soon and first support with spark-1.3.1 and hadoop-2.3 should be good start.
Otherwise people could just grab source and build it.

Just my 2-cents

**Comment by Leemoonsoo** [comment]
Thanks @hsaputra. for the opinion. Yes, we can add more combo later.
Then, I'm merging it

**Pull request closed without merging**
