### PR TITLE
untracked files configuration.

### PR DESCRIPTION
**Pull request by astroshim**
To fix https://issues.apache.org/jira/browse/ZEPPELIN-258.

### CODE REVIEW

**Comment by bzz** [comment]
Good catch, thank you, looks good to me!

**Comment by Leemoonsoo** [comment]
CI Failure is unrelated. LGTM!

**Comment by bzz** [comment]
Any reason to close without merging? Also, I guess the history have been re-wrintte as the reviewed code have disappeared from this PR

https://issues.apache.org/jira/browse/ZEPPELIN-258 is stil open

**Comment by astroshim** [comment]
Not merged yet.:)

**Comment by Leemoonsoo** [comment]
LGTM, i'm merging it if there're no more discussions

**Pull request closed without merging**
