### PR TITLE
Get travis to retry download of Spark release

### PR DESCRIPTION
**Pull request by felixcheung**
### What is this PR for?
Refactor download and use travis' builtin mechanism to retry on failure - hopefully it will then hit a different apache mirror; this should mitigate the intermitted download failures that result in test failures

### What type of PR is it?
Improvement

### Todos
* [x] - Separate download script
* [x] - Travis to retry download step
* [x] - Add timeout to kill download if not complete in 5 min (need to tune this)
* [x] - Add timer to log how long download takes

### Is there a relevant Jira issue?
N/A

### How should this be tested?
Travis

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by felixcheung** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/110306654/log.txt
it retried 3 times - 2x timeout after 5 min, 1x partial/corrupted download.

**Comment by Leemoonsoo** [comment]
Change looks good to me!

**Comment by felixcheung** [comment]
It passed.  I'm going trigger CI a few more times.

**Comment by felixcheung** [comment]
Everything still passing, download time has been super fast (like 4 sec) I will hold and retry on Monday during the day.

**Comment by prabhjyotsingh** [comment]
:+1:

**Comment by felixcheung** [comment]
more download errors:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/110955308/log.txt

I suspect we should travis_retry build as well - they could fail with network/download errors? eg. https://s3.amazonaws.com/archive.travis-ci.org/jobs/111070007/log.txt

**Comment by felixcheung** [comment]
Merging this then since it seems to help..

**Comment by felixcheung** [comment]
Maybe pre-caching is the only way to make this more stable.. I have seen more than a few times download fails even after 3 tries either from timing out or partial/corrupted file

```
+tar zxf spark-1.4.1-bin-hadoop2.3.tgz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

[31;1mThe command "./testing/downloadSpark.sh 1.4.1 2.3" failed 3 times.[0m
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/111662284/log.txt

**Pull request closed without merging**
