### PR TITLE
ZEPPELIN-31 fix REST API base path in web-app

### PR DESCRIPTION
**Pull request by bzz**
Fixes https://issues.apache.org/jira/browse/ZEPPELIN-31

### CODE REVIEW

**Comment by bzz** [comment]
Ready to merge

**Comment by Leemoonsoo** [comment]
When i go to interpreter menu.

REST api call address was 
http://localhost:8080/api/interpreter

but changed to 
http://localhost:8080//api/interpreter

and getting 404

**Comment by bzz** [comment]
@Leemoonsoo should be good now

**Comment by bzz** [comment]
Triggering CI

**Comment by bzz** [comment]
Ready to merge

**Comment by bzz** [comment]
\\cc @corneadoug @anthonycorbacho for review

**Comment by corneadoug** [comment]
+1

**Comment by anthonycorbacho** [comment]
+1 as well

**Comment by Leemoonsoo** [comment]
Tested. +1

**Comment by bzz** [comment]
Thanks, merging then!

**Pull request closed without merging**
