### PR TITLE
ZEPPELIN-372 : Exporting a notebook

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
Exporting a notebook in a JSON format, which can later be used/imported in a different environment.

screen shot 2015-10-29 at 12 29 41 pm

### CODE REVIEW

**Comment by felixcheung** [comment]
should we have a test for export/import round tripping?

**Comment by prabhjyotsingh** [comment]
Yes, I intend to write a selenium test case, once both are merged.

**Comment by Leemoonsoo** [comment]
Tested and working well. Could you rebase and trigger CI?

**Comment by corneadoug** [comment]
This was a merge, not a rebase

**Comment by Leemoonsoo** [comment]
Thanks for really useful feature.
Merge if there're no more discussions

**Comment by corneadoug** [comment]
Too bad it doesn't work on Firefox and Safari

**Comment by prabhjyotsingh** [comment]
@corneadoug thank you for finding this issue, have made another pr https://github.com/apache/incubator-zeppelin/pull/408 with the fix.

**Comment by bpirvu** [comment]
Is there any documentation for this feature? I wasn't able to find it...

**Comment by felixcheung** [comment]
@bpirvu - it's probably best if you email the dev list (https://zeppelin.incubator.apache.org/community.html) for questions like this in the future - PR once it is closed might not be monitored.

**Pull request closed without merging**
