### PR TITLE
[ZEPPELIN-13] ZEPPELIN_CONF_DIR cannot be reached until ZEPPELIN_CONF_DIR become set

### PR DESCRIPTION
**Pull request by jongyoul**
bin/common.sh tries to find and set ZEPPELIN_CONF_DIR in order to read zeppelin-env.sh, but ZEPPELIN_CONF_DIR is defined in zeppelin-env.sh, so we cannot use different ZEPPELIN_CONF_DIR.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Looks good to me!

**Comment by anthonycorbacho** [comment]
this doesnt look good to me... convention is not followed

https://github.com/apache/incubator-zeppelin/blob/master/CONTRIBUTING.md#code-convention ... i spend a lot of time to set a coding convention;;;;

**Comment by jongyoul** [comment]
@anthonycorbacho I've read that guide, too. This is about Java and Scala coding style. Could you please which is not following convention? I also think consistency is very important.

**Comment by anthonycorbacho** [comment]
This part
* [Shell style](https://google-styleguide.googlecode.com/svn/trunk/shell.xml)

i.e:
```
if [ "$1" == "--config" ]
then
...

sould be

if [[ "$1" == "--config" ]]; then
...
```

**Comment by jongyoul** [comment]
@anthonycorbacho Oops. I missed this. I read "Shell" as "Scala" :-). I'm about to make a hotfix now.

**Pull request closed without merging**
