### PR TITLE
added autocompletion

### PR DESCRIPTION
**Pull request by xhudik**
auto-completion shortcut was missing

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
merge if there're no more discussions

**Comment by xhudik** [comment]
one question:
is there any other shortcut? I'm wondering whether there is nothing for cell manipulation (inserting, moving up and down,...) - such procedures are quite common so shortcuts would be handy ...

**Comment by Leemoonsoo** [comment]
No shortcuts yet. There are [one really old attempt](https://github.com/NFLabs/zeppelin/pull/229) for shortcuts. Definitely keyboard shortcuts will help a lot.

**Comment by xhudik** [comment]
right, so it requires additional work :(. In this case, this pull request should be ok for now

**Comment by felixcheung** [comment]
LGTM

**Comment by felixcheung** [comment]
Do we have a JIRA for the additional work? If not, @xhudik could you create one?

**Comment by xhudik** [comment]
@felixcheung  - i don't have too much time, but I'll try to find some and create it within 2-3 days

**Comment by xhudik** [comment]
@felixcheung  -  I created one general issue/feature improvement request: https://issues.apache.org/jira/browse/ZEPPELIN-391 - let's discuss there

**Pull request closed without merging**
