### PR TITLE
ZEPPELIN-361 Move licese of subcomponents from NOTICE to LICENSE

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Move license of subcomponents from NOTICE to LICENSE
https://issues.apache.org/jira/browse/ZEPPELIN-361

### CODE REVIEW

**Comment by felixcheung** [comment]
Spark does it by referring to copies under a license directory. Should that be done here?
https://github.com/apache/spark/tree/master/licenses

**Comment by Leemoonsoo** [comment]
I believe it depends on the condition of the license. (if it requires include copies of license).
I think we can either append them into LICENSE file or have a copy in the separate file.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions.

**Comment by anthonycorbacho** [comment]
LGTM!

**Comment by bzz** [comment]
Looks great to me

**Pull request closed without merging**
