### PR TITLE
Allow instance profile authentication with S3

### PR DESCRIPTION
**Pull request by cdfhuang**
This PR generalizes authentication with S3 access (for storing notebooks) a bit. Before the only way to authenticate was to set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables. This change uses DefaultAWSCredentialsProviderChain for authentication, which allows instance profiles on EC2 instances for authentication with S3.

### CODE REVIEW

**Comment by felixcheung** [comment]
shouldn't we keep the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment approach as well?

**Comment by cdfhuang** [comment]
Yup, we should, and the default provider chain takes care of that. The [documentation](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) for the default provider chain mentions that it'll look at four different places in a pre-defined order for credentials. The first place is the environment variables. It will then fall back to Java properties, credentials files (~/.aws/credentials), and lastly instance profiles. So nothing is lost from the original way of authentication for S3 notebooks.

One note is that the documentation mentions AWS_SECRET_KEY, but this [thread](https://github.com/aws/aws-cli/issues/97) mentions a standardization for AWS_SECRET_ACCESS_KEY. I've tested this PR to work with my set of AWS_SECRET_KEY and AWS_SECRET_ACCESS_KEY as well.

**Comment by felixcheung** [comment]
I see. cool, thanks for explaining.

**Comment by Leemoonsoo** [comment]
Tested and LGTM!

**Pull request closed without merging**
