### PR TITLE
[ZEPPELIN-973, ZEPPELIN-954] Table rendering improvements

### PR DESCRIPTION
**Pull request by jasonxh**
### What is this PR for?
This PR fixes a few minor issues from the recent introduction of Handsontable for table rendering (https://github.com/apache/incubator-zeppelin/pull/858):
* Render up to 5 digits after decimal point instead of always rounding to integers
* Allow visual selection of table cells (for copy)
* Default to text renderer instead of numeric renderer

### What type of PR is it?
Bug Fix, Improvement

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-973
* https://issues.apache.org/jira/browse/ZEPPELIN-954

### How should this be tested?
Output some rows with floating point numbers and render them in a table.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by corneadoug** [comment]
@jasonxh Thanks for the fix
Next time if possible, please add a simple code example for testing, like:
```
print(s"""%table
name\tsize
sun\t127.6
moon\t0.6458
gerard\t45.234856803""")
```
It can save a lot of time to the reviewer :)

I tested and the decimal formating is working great, HTML and string rendering is still good too.

Regarding the selection cell for copy, I would advise to use both:
```
fragmentSelection: true,
disableVisualSelection: true,
```

This would remove the cell selection (with the border), and allow selection of the table text visually.
screen shot 2016-06-08 at 2 36 59 pm

So except for that small configuration change, LGTM

**Comment by jasonxh** [comment]
Thanks @corneadoug . I've updated the PR with your suggestions. I'll remember to paste a code snippet next time. :)

**Comment by corneadoug** [comment]
LGTM
Anybody's welcome to test it too

**Comment by r-kamath** [comment]
@corneadoug :)
@jasonxh Thanks for the fix. LGTM

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by corneadoug** [comment]
@jasonxh I can't find you somehow on the JIRA user id.
Could you give it to me?

**Comment by jasonxh** [comment]
@corneadoug it's the same handle as github, jasonxh

**Comment by corneadoug** [comment]
@jasonxh can you try to assign yourself to those two JIRA issues? somehow I can't do it

**Comment by corneadoug** [comment]
@jasonxh I managed to do it, thanks

**Comment by gauravkumar37** [comment]
Regarding selecting data from the table (ZEPPELIN-954), it works but only the first time. I have tried using both Firefox and Chrome (latest versions).
I am using %sql to output a table from spark sql. It works when I refresh the page and the data is pre-populated from the previous run. After I run the query again and fresh data is rendered, selecting text doesn't work.

**Comment by jasonxh** [comment]
@gauravkumar37 I noticed the same thing. There's some cleanup issue regarding handsontable. I've reopened [ZEPPELIN-954] and I'm working on a fix.

**Comment by corneadoug** [comment]
Handsontable isn't properly instantiated, it's creating a lot of them

**Comment by gauravkumar37** [comment]
@corneadoug I think probably that's the reason the UI gets sluggish after a while.

**Pull request closed without merging**
