### PR TITLE
ZEPPELIN-45: Integrate Tajo with Zeppelin

### PR DESCRIPTION
**Pull request by blrunner**
I succeed to test on local tajo cluster and distributed tajo cluster and I borrowed some classes from apache commons dbcp2 for unit test implementation.

Please see following site.
https://issues.apache.org/jira/browse/ZEPPELIN-45

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the contribution!
Let me test this.

**Comment by Leemoonsoo** [comment]
Tested and works well.
One more thing is, could you add TajoInterpreter class to the default configuration in ZeppelinConfiguration? line 383, ZEPPELIN_INTERPRETERS property.
This values are used when zeppelin-site.xml is not exists.

**Comment by blrunner** [comment]
Hi @Leemoonsoo 

Thanks for your review. I've updated this as follows.

* Added this to ZeppelinConfiguration for default configuration.
* Updated Tajo builder order because it had caused a problem to ProtocolBuffer dependency.

And if you authorize me to assign JIRA issue, it would be better for me to contribute Zeppelin continuously.

Cheers
Jaehwa

**Comment by blrunner** [comment]
I found that ProtocolBuffer wrong version had been downloaded occasionally. I'm digging this.

**Comment by blrunner** [comment]
I fixed a bug about protobuf version.

**Comment by Leemoonsoo** [comment]
Looks good to me!

**Pull request closed without merging**
