### PR TITLE
ZEPPELIN-455 Improve build instruction

### PR DESCRIPTION
**Pull request by Leemoonsoo**
This PR improves build instruction in README.md
https://issues.apache.org/jira/browse/ZEPPELIN-455

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me.
Do we mention all interpreters here or only those who mandatory require a build-time flags? (i.e Flink is not here)

**Comment by Leemoonsoo** [comment]
Thanks. While 'Build from source' section on the [install page](http://zeppelin.incubator.apache.org/docs/0.5.5-incubating/install/install.html) points README.md, it is good to list if any interpreter has build flag that user should aware. But i think if there're no special option to configure in build-time, no reason to mention.

**Comment by felixcheung** [comment]
looks good

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
