### PR TITLE
Line chart with focus

### PR DESCRIPTION
**Pull request by catap**
This pull request included https://github.com/apache/incubator-zeppelin/pull/310

### CODE REVIEW

**Comment by bzz** [comment]
Thank you for contribution!

Shall #310 be closed then? 

A bit on description as well as a screenshot for GUI changes is a big help for reviewer and from my experience helps to land changes much faster.

**Comment by catap** [comment]
#310 may be closed if we would like do review both commits in this pull request.

I think it is the best way.

Ok, let's explain that my patches is doing.

For example I have time series with history of EUR/USD quotes.

When I upload it to zeppelin, I have line chart below:
screen shot 2015-09-18 at 12 14 41

The chart looks bad because show zero at Y. And I fix it by my first commit:
screen shot 2015-09-18 at 12 15 50

The second patch add an extended version of Line Chart that solve problem with zoom of chart. For example:
screen shot 2015-09-18 at 12 17 11

**Comment by Madhuka** [comment]
+1

**Comment by bzz** [comment]
@catap thank you for clean explanation!
\cc @corneadoug for a review

**Comment by corneadoug** [comment]
Hi,
I tried this branch so here is my PR review:

* Feature works well, and checkbox as option is enough for now
* Code is good, and state is saved in paragraph config
* *[ ] Both options are not needed for every graph and should be shown on line chart only

**Comment by corneadoug** [comment]
I saw a few more improvements possible:
* Since we are setting a new config option: ``paragraph.config.graph.lineWithFocus`` doing a new graphMode is not necessary (it would even remove a lot of code not to do it)
* One problem with having ``lineWithFocus`` and ``forceY`` set in ``paragraph.config.graph`` is that when we change the graph type, those options are still there. The best would be to add them into ``paragraph.config.graph.options`` and clear that ``options`` object when we change graph

**Comment by corneadoug** [comment]
@catap If you can do those improvements, I will merge it :)

**Comment by catap** [comment]
Let's merge it!

I'm little bit busy and not sure that can find the time to fix it in next few days ;)

**Comment by corneadoug** [comment]
@catap Do you want me to do a PR on this branch then? I got time :p

**Comment by catap** [comment]
sure, feel free to send PR to this branch with you changes ;)

**Comment by corneadoug** [comment]
@catap okay, just realized the lineWithFocus was not an option but a totally different kind of graph in nvd3.

So the PR is good as it is

**Pull request closed without merging**
