### PR TITLE
[HOTFIX] Authentication doesn't work after upgrade to jetty9

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
After the jetty9 upgrade https://github.com/apache/incubator-zeppelin/pull/831, authentication seems doesn't work. This PR fixes problem by applying shiro filter only /api/*

### What type of PR is it?
Hot Fix

### Todos
* [x] - Fix

### How should this be tested?
enable authentication (edit conf/shiro.ini) and try login

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Tested, LGTM.
CI fails for unrelated reason.

**Comment by prabhjyotsingh** [comment]
Update: login information does not stays after page refresh.

**Comment by jongyoul** [comment]
LGTM

**Comment by bzz** [comment]
👍  Looks great, thank you for hotfixing!

It looks like it's flaky webapp build somehow.

```
olve@1.1.7, fileset@0.2.1, escodegen@1.8.0, js-yaml@3.6.0, handlebars@4.0.5)
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/incubator-zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] 
[ERROR] npm ERR! Callback called more than once.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/incubator-zeppelin/zeppelin-web/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 

[INFO] Zeppelin: web Application .......................... FAILURE [10:49 min]
```

**Comment by bzz** [comment]
[ZEPPELIN-836](https://issues.apache.org/jira/browse/ZEPPELIN-836) was created to address CI issues

**Comment by corneadoug** [comment]
Can you try to re-trigger CI?

**Comment by Leemoonsoo** [comment]
After couple of different trial, figured out apply shiro filter to `/*` as before, and use authcBasic (default browser user auth dialog) instead of authc (bootstrap user auth dialog) is the simplest fix at the moment. 

It's the dialog is bit ugly but authentication is functioning as before. 
I have created a separate issue to bringing our fancy auth dialog back https://issues.apache.org/jira/browse/ZEPPELIN-837

**Comment by prabhjyotsingh** [comment]
Tested, works for now, and user session remains after page refresh.

**Comment by Leemoonsoo** [comment]
Thanks @prabhjyotsingh taking a look. I'm merging it into master as a hotfix

**Pull request closed without merging**
