### PR TITLE
Add animation for dropdown menu

### PR DESCRIPTION
**Pull request by r-kamath**

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Looks neat, LGTM.

**Comment by corneadoug** [comment]
Barely can see any change compare to original one.
If you use 0.2s as transition time, its better

**Comment by Leemoonsoo** [comment]
LGTM.

**Comment by Leemoonsoo** [comment]
both okay 0.1, 0.2s

**Comment by r-kamath** [comment]
@corneadoug my idea was to have some animation instead of `display:block`. 0.2s sounds good to me. 55f9969

**Comment by corneadoug** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
