### PR TITLE
Minor Doc update - add SparkR to spark interpreter docs

### PR DESCRIPTION
**Pull request by jeffsteinmetz**
### What is this PR for?
Minor documentation update that mentions the SparkR interpreter.
Minor grammar updates.

### What type of PR is it?
Documentation

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by darionyaphet** [comment]
+1

**Comment by jeffsteinmetz** [comment]
fixed merge conflicts.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions.

**Pull request closed without merging**
