### PR TITLE
Add username in place of Connected

### PR DESCRIPTION
**Pull request by ravicodder**
### What is this PR for?
To show more information on the navigation bar about user.
 - show 'Connected' if it is an anonymous user.
 - show the username if it is not an anonymous user.

### What type of PR is it?
Improvement

### Todos
* [x] - Change HTML

### How should this be tested?
Case 1 :   Anonymous User
                to be an anonymous user, make the following changes in /conf/shiro.ini  file
               1. Uncomment                    /** = anon
               2. Comment                       /** = authcBasic
               3. Restart Zeppelin.

case 2:    Non-anonymous User
               to be a non-anonymous user, make the following changes in /conf/shiro.ini  file
               1. Comment                     /** = anon
               2. Uncomment                 /** = authcBasic
               3. Restart Zeppelin
               4. On Zeppelin Web page it will ask for username and password. Use one of the username and    password from the list  given in conf/shiro.ini file to login.

### Screenshots (if appropriate)
For example, if anonymous user it will show 'Connected'.
screen shot 2016-03-21 at 12 14 53 pm
And for non -anonymous user for example a user with userid 'admin'  will show the username as below
screen shot 2016-03-21 at 12 16 28 pm

### Questions:
* Does the licenses files need update?no
* Is there breaking changes for older versions?no
* Does this needs documentation?no

### CODE REVIEW

**Comment by ravicodder** [comment]
Ready for review.

**Comment by corneadoug** [comment]
LGTM, however we might want to limit the size of the username with a truncate

**Comment by ravicodder** [comment]
Added limit to size and we can see the complete username on tool tip 
screen shot 2016-03-22 at 4 41 29 pm

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
I'm merging if there're no more discussions

**Pull request closed without merging**
