### PR TITLE
[ZEPPELIN-49] Interpreter.getProperty returns wrong value

### PR DESCRIPTION
**Pull request by jongyoul**
- Fixed to return p, not property

### CODE REVIEW

**Comment by RamVenkatesh** [comment]
LGTM!

**Comment by jongyoul** [comment]
@RamVenkatesh Thanks.

**Comment by bzz** [comment]
Looks great! 
Any way to test it to avoid further errors, by the way?

**Comment by jongyoul** [comment]
@bzz Do you want to test the method of Interpreter.getProperty itself? It can help make sample subclass of Interpreter including static register codes and then make an instance with some properties and and them manually. Do you think it is good?

**Comment by bzz** [comment]
@jongyoul That would be great, but this sounds too complicated for such a change.. Do you think it worth doing now?

**Comment by jongyoul** [comment]
If we have a plan to change an implementation of Interpreter, it would be good. Otherwise, it's a little tricky. Please tell me your plan.

**Comment by bzz** [comment]
I agree, lets address it in separate PR later, in case we actually need it.

**Comment by bzz** [comment]
Merging this one if there is no discussion

**Pull request closed without merging**
