### PR TITLE
ZEPPELIN-104 Spark-1.4 as default Zeppelin's build profile

### PR DESCRIPTION
**Pull request by Leemoonsoo**
This PR makes Spark-1.4 as default Zeppelin's build profile. https://issues.apache.org/jira/browse/ZEPPELIN-104

And Enabling CI test Zeppelin with spark version 1.4

### CODE REVIEW

**Comment by bzz** [comment]
Looks great :+1: for tests!

**Comment by Leemoonsoo** [comment]
Test is fixed :-)

Ready to merge.

**Comment by Leemoonsoo** [comment]
merging if there is no more discussions

**Comment by jongyoul** [comment]
I've run Zeppelin with spark 1.4. LGTM

**Pull request closed without merging**
