### PR TITLE
[ZEPPELIN-328] Interpreter page should clarify the % magic syntax for interpreter group.name

### PR DESCRIPTION
**Pull request by felixcheung**
Currently the Interpreter page like the interpreters as
hive %hql
However, this does not work unless hive is the default group - otherwise one would require the full %group.name.
It seems it would be better to list interpreter as %group.name on the page.

### CODE REVIEW

**Comment by felixcheung** [comment]
Before
image

After
image

Others
image
image

image

**Comment by felixcheung** [comment]
Any comment is welcome

**Comment by corneadoug** [comment]
If I remember well (from last time I looked in that part of the code). Its not mandatory for an interpreter to have a group. The tutorial https://zeppelin.incubator.apache.org/docs/development/writingzeppelininterpreter.html didn't even mentioned it. So if settings.name is indeed set, in the case of %angular and %md it would be better to not have the group

**Comment by felixcheung** [comment]
I guess it's not required but the name is used as the group if absent
Interpreter.java
```
  public static void register(String name, String className) {
    register(name, name, className);
  }

  public static void register(String name, String group, String className) {
    register(name, group, className, new HashMap<String, InterpreterProperty>());
  }

  public static void register(String name, String group, String className,
      Map<String, InterpreterProperty> properties) {
    registeredInterpreters.put(group + "." + name, new RegisteredInterpreter(
        name, group, className, properties));
  }
```

Agreed if there is only one interpreter in the group then it's better to have `%sh` instead of `%sh.sh`
Ideally we should know if the interpreter is the default of its group in that case we could list `%spark, %spark.pyspark, %spark.sql, %spark.dep`?

**Comment by felixcheung** [comment]
Better?

image
image

**Comment by corneadoug** [comment]
If the rule is to not show interpreter.name for the first,  wouldn't it show %hive instead of %hive.hql?
could be better to have: if the group name = interpreter name, just show the interpreter name

But it's my guess since I don't understand well the problem of default group

**Comment by felixcheung** [comment]
I think that is in fact correct - you could run the default interpreter in any group with %group but not %name - ie. `%hive` works but `%hql` does not (it fails with `hql interpreter not found` error)
Also in such case group name != (default) interpreter name

**Comment by corneadoug** [comment]
I see, didn't expect %hive not to work, better always use %hive.hql than %hive then?

**Comment by felixcheung** [comment]
I think you mean %hql (interpreter name) not working.
Using `%hive` (hql is the default interpreter) or `%spark` (spark/scala is the default interpreter) seems fine to me...

**Comment by felixcheung** [comment]
any more feedback on this?

**Comment by corneadoug** [comment]
I guess the question is:
What is the rule to show the %group.%name

Removing the %name for the first element of each interpreter doesn't sound that reliable.

Like you said before:
> Agreed if there is only one interpreter in the group then it's better to have %sh instead of %sh.sh
> Ideally we should know if the interpreter is the default of its group in that case we could list %spark, %spark.pyspark, %spark.sql, %spark.dep?

To me it should be: if %group = %name we only show %group.
I'm not sure there is a default settings, or at least we don't receive any from the server

**Comment by felixcheung** [comment]
I looked into this more.
The default interpreter for a given group is the first interpreter:
https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NoteInterpreterLoader.java#L131
```
      // next, assume replName is 'group' of interpreter ('name' is ommitted)
      // search interpreter group and return first interpreter.
      for (InterpreterSetting setting : settings) {
        intpGroup = setting.getInterpreterGroup();
        Interpreter interpreter = intpGroup.get(0);
```
In such case the `name` can be omitted and only the `group` is required.
I think this matches the behavior here.

It might be better if there is a way from a group of interpreters to decide which is the default interpreter rather then the first one in ZEPPELIN_INTERPRETERS (https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java#L396), but that might over complicate the design.

**Comment by Leemoonsoo** [comment]
Please take a look https://issues.apache.org/jira/browse/ZEPPELIN-74 about omitting 'group' or 'name'.
If zeppelin can display 'group' and 'name' in a way user can learn omit rule as well, that would be really cool.

**Comment by felixcheung** [comment]
Updated to handle default group. My understanding is the default group is the first interpreter group from config.

Here's what it looks like:
image

image

image

**Comment by corneadoug** [comment]
Why isn't %pyspark -> %spark.pyspark
Or %ignite -> %ignite (default) ?

**Comment by felixcheung** [comment]
because when spark is the default group, you can run pyspark by simply putting `%pyspark%` at the beginning of the paragraph. This is my understanding of @Leemoonsoo feedback - and matches the currently implemented omit rules.

`(default)` here is the default interpreter of the default group, which means you can omit `%spark` or `%spark.spark` and the paragraph is will run as Spark Scala. If there is a better way to represent that, please let me know.

**Comment by corneadoug** [comment]
Okay, got it

**Comment by felixcheung** [comment]
any more thoughts on this?

**Comment by corneadoug** [comment]
No, it's good to go.
I will be merging if no more comments.

**Pull request closed without merging**
