### PR TITLE
[WIP] Two SparkR implementation conflict in master branch

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Recently #208 and #702 are merged into master branch.
They passed the CI test individually, but failing after both merged.

* zeppelin-web build error
```
[ERROR] npm ERR! registry error parsing json
[ERROR] npm http 200 https://registry.npmjs.org/bower/1.7.2
[ERROR] npm ERR! SyntaxError: Unexpected token 
[ERROR] npm ERR! ï¿½ï¿½Y[oï¿½6ï¿½+ï¿½ï¿½6ï¿½ï¿½ulEï¿½ï¿½ï¿½
[ERROR] npm ERR! ï¿½{hï¿½ï¿½Cï¿½Ë‘ï¿½L=RJï¿½ï¿½oï¿½9bï¿½4ï¿½ï¿½ï¿½ï¿½W4ï¿½["ï¿½ï¿½wnï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½2Cï¿½Ï•nï¿½ï¿½ï¿½U`ï¿½ï¿½aï¿½
[ERROR] npm ERR! Gï¿½p^@ï¿½ï¿½$eï¿½Ley,ï¿½ï¿½IUï¿½"/Kï¿½,qrï¿½[8ï¿½Fï¿½ï¿½ï¿½^ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½ï¿½ï¿½ï¿½ï¿½=x?ï¿½}ï¿½ï¿½{Wï¿½+ï¿½ï¿½ï¿½Ü³Ð€ìµ±ï¿½ï¿½ï¿½}
```

* 'SparkRInterpreter.java' and 'RRepl.java' uses the same interpreter name. 'spark.r'.
That conflicts and make https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinSparkClusterTest.java#L87 fails.

* R.md and r.md both exists under same directory. That confuses git client.

### What type of PR is it?
Hot Fix

### Todos
* [x] - Merge R.md and r.md
* [x] - Fix zeppelin-web build error
* [x] - Change interpreter listing order

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by bzz** [comment]
@Leemoonsoo thank you for taking care of CI failure on short notice!

**Comment by bzz** [comment]
Looks great to me, let's merge asap as a hotfix

**Comment by elbamos** [comment]
Is there a proposal for what Eric and I should do about the name conflict?

**Comment by Leemoonsoo** [comment]
I'm merging it as a hotfix.

**Comment by Leemoonsoo** [comment]
Regarding, name conflict, i can come up with some options.

a. Keep the same name 'spark.r' for both [SparkRInterpreter](https://github.com/apache/incubator-zeppelin/blob/master/spark/src/main/java/org/apache/zeppelin/spark/SparkRInterpreter.java) and [RRepl](https://github.com/apache/incubator-zeppelin/blob/master/r/src/main/java/org/apache/zeppelin/rinterpreter/RRepl.java).
And let user select it in build time using maven profile, -Pr for RRepl, -Psparkr for SparkRInterpreter, or select it in a runtime using `zeppelin.interpreters` property in conf/zeppelin-site.xml

b. Change SparkRInterpreter name to 'spark.sparkr', similar to PySparkInterpreter uses the name 'spark.pyspark'

c. Change RRepl, and KnitR name from 'spark.r', 'spark.knitr' -> 'r.r', r.knitr'. 
And make RRepl and KnitR more like generic R support rather than SparkR support. Similar to what [ZEPPELIN-502](https://issues.apache.org/jira/browse/ZEPPELIN-502) trying to do for python


Personally, i'm good with all three options and prefer c) as a long term plan, while my guess is many R users will use r without sparkr integration.

What do you think?

**Comment by elbamos** [comment]
My preference is b because it imposes the least burden on users.

I think most R users will want spark integration, and I think we disagree about which interpreters provide closer spark integration.

**Pull request closed without merging**
