### PR TITLE
ZEPPELIN-306 - Fix Notebook Action bar to top

### PR DESCRIPTION
**Pull request by corneadoug**
This PR fix the Notebook Action bar, so that it's accessible even after scroll

screen shot 2015-09-21 at 3 47 57 pm

Because of the CSS changes, I had to change the tooltip from top to bottom

screen shot 2015-09-21 at 3 36 02 pm

### CODE REVIEW

**Comment by corneadoug** [comment]
Ready!

**Comment by prabhjyotsingh** [comment]
If I change the view to simple or report it looks broken.

screen shot 2015-09-21 at 12 48 51 pm

**Comment by corneadoug** [comment]
Fixed by adding a background color
screen shot 2015-09-21 at 5 12 03 pm

**Comment by felixcheung** [comment]
looks good!

**Comment by r-kamath** [comment]
LGTM!

**Comment by corneadoug** [comment]
Ready To Merge then!

**Pull request closed without merging**
