### PR TITLE
ZEPPELIN-460 Modify style.css for the aesthetically pleasant document…

### PR DESCRIPTION
**Pull request by AhyoungRyu**
I modified style.css file (located in /docs/assets/themes/zeppelin/css/style.css).
The result of this PR is like below attached images.

1. Resize hn tag  font  & Add bottom-border to h2, h3 tag (Because these tags are used a lot for the title.)
 & Adjust table size to web page border
 - Before 
before resize

 - After 
After resize
2. Change code color & Arrange code font size
img1

3. Change Code font-family and reduce the font size
 - Before
before

 - After
after

4. Increase padding size between p, block quote, table, pre, img

### CODE REVIEW

**Comment by felixcheung** [comment]
I like the new font size/spacing code block but it seems the color style is a bit different?

**Comment by AhyoungRyu** [comment]
Thank you for your review @felixcheung : ) 
You mean the small code block ? 
The red color seems like little bit aggressive, so I changed to black like other open source project documentation.

**Comment by Leemoonsoo** [comment]
Cool. A lot better than before. Thank you so much.

**Comment by bzz** [comment]
Looks great, but if its possible not to make fonts smaller - for me that would be even more awesome. 
Mobile devices do not tolerate small fonts.

**Pull request closed without merging**
