### PR TITLE
[ZEPPELIN-185] ZeppelinContext methods like z.show are not working with DataFrame in pyspark

### PR DESCRIPTION
**Pull request by felixcheung**
z.show() doesn’t seem to work properly in Python – I see the same error below: “AttributeError: 'DataFrame' object has no attribute '_get_object_id'"
#Python/PySpark – doesn’t work
rdd = sc.parallelize(["1","2","3"])
Data = Row('first')
df = sqlContext.createDataFrame(rdd.map(lambda d: Data(d)))
print df
print df.collect()
z.show(df)
AttributeError: 'DataFrame' object has no attribute ‘_get_object_id'

More generally, ZeppelinContext methods are not working with Python objects since Py4J would need to know how to serialize it

It turns out the error is caused by Py4J trying to auto convert the DataFrame, which fails since it can only do that for simple types.
Instead of getting conversion to work, the better approach is to pass along the inner java object instead. To do that we intercept the call on the python side with a wrapper object instead of letting Py4J handle it

### CODE REVIEW

**Comment by felixcheung** [comment]
This is what it looks like with the fix
image

**Comment by felixcheung** [comment]
Same failure in build #654 https://travis-ci.org/apache/incubator-zeppelin/builds/73126955
And #623 https://travis-ci.org/apache/incubator-zeppelin/builds/72767991

testAngularDisplay(org.apache.zeppelin.ZeppelinIT)  Time elapsed: 37.627 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<BindingTest_[1]_> but was:<BindingTest_[]_>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.apache.zeppelin.ZeppelinIT.testAngularDisplay(ZeppelinIT.java:275)

Is it some sort of intermitted test failure?

**Comment by Leemoonsoo** [comment]
`org.apache.zeppelin.ZeppelinIT.testAngularDisplay(ZeppelinIT.java:275)` seems flickering test.

it'll be good if we can keep object exchange capability between scala and python. It was done by Zeppelin context (that extends Map), like
```
%spark
z.put("myVar", "from scala")
```

```
%pyspark
z.get("myVar")
```

There're `Merge commit '7599efb54e2941f097473db0b0b3c79b9af98099` in this branch's commit. Can we have more clean commit history?

**Comment by felixcheung** [comment]
Sure. I will rework this, though we might want to rethink the cross interpreter data passing a bit - it only works with simple type with py4j for instance.





On Sun, Aug 2, 2015 at 12:36 PM -0700, "Lee moon soo" <notifications@github.com> wrote:
`org.apache.zeppelin.ZeppelinIT.testAngularDisplay(ZeppelinIT.java:275)` seems flickering test.

it'll be good if we can keep object exchange capability between scala and python. It was done by Zeppelin context (that extends Map), like
```
%spark
z.put("myVar", "from scala")
```

```
%pyspark
z.get("myVar")
```

There're `Merge commit '7599efb54e2941f097473db0b0b3c79b9af98099` in this branch's commit. Can we have more clean commit history?


---

**Comment by felixcheung** [comment]
Closing this and replacing with #178

**Comment by VahidTehrani** [comment]
Hi felixcheung,

I recently tried to move a Spark DataFrame from Python to Scala. 
`z.put("spDf", spDf)`
but I got the same error you got:
`AttributeError: 'DataFrame' object has no attribute '_get_object_id'`
Any idea how we can fix it?

**Comment by felixcheung** [comment]
I don't think this is currently supported, looking at the code.
The error is caused by py4j trying to convert the DataFrame type.
Do you mind opening a JIRA for this and I will take a look at a possible fix?

**Pull request closed without merging**
