### PR TITLE
ZEPPELIN-462 - Fix Navbar CSS

### PR DESCRIPTION
**Pull request by corneadoug**
This PR is fixing https://issues.apache.org/jira/browse/ZEPPELIN-462

Navbar alignment has been reworked
screen shot 2015-11-27 at 2 07 12 pm

And Navbar style on smaller resolutions has been fixed
screen shot 2015-11-27 at 1 33 35 pm

### CODE REVIEW

**Comment by r-kamath** [comment]
tested. LGTM :+1:

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge if there is no more discussions

**Comment by jongyoul** [comment]
LGTM

**Pull request closed without merging**
