### PR TITLE
Removed custom repositories

### PR DESCRIPTION
**Pull request by jwcarman**
I removed the custom repositories from the pom.xml file, deleted my ~/.m2/repository directory and ran:

mvn clean package -Pspark-1.3 -Dhadoop.version=2.2.0 -Phadoop-2.2 -DskipTests

which succeeded.

### CODE REVIEW

**Comment by felixcheung** [comment]
+1
Will we end up having profile for Cloudera or Hortonworks of Spark? Cloudera CDH for example has a different akka build and we might need to pull from their repo.

**Comment by Leemoonsoo** [comment]
Thanks for contribution.

One question, will this changes still build zeppelin with cdh hadoop dependencies?
for example `mvn package -Dhadoop.version=2.0.0-mr1-cdh4.7.1`
?

**Comment by jwcarman** [comment]
Running the command:

mvn clean package -Dhadoop.version=2.0.0-mr1-cdh4.7.1 -DskipTests

I get:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [  1.617 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [  5.463 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [  2.345 s]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 15.725 s]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  1.194 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  1.121 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  1.219 s]
[INFO] Zeppelin: Hive interpreter ......................... SUCCESS [  1.541 s]
[INFO] Zeppelin: Tajo interpreter ......................... SUCCESS [  1.305 s]
[INFO] Zeppelin: web Application .......................... SUCCESS [ 38.142 s]
[INFO] Zeppelin: Server ................................... SUCCESS [  6.217 s]
[INFO] Zeppelin: Packaging distribution ................... SUCCESS [  0.229 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2015-05-02T09:41:32-04:00
[INFO] Final Memory: 109M/1809M
[INFO] ------------------------------------------------------------------------


Now, when I leave off the -DskipTests, I get some failure because it seems to be trying to load some JS testing framework in Safari and it can't find a "driver", so I need to get that all set up so that I can run a full build.  But, it seems to be able to download everything it needs.

**Comment by Leemoonsoo** [comment]
Looks good to me.

@jwcarman
Are you interested in removal of custom pluginRepository, too?

**Comment by jwcarman** [comment]
Yeah, I was going to remove that also.  I'll create a separate pull request for that.

**Comment by jwcarman** [comment]
Okay, maybe I won't :)

**Comment by Leemoonsoo** [comment]
Custom plugin repository were for "s3-upload-maven-pugin" which is used in zeppelin-distribution module.
Could you change s3-upload-maven-pugin plugins version from '1.2-SNAPSHOT' to '1.2' ? then i think i can merge this PR.

**Comment by jwcarman** [comment]
Done.

**Comment by Leemoonsoo** [comment]
LGTM.
If there're no more discussions, i'm merging it.

**Pull request closed without merging**
