### PR TITLE
[WIP] ZEPPELIN-52 Long statements in paragraph and going beneath the control bar

### PR DESCRIPTION
**Pull request by r-kamath**
before
screen shot 2015-11-09 at 11 55 38 pm

after
screen shot 2015-11-09 at 11 55 38 pm

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Gave it a spin dosen't work on Firefox and IE 10, but works on chrome, safari and edge (windows 10).

**Comment by r-kamath** [comment]
@prabhjyotsingh tested on Firefox and IE :tada:

**Comment by prabhjyotsingh** [comment]
tested, and this works for me.

**Comment by Leemoonsoo** [comment]
Thanks for the improvement.
There was design principles when Zeppelin UI implemented in the beginning.
I just documented that https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61328042

My preference is improvement without adding more empty spaces inside of Paragraph.
What do you think?

**Comment by r-kamath** [comment]
@Leemoonsoo Thanks for the document.
>...without adding more empty spaces inside of Paragraph...

makes sense. working on a better solution!

**Comment by r-kamath** [comment]
@Leemoonsoo how about we hide the control bar and show it on mouseover event of the paragraph

**Comment by Leemoonsoo** [comment]
Here's little bit of history.

Currently, Zeppelin has 3 Looknfeels. 'default', 'simple' and 'report'. But before the looknfeel feature, there were only single style, and that was 'simple'. 'default' was introduced as a alternative to 'simple', based on feedbacks

  * Hard to distinguish Paragraphs -> gray background
  * Hard to find buttons -> controls always shown

Therefore 'default' was intended to show controls always, while 'simple' show only on hover mouse.

It could be challenging, but what do you think make it aware contents length of 1st line and hide (or make it almost transparent) control only when there're text underneath, and show as a normal on mouse hover? Do you think it's a good idea?

**Comment by r-kamath** [comment]
>what do you think make it aware contents length of 1st line and hide (or make it almost transparent) control only when there're text underneath, and show as a normal on mouse hover? 

Will make the paragraph ui inconsistent.  how about an auto show/hide option which can be turned on or off. we can call it "Auto hide controls"

**Comment by corneadoug** [comment]
Not a big fan of adding too many switch options, there is already many.

One possible way, would be to show those controls outside of the text editor when there is a title shown.
That way, in some case it wouldn't obstruct the editor.

I tried before to play with the opacity of that action buttons component background, but this is pretty much as far as we can go.

**Comment by Leemoonsoo** [comment]
Another idea is, when cursor hit the controls, like
image

Automatically adds newlines char after '%[name]', 

image

**Comment by felixcheung** [comment]
I like the newline idea, but %[name] might not be there if it's the default interpreter?

**Comment by Leemoonsoo** [comment]
I think leaving it unchanged is okay for now.
In the future, maybe we can think automatically adds default interpreter name.

**Pull request closed without merging**
