### PR TITLE
ZEPPELIN-953 ] Jquery.floatThead delete the information from the license file.

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
<Jquery.floatThead> is no longer used.
But the license document contains the appropriate information.

Due to the following PR <jquery.floatThead> was removed.
Resulting in a using < HandsonTable >.
https://github.com/apache/incubator-zeppelin/pull/858

### What type of PR is it?
 Documentation

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-953

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Agreed, LGTM 👍

**Comment by prabhjyotsingh** [comment]
This CI failure was fixed with https://github.com/apache/incubator-zeppelin/pull/958. Can you rebase with master and re-trigger ?

**Comment by cloverhearts** [comment]
@prabhjyotsingh  Okay, Rebasing is executed.

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by bzz** [comment]
Looks great to me, @cloverhearts thank you for catching it.

Merging if there is no more discussion

**Pull request closed without merging**
