### PR TITLE
Add job operation API

### PR DESCRIPTION
**Pull request by astroshim**
This PR is related to https://issues.apache.org/jira/browse/ZEPPELIN-137.
I added some notebook job operations.

Here is the examples.
* Get notebook job status.
```
]# curl -XGET http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA
{"status":"OK","body":[{"id":"20151121-212654_766735423","status":"FINISHED","finished":"Tue Nov 24 14:21:40 KST 2015","started":"Tue Nov 24 14:21:39 KST 2015"},{"id":"20151121-212657_730976687","status":"FINISHED","finished":"Tue Nov 24 14:21:40 KST 2015","started":"Tue Nov 24 14:21:40 KST 2015"},{"id":"20151121-235508_752057578","status":"FINISHED","finished":"Tue Nov 24 14:21:40 KST 2015","started":"Tue Nov 24 14:21:40 KST 2015"},{"id":"20151121-235900_1491052248","status":"FINISHED","finished":"Tue Nov 24 14:21:41 KST 2015","started":"Tue Nov 24 14:21:40 KST 2015"},{"id":"20151121-235909_1520022794","status":"RUNNING","finished":"Tue Nov 24 02:53:51 KST 2015","started":"Tue Nov 24 14:21:41 KST 2015"}]}
```

* Run notebook job.
```
]# curl -XDELETE http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA
{"status":"ACCEPTED"}
```

* Stop(Delete) notebook job.
```
]# curl -XDELETE http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA
{"status":"ACCEPTED"}
```

* Run requested paragraph job.
```
]# curl -XPOST http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA/20151121-212654_766735423
{"status":"ACCEPTED"}
```

* Stop(Delete) requested paragraph job.
```
]# curl -XDELETE http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA/20151121-212654_766735423
{"status":"ACCEPTED"}
```

### CODE REVIEW

**Comment by bzz** [comment]
Great contribution! 
Could you please check that it also follows project's [java styleguide](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace) ?

**Comment by springml** [comment]
Thank you for the contribution.
Is it possible to pass a runtime parameter to the "Run notebook" api?

**Comment by astroshim** [comment]
@bzz Thank you for your comment.
But I don't understand what you mean the java style, could you tell me more detail?

**Comment by astroshim** [comment]
@springml Thank you for your comment.
What is the runtime parameter? Is runtime you mean is the time will be executed?

**Comment by springml** [comment]
That is correct.  I want to be able to pass a parameter (e.g. jobid) when calling the api to execute the  notebook.  Something like this would be great:
]# curl -XDELETE http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA?jobid=1001
{"status":"ACCEPTED"}

**Comment by astroshim** [comment]
@springml I am going to add more APIs related to scehdule job. That could be solution.

**Comment by bzz** [comment]
@astroshim Sure! Zeppelin project agreed to adhere this styleguide for Java language https://google.github.io/styleguide/javaguide.html 

We encourage all contributors to read this document carefully.

It means that all the code in the project should be formatted according rules of that guide. 
Some of them are enforced through the build system (using checkstyle maven plugin), like max length of the line - that is why you had "whitespace\lineLength build error". 

Some rules are not enforced automatically, but are a good practices to follow. This is one of the reasons to have a "code review" in PullRequests here.

Your code looks great, but there are still a few cases where formatting that can be improved before merging, i.e [horizontal whitespaing](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace)

Things like
```java
while(paragraph.getStatus() == Status.PENDING) ...
```

according to the link above should look like
```java
while (paragraph.getStatus() == Status.PENDING) ...
```

Another thing to check is [vertical whitespace](https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace) - an empty line between two consecutive method fields of the class (fields, methods).

Please let me know if it that helps!

**Comment by astroshim** [comment]
@bzz Your comment is very helpful. Thank you very much!!

**Comment by astroshim** [comment]
I added cron job api's 

- Add cron job
```
]# curl -XPOST http://121.156.59.2:8080/api/notebook/cron/2B79J5UQB -d '{"cron":"* * * * * ?" }'
{"status":"ACCEPTED"}
```

- get cron job
```
]# curl -XGET http://121.156.59.2:8080/api/notebook/cron/2B79J5UQB
{"status":"OK","body":"* * * * * ?"}
```

- remove cron job
```
]# curl -XDELETE http://121.156.59.2:8080/api/notebook/cron/2B79J5UQB
{"status":"ACCEPTED"}
```

**Comment by bzz** [comment]
@astroshim looks great!

Could you also please update the [REST API docs](http://zeppelin.incubator.apache.org/docs/0.6.0-incubating-SNAPSHOT/rest-api/rest-notebook.html), by adding a description of new API there?

Docs sources are in https://github.com/apache/incubator-zeppelin/blob/master/docs/rest-api/rest-notebook.md and here are the [instructions](http://zeppelin.incubator.apache.org/docs/0.6.0-incubating-SNAPSHOT/development/howtocontributewebsite.html) on how to build/update them.

BTW there may be a small typo in PR description:
>Run notebook job.
>$ curl -XDELETE http://121.156.59.2:8080/api/notebook/job/2B3Z5BXJA
{"status":"ACCEPTED"}

Instead of `curl -XPOST ...`

**Comment by Leemoonsoo** [comment]
Notebook Rest API returns,

```
CREATED, on createNote
OK,      on deleteNote
CREATED, on cloneNote
```

Interpreter Rest API returns

```
CREATED, on newSetting
OK,      on updateSetting
OK,      on removeSetting
OK,      on restartSetting
```

This PR adds 8 more APIs

```
ACCEPTED, on runNoteJobs
ACCEPTED, on stopNoteJobs
OK,       on getNoteJobStatus
ACCEPTED, on runParagraph
ACCEPTED, on stopParagraph
ACCEPTED, on registerCronJob
ACCEPTED, on removeCronJob
OK,       on getCronJob
```

I think return Status need to be little bit more consistent.
For example, removeCronJob returns `ACCEPTED`, but deleteNote returns `OK`.

So, i think changing `ACCEPTED` to `OK` for all new APIs makes api more consistent.
What do you think?

**Comment by bzz** [comment]
+1 for consistent statuses as well as updating the [REST API docs](http://zeppelin.incubator.apache.org/docs/0.6.0-incubating-SNAPSHOT/rest-api/rest-notebook.html), by adding a description of this API there

**Comment by astroshim** [comment]
@Leemoonsoo @bzz Thank you for your review!
I totally agree with your idea about consistent statuses. I'll fix them.

**Comment by astroshim** [comment]
@bzz I updated REST API docs, could you review?
Thanks.

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by bzz** [comment]
Looks awesome to me!
Merging if there is no further discussion.

**Pull request closed without merging**
