### PR TITLE
[ZEPPELIN-923] Apply new mechanism to ShellInterpreter

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
This PR applies the new interpreter registration mechanism to Shell interpreter.

### What type of PR is it?
Improvement

### Todos
* [x] - Remove static property definition code lines in `shellInterpreter.java` and add `interpreter-setting.json` under the `shell/src/main/resources`

### What is the Jira issue?
[ZEPPELIN-923](https://issues.apache.org/jira/browse/ZEPPELIN-923)

### How should this be tested?
1. apply patch
2. rm -r `interpreter/sh` and `conf/interpreter.json`
3. build source 
4. bin/zeppelin-daemon.sh start
5. Run some shell command

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
😄

**Comment by AhyoungRyu** [comment]
@jongyoul But CI is failed :(  Is this relevant with this PR ?

**Comment by jongyoul** [comment]
@AhyoungRyu One looks irrelevant and another is about rat plugin. you need to exclude interpreter-setting.json in a rat plugin.

**Comment by AhyoungRyu** [comment]
@jongyoul I see. Okay Thanks for letting me know :)

**Comment by prabhjyotsingh** [comment]
@AhyoungRyu have made a fix #4492.7 failed  #958. Can you rebase with master, and re-trigger ?

And yes other is `[INFO] Rat check: Summary of files. Unapproved: 1 unknown: 1 generated: 0 approved: 2 licence.`

**Comment by AhyoungRyu** [comment]
@jongyoul @prabhjyotsingh I excluded `interpreter-setting.json` and also rebased from master.

**Comment by prabhjyotsingh** [comment]
LGTM.

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
