### PR TITLE
Apply #407 into master branch

### PR DESCRIPTION
**Pull request by Leemoonsoo**
#407 addressed https://issues.apache.org/jira/browse/ZEPPELIN-406 and merged into branch-0.5.5
This PR applies it to the master branch

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
It cherry picks ba72645 and take care of files added after branch-0.5.5 is created.
Ready to merge.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by felixcheung** [comment]
looks good

**Comment by jongyoul** [comment]
looks good

**Pull request closed without merging**
