### PR TITLE
ZEPPELIN-161 : Fixing grunt test

### PR DESCRIPTION
**Pull request by Madhuka**
All the test in zeppelin web was failed. Contain older version code 
Here is the fixed.

 - [x] Fixing Karma config
   - [x] Handle js file paths in Karma config in atomically
  - [x] Fixing config properties
 - [x] Updating test spec for current code base version

### CODE REVIEW

**Comment by Madhuka** [comment]
When I check builder log web application was build successfully

End of the log I found

11:01:42,552  INFO org.apache.zeppelin.notebook.Paragraph:211 - RUN : from pyspark.sql.functions import *
print(sqlContext.range(0, 10).withColumn('uniform', rand(seed=10) * 3.14).count())
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated

is it builder resource issue? or Env? any idea?

**Comment by Madhuka** [comment]
`./grunt buildSkipTests` will build without test. It can be used in CI
grunt-buildskiptests

`./grunt build` will contain the test
grunt-build

`./grunt test` will run all the test specs
grunt-test

JIRA[1] is created for integrating those to CI 
[1] https://issues.apache.org/jira/browse/ZEPPELIN-166

**Comment by Madhuka** [comment]
@Leemoonsoo : Ready for Merge
@bzz, @corneadoug This contain the fixed for grunt test.

**Comment by Leemoonsoo** [comment]
Thanks for great contribution. LGTM!

**Pull request closed without merging**
