### PR TITLE
Hotfix - initial notebook name does not increase.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
To increase initial notebook name.

### What type of PR is it?
Bug Fix

### How should this be tested?
execute create new note.

### Screenshots (if appropriate)
 - before
image

- after
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by bzz** [comment]
Looks good to me
 \cc @felizbear @corneadoug for double-check

**Comment by felizbear** [comment]
looks good

**Comment by bzz** [comment]
As it's marked as HOTFIX (urgent), I will proceed merging it if there is no further discussion

**Comment by Leemoonsoo** [comment]
Tested and looks good to me

**Pull request closed without merging**
