### PR TITLE
moved delete button to help protect against accidental clicks

### PR DESCRIPTION
**Pull request by schnee**
### What is this PR for?
The delete notebook action is embedded in the button bar with several other buttons, increasing the potential for an accidental click. This PR moves the delete button out of the "normal" button bar.

### What type of PR is it?
Improvement

### Todos
(none)

### Is there a relevant Jira issue?
No

### How should this be tested?
Create new notebook
populate notebook
delete notebook

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by felixcheung** [comment]
thanks for the contribution. could you add a screenshot please?

**Comment by schnee** [comment]
cursor_and_localhost_8080___notebook_2a94m5j1z

**Comment by Leemoonsoo** [comment]
Thanks for the improvement.
CI test failing is irrelevant, i think.
LGTM!

**Comment by felixcheung** [comment]
@schnee it looks like the trash icon is mis-aligned and off by a few pixels - could you check please?
I suspect it has to do with `<span class="labelBtn btn-group">`

**Comment by schnee** [comment]
After applying the styling, here's the zoomed in view:

cursor_and_localhost_8080___notebook_2a94m5j1z

Appears to have worked. If I can help with the Travis build, let me know, but it seems unrelated.

**Comment by felixcheung** [comment]
awesome. thanks
@corneadoug FYI.

I'm not sure what's going on with travis though, seems like we are having issues. Let's see if we could get more passing a bit later.

**Comment by corneadoug** [comment]
The best way to align it would be to add:
```
vertical-align: middle;
display: inline-block;
```
To the button style and remove the `btn-group`
Otherwise the button's borders are removed when hovered:
screen shot 2016-01-22 at 5 31 00 pm

There is also the same problem with the last element of the button-group (because of tooltip)
In that case, we might want to add `tooltip-append-to-body="true"` to that export button, and this in a css file:
```
.tooltip {
  z-index: 11000;
}
```
Somebody else, might need to double check all the z-index after that though (I didn't found any problem, but I might not have tested everything)

**Comment by schnee** [comment]
applied the styling to the delete button suggested by @corneadoug. Corner rounding of the standalone delete button seems fixed.

cursor_and_localhost_8080___notebook_2a94m5j1z

The other part of Damian's comment seems out of scope for this pull request.

**Comment by corneadoug** [comment]
Thanks LGTM

**Comment by felixcheung** [comment]
Any idea why travis is failing?

**Comment by corneadoug** [comment]
@felixcheung Looks like basic timeout somehow.
I doubt this PR would break anything

**Comment by felixcheung** [comment]
@schnee could you close and reopen this PR one more time to see if travis goes better?

**Comment by corneadoug** [comment]
Alright, seems like a test is now broken:
```
{"method":"xpath","selector":"//*[@id='main']/div//h3/span[1]/button[@tooltip='Remove the notebook']"}
```

Need to change that xpath in **testAngularDisplay** test

**Comment by corneadoug** [comment]
Using this one would solve it:
```
//*[@id='main']/div//h3/span/button[@tooltip='Remove the notebook']
```

**Comment by schnee** [comment]
let's see if that did it.

**Comment by schnee** [comment]
Rock On!

**Comment by felixcheung** [comment]
Great! Merging if there is no more discussion

**Pull request closed without merging**
