### PR TITLE
Increase wait time for selenium test cases so the build fails less often

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
Generally increasing wait time to 30 instead of 5. So that, travis build fails less often.

### What type of PR is it?
Improvement

### Is there a relevant Jira issue?
No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
LGTM.
Merge if there're no more discussions

**Comment by corneadoug** [comment]
Is it in seconds?

**Comment by prabhjyotsingh** [comment]
I know, 30 sec is a lot. But on my local travis this helped.

**Comment by bzz** [comment]
What is the impact on the overall build time in your experience? Also, may that somehow be related to https://issues.apache.org/jira/browse/ZEPPELIN-510 ?

**Comment by prabhjyotsingh** [comment]
Build time might have been increased slightly, but since "waitForText" is called only 8 times, hence it is much.

Yes, even I'm trying to find a solution for ZEPPELIN-510, but not able to reproduce it locally.

**Comment by bzz** [comment]
Can not reproduce locally on os x either. 
So it should be about ~ +3 min build time, right? Could plz you verify on your travis?

Right now on master we have `Elapsed time 37 min 9 sec`

**Comment by prabhjyotsingh** [comment]
This PR took https://travis-ci.org/apache/incubator-zeppelin/builds/97161109 `` Elapsed time 47 min 31 sec  ``

**Comment by bzz** [comment]
What do you think about exploring poll approach here, like #546 ?

**Comment by prabhjyotsingh** [comment]
@bzz agreed, thats a better approach ```Elapsed time 33 min 30 sec```

**Pull request closed without merging**
