### PR TITLE
ZEPPELIN-523 ] table scrolling bug fixed. out of area scroll issue

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
Scrollbar position when you scroll through the table has been modified with parts that are expressed differently in the length of the actual data.

### What type of PR is it?
Bug Fix

### Todos
- [x] Perfect Scroll-based Zeppelin scroll bug fix
- [x] Browser Test
  - [x] Safari (9.0.2(11601.3.9)
  - [x] Firefox (43.0)
  - [x] Chrome (47.0.2526.106 (64-bit)

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-523
### How should this be tested?
Step 1. create table on zeppelin
           example query) 
``` python
%pyspark
TABLE = "%table Header1\tHeader2\n"
for x in range(1,51):
    #TABLE +=  "scroll";
    TABLE +=  str(x);
    if (x%2) == 0:
        TABLE += "\n"
    else:
        TABLE += "\t"
z.put("table_context", TABLE)

```
``` scala
println(z.get("table_context"))
```

Step 2. 
Scroll the mouse over the Table.
#### Before
before

#### After
after

### Questions:
Why did this problem occur?
- ref. https://github.com/noraesae/perfect-scrollbar#how-to-use perfect scrollbar library. 
  height calculation miss.

### CODE REVIEW

**Comment by astroshim** [comment]
Cool fix!
I tested on chrome/firefox/explore10 and working well.
Thanks.

**Comment by corneadoug** [comment]
Tested, LGTM

**Comment by cloverhearts** [comment]
@astroshim @corneadoug Thank you for Feed back! Have a nice day~

**Comment by r-kamath** [comment]
@cloverhearts Thanks for the fix. LGTM

**Comment by cloverhearts** [comment]
@r-kamath Thank you for Feed back!

**Comment by corneadoug** [comment]
@cloverhearts I just merged #554, since those two PRs are making changes on the same component, could you rebase this PR so that we can check that everything still work?

**Comment by cloverhearts** [comment]
@corneadoug okay.

**Comment by cloverhearts** [comment]
@corneadoug 
Sorry. I tried to test with the # 554 and # 556.
# 556 is a single action results, it was confirmed that # 554 is not running.
I want to create a separate PR or to fix a problem in this area, or seems to need to upload the modified code to the current PR.

I'm sorry to bother you.

**Comment by corneadoug** [comment]
@cloverhearts don't really understand, but to rebase you need to do:
```
git fetch incubator-zeppelin
git rebase incubator-zeppelin/master
git pull -f (after fixing potential conflicts)
```

**Comment by cloverhearts** [comment]
rebase complete

**Comment by prabhjyotsingh** [comment]
Wired bug, scroll dosent show after running the paragraph. Happens in all the browsers.

scroll not shown after running paragraph


Apart for this, works good, tested on IE10, FF, Chrome and Safari.

**Comment by cloverhearts** [comment]
@prabhjyotsingh 
Thank you good feedback.
I know that this is a bug.
This bug is that I created a PR and is unrelated to a bug, the bug that already exist in the past.
But I have an idea to fix this bug.
I hope to create a new PR after fix this bug.

**Comment by cloverhearts** [comment]
I close this PR.
And I will make a new PR fix the known bugs table.

**Pull request closed without merging**
