### PR TITLE
Add filter to quickly search the notebook from the list

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
Allows the user to instantly find the notebook from the list shown on the home page and in the Notebook main menu

### What type of PR is it?
Improvement

### How should this be tested?
Enter the search term in the filter input box

### Screenshots
screen shot 2016-01-20 at 3 22 32 pm
<br>
screen shot 2016-01-20 at 3 22 26 pm
<br>
screen shot 2016-01-20 at 3 21 58 pm
<br>
screen shot 2016-01-20 at 3 22 11 pm

### CODE REVIEW

**Comment by vgmartinez** [comment]
Hi @r-kamath,
Nice improvement...LGTM

**Comment by felixcheung** [comment]
cool - @corneadoug

**Comment by corneadoug** [comment]
I will take a look, However first feedbacks:
* The Filter box should be aligned with the Notebook icon in Home page
* Since the same HTML code is used in 2 different places, it should be packaged as a component (html file only) and inserted using ng-include

**Comment by r-kamath** [comment]
@corneadoug thanks for the comments. please take a look at updates

**Comment by corneadoug** [comment]
@r-kamath I would probably reduce that input padding to: `padding: 6px`
screen shot 2016-02-02 at 12 48 24 pm
screen shot 2016-02-02 at 12 48 33 pm

Except for that, its good

**Comment by r-kamath** [comment]
@corneadoug padding fixed in ed41d41

**Comment by minahlee** [comment]
Nice improvement!

I have one suggestion for style.

When user have long name of notebook, dropdown menu's width also changes:
screen shot 2016-02-03 at 11 26 49 am

I think it will look better if you apply width:100% for filter input box. Also, can we add padding into this filter input box as below?
screen shot 2016-02-03 at 11 39 35 am
I applied padding: 0px 10px for #notebook-list>.filter-names

**Comment by r-kamath** [comment]
@minahlee I've updated the css. Also removed the custom clear button for the search box which wasn't working well with this css update.

**Comment by minahlee** [comment]
LGTM merging if there is no more discussion

**Pull request closed without merging**
