### PR TITLE
[ZEPPELIN-281] Windows build

### PR DESCRIPTION
**Pull request by fvaleri**
### What is this PR for?
Give some hints in README for source building on Windows.

### What type of PR is it?
Documentation

### Todos
* [fork] - Fork from the main repo
* [checkout] - Checkout the code
* [build] - Follow the standard way of build
* [test] - Run zeppelin using zeppelin.cmd

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-281

### How should this be tested?
Follow the standard way of build using Git and Maven.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by fvaleri** [comment]
I have done the build process under Windows with and without proxy and it works. 
I have also done some live test with a 1Gb data set on my laptop. No problems.
Can anyone confirm?

I think that we can make small changes to the README just to avoid some pain for those who are behind a corporate proxy.

**Comment by Leemoonsoo** [comment]
Thanks @fvaleri for the proxy settings on build instruction.
LGTM and merge if there're no more discussions

**Comment by ajinkyamahakalkar** [comment]
Hi,
I am trying to build the Zeppelin Jar on a windows machine but the build is getting failed with the following error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:
2.8:copy (copy-artifact) on project zeppelin-interpreter: Error copying artifact
from 
D:\Projects\zeppelin-master\zeppelin-master\zeppelin-interpreter\target\zeppelin-interpreter-0.8.0-SNAPSHOT.jar 
to 
D:\Projects\zeppelin-master\zeppelin-master\zeppelin-interpreter\interpreter\Zeppelin: Interpreter\zeppelin-interpreter-0.8.0-SNAPSHOT.jar: The filename, directory name, or volume label syntax is incorrect -> [Help 1]
Can we not build this project on a Windows Machine?
If yes then what changes do we need to make to build this code?
Thank you..!!

**Comment by conker84** [comment]
@ajinkyamahakalkar please check #2646

**Pull request closed without merging**
