### PR TITLE
Fix getRegisteredInterpreterList to avoid adding null to the list

### PR DESCRIPTION
**Pull request by eranwitkon**
This PR fix the getRegisteredInterpreterList

InterpreterFactory is looping through the interpreters class name list from the config and registering an interpreter for every interpreter found on the disk.
when getRegisteredInterpreterList is called, for every item in the config-interpreters-class-name-list an item is added to the list, a RegisteredInterpreter if found or NULL.
This PR fix it by adding to the list only of the interpreter was found.
This also add a test to test the list are equal 

Ready for review.

### CODE REVIEW

**Comment by eranwitkon** [comment]
I noticed this PR failed on CI. based on the log the InterpreterFactory JUnit failed.
Not sure what to do with it as the unit test pass locally
selection_019

Please advise...

**Comment by eranwitkon** [comment]
Ready for review\merge

**Comment by eranwitkon** [comment]
This PR fix a bug in the getRegisteredInterpreterList.
Ready to review and merge, please.

**Comment by Leemoonsoo** [comment]
How it is different from https://github.com/apache/incubator-zeppelin/pull/240 ?

**Comment by eranwitkon** [comment]
Thus is not different,  240 is closed due to a problem I had with push.
This replace 240.
Thanks

בתאריך יום ד׳, 26 באוג׳ 2015, 20:13 מאת Lee moon soo <
notifications@github.com>:

**Comment by Leemoonsoo** [comment]
My apologies, i mean with #241 (which is merged). Isn't it duplicated?

**Comment by eranwitkon** [comment]
Sorry for that, I had 241 based on 242. Since I did not know if you are
going to accept both.
If #241 is merged then the fix is already in.
Thank.
I will close this pr as well.

בתאריך יום ה׳, 27 באוג׳ 2015, 21:08 מאת Lee moon soo <
notifications@github.com>:

**Comment by eranwitkon** [comment]
@Leemoonsoo I have PR #242 and PR #254 both opened.
#242 is the fix for the InterpreterFactory I will close it.
#254 is new REST API test - can this be reviewed?

**Pull request closed without merging**
