### PR TITLE
[ZEPPELIN-672] Add feature to export tables using Datatables

### PR DESCRIPTION
**Pull request by ankurmitujjain**
### What is this PR for?
It is an extension of #6 #714
It allows user to export data in a paragraph to a TSV/CSV file.

### What type of PR is it?
Feature

### Todos
* [x] - Improves the current Table features like Search, Fixed Headers, Sorting

### Is there a relevant Jira issue?
[ZEPPELIN-672](https://issues.apache.org/jira/browse/ZEPPELIN-672)

### How should this be tested?
1. Create a paragraph with data in %table view
2. Click on TSV/CSV button to export CSV/TSV file

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update?
 Need to have MIT license for Datatables.
* Is there breaking changes for older versions?
No
* Does this needs documentation?
No

### CODE REVIEW

**Comment by ankurmitujjain** [comment]
@adejanovski @corneadoug @bzz @Leemoonsoo
I am done with integrating datatables, have to update a failing testcase...

@corneadoug can you please let me know any example for Chart Pivoted data to verify if this is completed or not...

Thanks
Ankur

**Comment by ankurmitujjain** [comment]
@adejanovski @corneadoug @bzz @Leemoonsoo @felixcheung 

Hello Team,

Can you please review this PR?

Thanks
Ankur

**Comment by corneadoug** [comment]
Thanks, I'll test that out

**Comment by prabhjyotsingh** [comment]
I see following issues:
 - There is a horizontal scrollbar
 - When i scroll, table data goes above header

screen shot 2016-03-09 at 4 22 58 pm

**Comment by ankurmitujjain** [comment]
Thanks for reviewing @prabhjyotsingh 
-I will look into horizontal scroll bar

-However fixed header, is the data tables feature I added, so as when we scroll down data, we always see columns and if we want to sort we can use them without scrolling up... 

this I also listed in PR...

Thanks
Ankur

**Comment by ankurmitujjain** [comment]
Hi @prabhjyotsingh ,

I had updated code as per your comments please review..

Thanks
Ankur

**Comment by prabhjyotsingh** [comment]
Tested it with different size of data. Looks good to me.

**Comment by ankurmitujjain** [comment]
Hi @corneadoug can we merge it ?

**Comment by felixcheung** [comment]
@hyonaldo  @zhongneu  you have both created PRs on this before, are you ok with this approach?

**Comment by corneadoug** [comment]
I found some css problems depending on the paragraph size:
screen shot 2016-03-16 at 2 13 51 pm

Also, when we scroll, the download buttons and search input can't be seen:
screen shot 2016-03-16 at 2 14 10 pm

Btw, I saw that the `Allowing Export to be not only Table based, but also of Chart Pivoted data` task is checked, however I didn't see any button when switching to a graph

**Comment by ankurmitujjain** [comment]
Hi @corneadoug : Sorry I wrongly marked pivot chart data as complete...
Actually I have to remove that feature for now, I will be exploring on how we can export data from graphs as per you suggestion, but for now I would like to keep this feature away from this PR...

However we can always export graph data in table view.

This PR I had planned only for implementing datatable and its export feature....
Please let me know if you are ok with this...

Regarding CSS problem: I will look into it...

Thanks
Ankur

**Comment by jmrr** [comment]
@ankurjainyash any progress with this? I'm experiencing some merge conflicts and master is evolving fast.

@Leemoonsoo I've seen that the export capability is clearly set in the roadmap you sent few weeks ago. What do you think it will be the final approach? Any of #725 , #714 , #6 #89 or #672  or a combination of some/all? I've tested #672 and its data display with search/sort seems more complete.

**Comment by corneadoug** [comment]
I think we would be better off using multiple PRs:
* #761 to replace the table only (if it brings better performances)
* #714 to have a download button available at all time for front data
* #725 to have a download button available at all time for back-end data

The good thing would be that both back-end and front-end data download would use the same UI, and it wouldn't add additional UI elements in the view

**Comment by r-kamath** [comment]
> #761 to replace the table only (if it brings better performances)

What is the max number of rows this lib can support ?

**Comment by ankurmitujjain** [comment]
Can someone help me to push changes?
I am not able to resolve conflicts... So please guide me how I can push my changes to this PR

**Comment by corneadoug** [comment]
@ankurjainyash please don't use merge from master, use rebase instead

**Comment by corneadoug** [comment]
@ankurmitujjain main problem might be that you use you branch master instead of a dedicated branch for this PR

**Comment by ankurmitujjain** [comment]
Thank you @corneadoug , I am still learning git... will use rebase instead of merge... you are right that I am using master instead of branch, which I will take care in next PR, not sure how to achieve same in this PR.

Can you guide me on how to revert R.md related changes?

Thanks
Ankur

**Comment by ankurmitujjain** [comment]
Posting new screenshots for reference...

image

image


image

image

**Comment by ankurmitujjain** [comment]
@r-kamath , I had not tested this, but I believe whatever amount of rows is supported by Zeppelin it will be supporting, on Datatables forum I can see that this plugin can support around 25-30k rows.

**Comment by corneadoug** [comment]
You can do a `git reset --hard lastCommitYouWantInYourHistory` then `git push -f` to rewrite

**Comment by ankurmitujjain** [comment]
Revert Done... Thanks :+1:

**Comment by ankurmitujjain** [comment]
Travis seems to be hanged.. can anyone please look at it...

**Comment by ankurmitujjain** [comment]
Open for review....
Please let me know if any more changes required or features needs to be added...

Thanks
Ankur

**Comment by corneadoug** [comment]
@ankurmitujjain First, the indentation is broken in most files

**Comment by corneadoug** [comment]
The indentation wasn't fixed properly (too many changes)
Try being careful with TABS (we use spaces indentation) and line ending ([a useful guide from github](https://help.github.com/articles/dealing-with-line-endings/#platform-mac))

**Comment by ankurmitujjain** [comment]
phew!!! done indent correction... please review

**Comment by ankurmitujjain** [comment]
@corneadoug I had updated download button placement and now it can also download data for pivot charts.

**Comment by ankurmitujjain** [comment]
Open for review...

**Comment by corneadoug** [comment]
@ankurmitujjain I did leave a comment before

> I think we would be better off using multiple PRs:
* #761 to replace the table only (if it brings better performances)
* #714 to have a download button available at all time for front data
* #725 to have a download button available at all time for back-end data

>The good thing would be that both back-end and front-end data download would use the same UI, and it wouldn't add additional UI elements in the view

Furthermore, I found a few bugs with current implementation:
* We shouldn't be needing an additional scroll bar, nor floatHead
* The CSV buttons, appear after we switch to table only
* the search bar is unnecessary in non-table case
* It doesn't download the pivoted data (doesn't really matter)
* Hard to resize

Considering the plan for export, the next step would be to make this PR adding datatable only:
* Remove download buttons
* Remove search input
* Make the datatable use its own scrollbar (and remove floathead)
* Make sure we can still resize the table

If you want, I can make a PR to your branch that take care of all these points.
Then you can Fix the test (so we are sure you get the contributions during the squash)

**Comment by ankurmitujjain** [comment]
@corneadoug I believe with above suggested changes it seems that you want this PR to replace default table implementation with data-tables only...

So current PR will be without search and download/export buttons. 
My main motive for this PR was to provide download button to download data in csv or tsv format. :P

Also you wanted to remove floatHead dependency which got added by #565  with default datatable scrollbar. 
Note: floatHead is to make table headers fixed, datatable alternative to this is FixedHeader
For scrolling current implementation is using perfect-scrollbar . 
Please correct me if my understanding is wrong :P

After going to datatables site it seems that default scrollbar of datatable needs fix "y" size , after doing a round of testing it seems, when we change paragraph size table will not get updated/redrawn automatically, so we will need some kind of tweak around to get that fixed or basically redraw table.

[Datatable default Scroll](https://datatables.net/examples/basic_init/scroll_xy.html)

I also saw a scroller and fixedheader plugin of datatable which implements scrolling over default scrollbar, but it seems that perfectScrollbar with floatHead is good alternative over those as I feel their UI is better and provide mu more functionality over these plugins...

[floathead](http://mkoryak.github.io/floatThead/datatables/)
[perfect-scrollbar](https://github.com/noraesae/perfect-scrollbar)


For other points..

- the search bar is unnecessary in non-table case
I will remove search box for now, but I was thinking to dynamically update charts on filtered dataset with that searchbox (may be another PR).

- It doesn't download the pivoted data (doesn't really matter)
- Hard to resize
Please share me steps /screenshots for above.

Please feel free to add any kind of changes to my PR, I would welcome good changes, as I like to have features added to zeppelin ASAP instead of thinking for credit/contribution sharing.

**Comment by corneadoug** [comment]
@ankurmitujjain Yes exactly
I know your original goal what for the download, however having in settings allow both server and front-end download, as well as not using extra space on the UI itself.

I will look into floathead a bit, otherwise it could always be improved in a different contribution

**Comment by ankurmitujjain** [comment]
@corneadoug can you please explain what you mean by "in setting" Datatable can also be used to download server side data.

**Comment by corneadoug** [comment]
#725

**Comment by ankurmitujjain** [comment]
@corneadoug , please also review comments from other users... [#6](https://github.com/apache/incubator-zeppelin/pull/6#issuecomment-185086161).

**Comment by fireboy1919** [comment]
See: https://github.com/apache/incubator-zeppelin/pull/822

**Comment by corneadoug** [comment]
@ankurmitujjain I made a PR to your branch https://github.com/ankurmitujjain/incubator-zeppelin/pull/1

**Comment by ankurmitujjain** [comment]
@fireboy1919 is it possible to download output in the form of CSV/TSV?

**Comment by fireboy1919** [comment]
Yes, #822 does that.  It's purely backend, using resource pools.  You might consider it an alternative to using #714.

**Comment by ankurmitujjain** [comment]
ok if thats the case than I believe datatable dont need download functionality which will be handled by #822 . please correct me if I am wrong...

**Comment by ankurmitujjain** [comment]
@fireboy1919 is it possible to download both server side data and front end table data?

**Comment by fireboy1919** [comment]
It's a REST call, so potentially, you could make a client side call to combine the two pieces of information.

But the problem is the same one the backend is solving by being backend - the memory limits imposed by the browser are small compared to what the server can handle.

A smarter approach would probably be to get that kind of thing would be to make a different kind backend component that can transform the data the way that you want it to be transformed.

**Comment by ankurmitujjain** [comment]
So basically you are suggesting to use rest endpoints in download buttons to download server side data....

**Comment by darionyaphet** [comment]
hi @ankurjainyash could support a option about save the CSV/TSV to server ?

**Comment by ankurmitujjain** [comment]
@darionyaphet . If you want to save data as csv on server you can use below code...

[spark-csv](https://github.com/databricks/spark-csv)

     val selectedData = df.select("year", "model")
     selectedData.write
    .format("com.databricks.spark.csv")
    .option("header", "true")
    .save("newcars.csv")

**Comment by darionyaphet** [comment]
@ankurmitujjain 👍

**Comment by ankurmitujjain** [comment]
Updated code to fix testcase, please review

**Comment by corneadoug** [comment]
Merging this

**Comment by felixcheung** [comment]
Could you check out #858? Seems to overlap with this PR
https://github.com/apache/incubator-zeppelin/pull/858

**Comment by corneadoug** [comment]
@felixcheung already saw it and I will check it.
However, while we test + discuss the other PR, there is no reason not to merge this one.
If the other is better, then it can simply replace this one

**Comment by darionyaphet** [comment]
This PR have merge into master branch ? @ankurmitujjain @prabhjyotsingh

**Comment by AhyoungRyu** [comment]
@darionyaphet Yes it does. See here : [d481b56](https://github.com/apache/incubator-zeppelin/commit/d481b56c50d421d513d27adf0f72e516a40be944)

**Pull request closed without merging**
