### PR TITLE
[ZEPPELIN-391] Keyboard shortcut

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR implements keyboard shortcuts for paragraph control.

### What type of PR is it?
Feature

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-391

### How should this be tested?
Try implemented shortcuts

Ctrl + Alt + c  : Cancel run
Ctrl + Alt + d : Remove paragraph
Ctrl + Alt + k : Move paragraph Up
Ctrl + Alt + j : Move paragraph Down
Ctrl + Alt + b : Insert new paragraph below
Ctrl + Alt + o : Toggle output
Ctrl + Alt + e : Toggle editor
Ctrl + Alt + m : Toggle line numbers
Ctrl + Alt + t : Toggle title
Ctrl + Alt + 1~0,-,+ : Paragraph width from 1~12

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Please review

**Comment by minahlee** [comment]
Ctrl + c is commonly used to copy highlighted text to the clipboard so better to change.

**Comment by Leemoonsoo** [comment]
@minahlee You're right. Changed to Ctrl+Alt+c

**Comment by minahlee** [comment]
Ctrl + Alt + k and Ctrl + Alt + E does work on chrome, firefox but not on IE
and Ctrl + Alt + 1~0,-,+ doesn't work on all three browsers

**Comment by Leemoonsoo** [comment]
@minahlee Some more shortcuts are not working in IE. for example Ctrl + n, Ctrl + p.
Do you mind handle shortcuts on IE separately?

**Comment by minahlee** [comment]
@Leemoonsoo sure

**Comment by Leemoonsoo** [comment]
I'll create an issue for shortcut on IE.
Merge if there're no more discussions

**Pull request closed without merging**
