### PR TITLE
ZEPPELIN-148 Notebook scope AngularObject for Angular display system

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Described https://issues.apache.org/jira/browse/ZEPPELIN-148

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Ready to merge

**Comment by Leemoonsoo** [comment]
This PR introduces a two different scope for a angularObject. One localScope(notebook scope) and the other globalScope(interpreter scope). 
Also includes end-to-end test that covers front-end interaction. 
I think this pr will really help make this feature from experimental to beta.

Ready to merge.

**Comment by Leemoonsoo** [comment]
merging if there're no more discussions.

**Comment by stumped2** [comment]
Closing as per https://issues.apache.org/jira/browse/INFRA-9976

**Pull request closed without merging**
