### PR TITLE
[ZEPPELIN-881] Apache Ignite version updated to 1.6

### PR DESCRIPTION
**Pull request by agura**
### What is this PR for?
Apache Ignite 1.6 contains JDBC driver improvements that affect Zeppelin Ignite interpreter user experience.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-881

### CODE REVIEW

**Comment by jongyoul** [comment]
Simple! Great! And I think Ignite JDBC interpreter doesn't have any special thing. How do you think it merges into JDBC interpreter?

**Comment by jongyoul** [comment]
Without the issue above, this PR looks good to me.

**Comment by agura** [comment]
@jongyoul Ignite JDBC interpreter has some specific options, so I need to investigate possibility of usage generic JDBC interpreter. I think the best way is to merge this PR in order to include new drivers in 0.6.0 release.

**Comment by jongyoul** [comment]
@agura I'll thank you if you help merge Ignite JDBC into generic JDBC interpreter.

And about this PR,  it looks good to me. Merging if there's no more discussion.

**Comment by agura** [comment]
Guys, can anybody merge this PR into master branch?

**Comment by jongyoul** [comment]
@agura Hi, one of CI test is failed. Could you please check it?

**Comment by agura** [comment]
@jongyoul How to rerun tests?

**Comment by jongyoul** [comment]
@agura Close and re-open this PR

**Comment by jongyoul** [comment]
@Leemoonsoo Could you please check that failure due to flaky test?

**Comment by bzz** [comment]
@jongyoul first thing to do is to check JIRA `flaky-test` label and see if there is an existing issue for this failure.

The CI failure is not related to the changes and is tracked under https://issues.apache.org/jira/browse/ZEPPELIN-888 I have added this failure to it.

Looks good to me, merging if there is no further discussion

**Comment by agura** [comment]
Thx, guys!

**Comment by jongyoul** [comment]
We also appreciate your contribution!

**Pull request closed without merging**
