### PR TITLE
[ZEPPELIN-309] Redirect to created/cloned notebook page on notebook c…

### PR DESCRIPTION
**Pull request by minahlee**
…reation/clone

This PR enables redirecting to new/cloned notebook pages when create/clone notebook event occurs.

### CODE REVIEW

**Comment by corneadoug** [comment]
I always thought this feature should be done using RestApi so that you don't get any websocket message, but this is somehow working without any problem.

However the event we rely on in this PR is pretty much not needed originally.
`` broadcastNote(newNote);`` should not be called in the case of a createNewNote or CopyNote.

**Comment by Leemoonsoo** [comment]
I think it's okay to use websocket, while this implementation does not adds more complexity (ie. new websocket message) and it's more consistent to keep using websocket for notebook operations in webapp.

**Comment by Leemoonsoo** [comment]
This PR i think need to be rebased. also need to change test to make CI test pass.

**Comment by minahlee** [comment]
@Leemoonsoo Rebased master branch and pushed a fix for CI test.

**Comment by Leemoonsoo** [comment]
Tested, working well. LGTM

**Pull request closed without merging**
