### PR TITLE
[ZEPPELIN-770] Add support for MapR 5.1

### PR DESCRIPTION
**Pull request by cjmatta**
### What is this PR for?
Adding support for MapR 5.1 via profile

### What type of PR is it?
Improvement

### Todos
* [x] - Add MapR 5.1 profile to spark-dependencies/pom.xml
* [x] - Update README.md to reflect new profile.

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-770

### How should this be tested?
Standard build with the -Pmapr51 profile

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by felixcheung** [comment]
Would other components like HBase, Hive work with MapR 5.1?

**Comment by cjmatta** [comment]
@felixcheung As far as I know they work without mapr-sepcific libraries.

**Comment by felixcheung** [comment]
test failure was:
```
+tar zxf spark-1.3.1-bin-hadoop2.3.tgz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

[31;1mThe command "./testing/downloadSpark.sh 1.3.1 2.3" failed 3 times.[0m
```

Spark release download corruption/timeout.

**Comment by felixcheung** [comment]
looks good to me. any more comment?

**Comment by cjmatta** [comment]
No more comments.

**Comment by Leemoonsoo** [comment]
LGTM

**Pull request closed without merging**
