### PR TITLE
ZEPPELIN-518 ] always top fixed column title for table

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
if you express a lot of table Row of Zeppelin, when the Column Title have to scroll down, it is invisible and inconvenient.

So, I have to change the Zeppelin Table Column Title was modified to always display.

### What type of PR is it?
Improvement

### Todos
- [x] implement Fixed Column Title for table
- [x] Browser Test
  - [x] Safari (9.0.2(11601.3.9)
  - [x] Firefox (43.0)
  - [x] Chrome (47.0.2526.106 (64-bit)

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-518
### How should this be tested?
step 1. many rows table print.
           example query)  
``` python
%pyspark
TABLE = "%table Header1\tHeader2\tHeader3\tHeader4\n"
for x in range(1,101):
    TABLE +=  str(x) + ""
    if (x%4) == 0:
        TABLE += "\n"
    else:
        TABLE += "\t"
z.put("table_context", TABLE)
```
``` scala
%spark
println(z.get("table_context"))
```
step 2. Scroll the mouse over the Table.

### Screenshots (if appropriate)
Animated Gif.
fixedtable

### Questions:
How tables are expressed in browsers that do not support this feature? 
 - As before Header mouse scrolling moves along.

### CODE REVIEW

**Comment by astroshim** [comment]
This function is very useful for users!
And the code what you added is the brilliant trick i think. :)
I tested this function at chrome/firefox/explorer and it's working well.

**Comment by cloverhearts** [comment]
@astroshim Thank you for feed back!

**Comment by corneadoug** [comment]
Its better to remove the unused thead content (to free some binding)
You could remove the ``<thead>`` part in the previous table, and add ``margin-top: 31px;`` to it.

**Comment by cloverhearts** [comment]
@corneadoug Thank you for good advice.
I will modify it as you advise.
unused thead -> margin top 31px;

**Comment by cloverhearts** [comment]
It is changed.
Delete Unused thead.
Add margin-top table.

**Pull request closed without merging**
