### PR TITLE
Add/pr teamplate

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
This PR has for goal to set guidelines regarding the **Pull Request** format in order to simplify the reviewer job.
It updates the project guidelines to include the template, and provides an easy click to fill Pull Request tool.

_This PR itself is done using the Pull Request's format_

### What type of PR is it?
Documentation

### Todos
* [x] - Include PR Template in the Project Guidelines
* [x] - Small modifications to the project guidelines
* [x] - Add short bookmarklet to the project guidelines

### Is there a relevant Jira issue?
No

### How should this be tested?
* You can check this PR's Markdown files for the documentation
* You can try the bookmarklet by creating a new bookmarked page and copy/pasting the code as its content, then click on it while creating a PR.

### Screenshots (if appropriate)
The template's bookmarklet in action:

fillpr

### Questions:
* Does the licenses files need update? **No**
* Is there breaking changes for older versions? **No**
* Does this needs documentation? **No, it is documentation**

### CODE REVIEW

**Comment by elbamos** [comment]
This is a really good template.  

Two questions:
1.  Do other open source projects find this level of formality necessary?  I'm not saying its a bad idea.  I just think whenever we have an issue, the first place we look should be to the experience of other projects. 

2.  Does it make sense to have a template for use *by the reviewer*?  I've seen a lot of "looks good to me" written so quickly after a PR is made, there's no way the reviewer could have compiled it, let alone tested it.  (I don't think this actually is an issue on other projects.)  So I'm wondering if it would be a good idea to ask that reviews give some indication of the nature of the review?

**Comment by corneadoug** [comment]
1. I don't have a lot of Open Source projects example that I can post right now, but it is quite usual for projects to have their own Issue Template or PR Template. I think it's even more important in an open source project since it gets contribution from a lot of people with different backgrounds.
A few examples that focus mainly on issue templates:
* https://github.com/docker/docker/blob/master/CONTRIBUTING.md
* https://github.com/atom/atom/blob/master/CONTRIBUTING.md
* https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

2. We documented the Review process and what terminology we use.
But yes, we could probably extend it to a _Tested, LGTM_ when it was tested and not just reviewed.
I wouldn't go as far as making a template for that. As long as the wording we use is defined and documented.

**Comment by r-kamath** [comment]
@corneadoug can you also add PR status in readme ?
`[Issue Stats](http://issuestats.com/github/apache/incubator-zeppelin)`

should look like this in the output
[Issue Stats](http://issuestats.com/github/apache/incubator-zeppelin)

Thanks

**Comment by r-kamath** [comment]
:+1: for bookmarklet

**Comment by corneadoug** [comment]
@r-kamath what would be the used of that badge?

**Comment by r-kamath** [comment]
@corneadoug similar to build status this badge is useful for checking the pr status

**Comment by Leemoonsoo** [comment]
Looks good to me. Tested bookmarklet works really well.


FYI, According to issuestat.com that @r-kamath has mentions,

Time distribution of pr close in apache zeppelin is look like
image

while other well known projects like Apache spark

image

and Apache flink

image
.

**Comment by corneadoug** [comment]
Then, Merging if there is no more discussions

**Pull request closed without merging**
