### PR TITLE
Cron UI fix and css cleanup

### PR DESCRIPTION
**Pull request by r-kamath**
- add spacing between links in presets
- remove inline css and fix alignment

Before
screen shot 2015-12-03 at 2 02 13 pm
screen shot 2015-12-03 at 2 46 27 pm

<hr />
After
screen shot 2015-12-03 at 2 01 30 pm
screen shot 2015-12-03 at 2 48 17 pm

### CODE REVIEW

**Comment by swkimme** [comment]
LGTM!

2015년 12월 3일 (목) 오후 6:19, Renjith Kamath <notifications@github.com>님이 작성:

**Comment by corneadoug** [comment]
Could you also add a bit more spacing between the Cron expresion and its error message?

**Comment by r-kamath** [comment]
@corneadoug currently it is 2px. will update to 5px

**Comment by r-kamath** [comment]
@corneadoug  87c21cd
screen shot 2015-12-03 at 3 08 57 pm

**Comment by prabhjyotsingh** [comment]
:+1:  LGTM

**Comment by corneadoug** [comment]
Its better thanks.
Ready For Merge

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
