### PR TITLE
[MINOR] fixed a logic to find issue number from title

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Changed the regex to find a issue number from title. This doesn't change any code about Zeppelin, but this will effect helper script for committers

### What type of PR is it?
[Bug Fix]

### Todos
* [x] - Fixed the bug

### What is the Jira issue?
N/A

### How should this be tested?
```
>>> import re
>>> re.findall("ZEPPELIN-[0-9]{3,4}", "ZEPPELIN-123")
['ZEPPELIN-123']
>>> re.findall("ZEPPELIN-[0-9]{4,5}", "ZEPPELIN-123")
[]
>>> re.findall("ZEPPELIN-[0-9]{3,4,5}", "ZEPPELIN-123")
[]
>>> re.findall("ZEPPELIN-[0-9]{3}", "ZEPPELIN-123")
['ZEPPELIN-123']
>>> re.findall("ZEPPELIN-[0-9]{3,5}", "ZEPPELIN-123")
['ZEPPELIN-123']
>>> re.findall("ZEPPELIN-[0-9]{4,5}", "ZEPPELIN-123")
[]
>>> re.findall("ZEPPELIN-[0-9]{3,5}", "ZEPPELIN-123")
['ZEPPELIN-123']
```

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
Looks good to me.

May be in PR description it's better to mention that it's not Zeppelin modification but a helper script for PR merge.

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by jongyoul** [comment]
Merging if there's no more discussion.

**Comment by prabhjyotsingh** [comment]
LGTM

**Pull request closed without merging**
