### PR TITLE
Send back message with note data on create and clone

### PR DESCRIPTION
**Pull request by vmakhaev**
We use web-socket api for creating and cloning notes from our servers. To know noteId of created or cloned note, we need some response message. I propose sending NOTE message to client on creating/cloning note.

There could be other ways to reach it. For example, we can send newId and note for creation an id, name, newId for cloning. If newId is not exists, we generate it on server.

Another way will be to create separate api for this, to not mix this with front-end api. It could be REST or smth.

### CODE REVIEW

**Comment by corneadoug** [comment]
Hi @vmakhaev ,
Can you explain what you try to achieve in this PR?
The title and description are telling different things, also the current description of this PR is what is already happening in Zeppelin.

If you have an improvement/feature in mind and a use-case as example, it could help us guide you

**Comment by vmakhaev** [comment]
The problem is to know id of just created Note (or just cloned Note).

In our case, we store metadata (Note ids and names) in our databases and create/clone Notes with websocket api. You can create Note with whatever name you like, but id will be generated in Zeppelin and will not be return somehow.
At the moment the only option is to get list of notes before creating one and after creating, make diff and find new just created Note with it's id.

Hope it makes it more clear.

**Comment by eranwitkon** [comment]
I don't know what was the original intent for separating the API between socket API and REST API but to me socket API are more internal and less descriptive then REST\JSON API.
If we see a need for people to interact from external application with Zeppelin server we should provide them with a REST API and keep it stable as much as possible. 
If needed I can do it for the above services.

**Comment by vmakhaev** [comment]
Yes, please. CRUD and clone will be enough for the beginning. If you need anything from me, let me know.

**Comment by nberserk** [comment]
@eranwitkon i also interested to design/implement that service.

**Comment by eranwitkon** [comment]
@nberserk No problem, it wasn't my intention to hijack this PR.
Can you open a JIRA ticket for this and we will start the work from it.
Also, please advise on what is the best way to do it together...

**Pull request closed without merging**
