### PR TITLE
Hotfix - does not working notebook filter on navibar.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
It doesn't working the notebook filter on navibar.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-873

### Screenshots (if appropriate)
- before 
image

- after
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by minahlee** [comment]
@astroshim Seems like folder structure notebook is broken. Could you take a look?

Attaching screenshot
**Master**
screen shot 2016-05-24 at 4 46 57 pm

**PR#912**
screen shot 2016-05-24 at 4 48 49 pm

**Comment by astroshim** [comment]
@minahlee Thank you for review and finding the problem. I'll take a look this.

**Comment by astroshim** [comment]
@minahlee I fixed the problem. Can you review?

**Comment by bzz** [comment]
CI failure is not related and is due to spark download failure :\ 

Could you plz create a JIRA issue for that with label `flaky-build` ?

**Comment by astroshim** [comment]
@bzz Okay. I'll make one.

**Comment by astroshim** [comment]
@bzz I couldn't find the reason of build failure so I just retrigger CI.

**Comment by minahlee** [comment]
@astroshim Thanks for the contribution. One feedback from me is that it would be awesome if we can filter subdirectory names in nav bar like main page does:
screen shot 2016-05-25 at 11 02 33 pm

This PR only can filter top-level directory name, so if user types b it won't show 0/b/c notebook.
We can leave it as a future work if it is too much.

**Comment by astroshim** [comment]
@minahlee Yes, you're right. It would be better supporting the filter subdirectory names.
How about creating new PR for filtering subdirectory names?

**Comment by minahlee** [comment]
@astroshim sounds good :)

**Comment by bzz** [comment]
Looks good to me.
@astroshim can you please link the JIRA issue here as well?

**Comment by astroshim** [comment]
@bzz I made issue(https://issues.apache.org/jira/browse/ZEPPELIN-886).

**Comment by bzz** [comment]
@astroshim thanks! I think there might be fix for it just merged to master - could you please rebase this branch and see if that resolves the issue?

**Comment by astroshim** [comment]
@bzz I rebased.

**Comment by bzz** [comment]
That CI issue is gone, current failure is due to networking issues on Spark download =\

**Comment by minahlee** [comment]
@astroshim Did you remove tutorial notebook on purpose? If not, can you revert the last commit?

**Comment by astroshim** [comment]
@minahlee It's my mistake. I reverted.

**Pull request closed without merging**
