### PR TITLE
[ZEPPELIN-382] Add Documentation for Cassandra interpreter in the doc…

### PR DESCRIPTION
**Pull request by doanduyhai**
Linked **[JIRA]**

[JIRA]: https://issues.apache.org/jira/browse/ZEPPELIN-382?jql=project%20%3D%20ZEPPELIN

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I think docs/_site directory shouldn't be included

**Comment by doanduyhai** [comment]
You're right, my bad, fixing it

**Comment by doanduyhai** [comment]
Done

**Comment by Leemoonsoo** [comment]
Thanks! LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions.

**Pull request closed without merging**
