### PR TITLE
ZEPPELIN-424 Cancel paragraph in pending status

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-424

Cancel paragraph in pending status.
By removing job from waiting queue and set status ABORT.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Ready to merge

**Comment by prabhjyotsingh** [comment]
Aborting a pending status paragraph clears the output of paragraph, but earlier it used to retain it.

Otherwise looks good, and a really useful feature.

output cleared

**Comment by Leemoonsoo** [comment]
@prabhjyotsingh Thanks, let me try to make it keep the output.

**Comment by Leemoonsoo** [comment]
Updated to keep output on cancel.

**Comment by corneadoug** [comment]
Tested, good.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by khalidhuseynov** [comment]
thanks for improving this feature, LGTM

**Pull request closed without merging**
