### PR TITLE
[ZEPPELIN-666] Change location of notebook authorization information.

### PR DESCRIPTION
**Pull request by prasadwagle**
### What is this PR for?
Currently, notebook authorization information is stored in the note file (note.json). The purpose of this PR is to store the authorization information in notebook-authorization.json in the conf directory. There is no change to the user experience.

The long-term goal is to make NotebookAuthorization an interface with implementation to store the authorization information with Shiro.

### What type of PR is it?
Improvement

### Todos
* [x] - Code review

### What is the Jira issue?
[ZEPPELIN-666](https://issues.apache.org/jira/browse/ZEPPELIN-666)

### How should this be tested?
1. Enable Basic Auth Security by changing conf/shiro.ini.
1. Create a note. By default all operations are allowed by any authenticated user.
1. Update readers, writers and owners by clicking on the lock icon in the top right area.
1. Check if users can or cannot perform operations according to the permissions.
1. Check if notebook-authorization.json has correct authorization information.

### Screenshots (if appropriate)
Not applicable.

### Questions:
* Does the licenses files need update?   No
* Is there breaking changes for older versions?   No
* Does this needs documentation?   No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thank you for the contribution. I tested and working well.
One thing i found is, NotebookAuthorization.removeNote() is never called. which i think supposed to be called on note removal.

**Comment by Leemoonsoo** [comment]
Could you re-trigger CI and see it's passing?

**Comment by Leemoonsoo** [comment]
@prasadwagle Thanks for the contribution. LGTM

**Comment by prasadwagle** [comment]
Thanks @Leemoonsoo for the review.

**Pull request closed without merging**
