### PR TITLE
Replace standard alert and confirm with BootstrapDialog

### PR DESCRIPTION
**Pull request by r-kamath**
Before
screen shot 2015-12-01 at 4 56 45 pm

<hr />

After
screen shot 2015-12-01 at 4 57 27 pm

### CODE REVIEW

**Comment by r-kamath** [comment]
I was waiting for CI to pass. Ready for review

**Comment by prabhjyotsingh** [comment]
LGTM, look better than default alerts/confirm box.

**Comment by corneadoug** [comment]
I prefer the browser alert to this one.
The title box is quite useless here

**Comment by r-kamath** [comment]
@corneadoug we can remove the title box if necessary. Even in the standard alert/confirm there is nothing in the title box. IMHO the standard ones are not considered as good UX

**Comment by corneadoug** [comment]
We can always change the style later.
Could you please update the license for BootStrapDialog here:
https://github.com/apache/incubator-zeppelin/blob/b5e2e62f239d6b1b625add16405e3a302e8ff060/zeppelin-distribution/src/bin_license/LICENSE

**Comment by corneadoug** [comment]
Thanks, LGTM

**Comment by swkimme** [comment]
Cool! LGTM

2015년 12월 9일 (수) 오후 5:44, CORNEAU Damien <notifications@github.com>님이 작성:

**Comment by Leemoonsoo** [comment]
Tested and LGTM.
Merging it into master.

**Comment by gauravkumar37** [comment]
Sorry to barge in a closed bug.
Neither the cancel nor the OK button has focus on them. Would be nice to have either pre-focussed.

**Comment by r-kamath** [comment]
> Neither the cancel nor the OK button has focus on them. Would be nice to have either one pre-focussed.
@gauravkumar37 thanks for the feedback. I've created a new PR (#532) to address this issue. Will focus OK by default and enable Esc key for cancel popup. PR is currently WIP.

**Comment by gauravkumar37** [comment]
Thanks @r-kamath, will check that PR out.

**Pull request closed without merging**
