### PR TITLE
[ZEPPELIN-51] Download link and release note to the first release

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Vote for 0.5.0-incubating release has passed in general@ incubator mailing list ([here](http://mail-archives.apache.org/mod_mbox/incubator-general/201507.mbox/%3CCALf24sZkjGv9s5%3DMU1U97%3Dj-WdsQsH4VkznUA31xsQ2wFDMqRA%40mail.gmail.com%3E)'s vote result).
This PR trying to update download page and add release note on website before the release announcement.

I have listed contributors since 0.4.0 (it was out side of Apache incubation) in release note. Please let me know if there're contributions i missed.

### CODE REVIEW

**Comment by jongyoul** [comment]
Congrat!!

**Comment by felixcheung** [comment]
+1

**Comment by galleon** [comment]
Congrats all!!

**Comment by bzz** [comment]
Congratulations, and looks awesome to me! Let's merge

**Pull request closed without merging**
