### PR TITLE
Update modules prerequisites

### PR DESCRIPTION
**Pull request by romi-totango**
Need to install libfontconfig as well

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks!  Looks good to me

**Comment by felixcheung** [comment]
looks good

**Comment by corneadoug** [comment]
Would be good to know why this is a prerequisite, and for which OS

**Comment by Leemoonsoo** [comment]
@corneadoug at line 29, there're description that this is example for ubuntu.
Merging if there're no more discussions.

**Comment by romi-totango** [comment]
It's for Ubuntu (or any based on it, i'm using Mint)

Without it, you'd get this error:

[INFO] Running "karma:unit" (karma) task
[INFO] INFO [karma]: Karma v0.12.37 server started at http://localhost:9002/
[INFO] INFO [launcher]: Starting browser PhantomJS
[INFO] ERROR [launcher]: Cannot start PhantomJS

And you can see their resolution (which worked for me)
https://github.com/karma-runner/karma-phantomjs-launcher/issues/31#issuecomment-49564925

**Pull request closed without merging**
