### PR TITLE
ZEPPELIN-145 Upgrade Flink version to 0.9.0

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-145

Upgrade flink version to 0.9.0

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I have changed implementation to use FlinkILoop. but i'm getting an exception ..

```
val text = env.fromElements("To be, or not to be")

val counts = text.flatMap { _.toLowerCase.split("\\W+") }.
    map { (_, 1) }.
    groupBy(0).
    sum(1)

val wc = counts.collect
--------------------------------------------------------------------------------------------------------
text: org.apache.flink.api.scala.DataSet[String] = org.apache.flink.api.scala.DataSet@63d817c0
counts: org.apache.flink.api.scala.AggregateDataSet[(String, Int)] = org.apache.flink.api.scala.AggregateDataSet@7fcca542
java.lang.IllegalAccessError: tried to access field org.apache.flink.api.java.RemoteEnvironment.host from class org.apache.flink.api.java.ScalaShellRemoteEnvironment
	at org.apache.flink.api.java.ScalaShellRemoteEnvironment.execute(ScalaShellRemoteEnvironment.java:65)
	at org.apache.flink.api.java.ExecutionEnvironment.execute(ExecutionEnvironment.java:798)
	at org.apache.flink.api.scala.ExecutionEnvironment.execute(ExecutionEnvironment.scala:582)
	at org.apache.flink.api.scala.DataSet.collect(DataSet.scala:542)
	at .<init>(<console>:21)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at org.apache.zeppelin.flink.FlinkInterpreter.interpret(FlinkInterpreter.java:251)
	at org.apache.zeppelin.flink.FlinkInterpreter.interpret(FlinkInterpreter.java:230)
	at org.apache.zeppelin.interpreter.ClassloaderInterpreter.interpret(ClassloaderInterpreter.java:57)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:93)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:277)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:170)
	at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aljoscha** [comment]
Hi,
did you also correctly update the Flink version in the cluster and everywhere else? This seems like a version mismatch, the field RemoteEnvironment.host was private in Flink before version 0.9.0 but now it is protected and should be accessible by ScalaShellRemoteEnvironment (which is a subclass of RemoteEnvironment).

**Comment by Leemoonsoo** [comment]
@aljoscha Thanks for the help. I think i made some mistake now it's working without error.

Ready to merge.

**Comment by stumped2** [comment]
Closing as per https://issues.apache.org/jira/browse/INFRA-9976

**Pull request closed without merging**
