### PR TITLE
Return empty file list instead of throwing error when dependency artifact is empty

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
This PR returns empty list of dependency files instead of throwing error when dependency artifact input form in interpreter setting is empty.

### What type of PR is it?
Bug Fix

### Is there a relevant Jira issue?
No. The bug is reported through comment in #673 

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by FRosner** [comment]
Hi @minahlee I am not in the position to build zeppelin right now. I can test it over the weekend, if this is fine for you.

**Comment by minahlee** [comment]
@FRosner Sure take your time and thank you for keeping your eyes on it :)

**Comment by Leemoonsoo** [comment]
Changes looks good to me.

**Comment by felixcheung** [comment]
looks good

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
