### PR TITLE
ZEPPELIN-284

### PR DESCRIPTION
**Pull request by corneadoug**
Set run notebook button as disables instead of hiding it (when note is running)

### CODE REVIEW

**Comment by felixcheung** [comment]
looks good

**Comment by corneadoug** [comment]
Forgot the screenshot,
change is not obvious with the color, but click is disabled
screen shot 2015-09-07 at 6 34 51 pm

**Comment by khalidhuseynov** [comment]
+1

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
LGTM
This also resolves the error that was coming in console "Uncaught TypeError: Cannot set property 'isOpen' of null".

**Pull request closed without merging**
