### PR TITLE
Pull request merge tool

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Since apache/incubator-zeppelin is a mirror, we can not simply click merge button for pull request.
Here's pullrequest merge tool, i modified little bit for Zeppelin, based on Spark's one.

### CODE REVIEW

**Comment by corneadoug** [comment]
Is there some options to pass also? Or does everybody has to configure its own?
I see that JIRA_USERNAME and JIRA_PASSWORD for example.
Can you make a quick HOW TO USE?

**Comment by jongyoul** [comment]
This looks like the modified version of spark_merge_pr.py, isn't it? I survey several merging tool for ASF. Do you try to get Mesos' one? https://github.com/apache/mesos/blob/master/support/apply-review.sh I think it's really clear to read code. How about you? Spark's one looks a little bit complicated.

**Comment by anthonycorbacho** [comment]
I like more the mesos `apply-review.sh`

**Comment by Leemoonsoo** [comment]
Right, it's modification of spark's one. 
And thanks for the feedback, but I still prefer to Spark's one over mesos's. The reasons are

* Spark's one comments all authors in pull requests when pull requests has commits from more than two contributors while mesos's one does not.
* Spark's one summarize all commits with author for the reference, while mesos's one is not.
* Mesos's one creates link to review board, which Zeppelin development community is not using it right now.

**Comment by jongyoul** [comment]
Yes, some are rights. Mesos' one doesn't support multiple author, but I think It's rare case. And in case you choose github for merging source, Mesos's doesn't create any reviewboard link whether Zeppelin use it or not. If you need to support mutiple authors, Spark's one would be better.

**Comment by Leemoonsoo** [comment]
@jongyoul Thanks for correction.

@corneadoug 
To use this script, minimum requirements are 

1. you should inside of Zeppelin source directory (or setup ZEPPELIN_HOME env variable)
2. add remote repository https://github.com/apache/incubator-zeppelin.git with name 'apache-github' and fetch it (you can use your favorite name instead of 'apache-github' with PR_REMOTE_NAME env variable)
3. add remote repository https://git-wip-us.apache.org/repos/asf/incubator-zeppelin with name 'apache' and fetch it (you can use your favorite name instead of 'apache' with PUSH_REMOTE_NAME env variable)

You can optionally setup your JIRA account by setting up JIRA_USERNAME, JIRA_PASSWORD env variable. 

and just run the script. script will ask question what you want to do.

**Comment by bzz** [comment]
@Leemoonsoo thank you very much for the tutorial!

As we can always switch, why not we try Spark one first and see? If that does not work for us, let's then try mesos one.

So my suggestion would be to merge this and move on.

BTW I presume each committee could use even his own tool of choice if it follows the process (i.e make reviews-before-commit in GH PRs and not a reviewboard)

**Comment by Leemoonsoo** [comment]
Like @bzz suggested, I think we can first try spark's one and see how it goes. @anthonycorbacho @jongyoul, is it okay for you guys?

**Comment by jongyoul** [comment]
:+1: @Leemoonsoo

**Comment by anthonycorbacho** [comment]
yep

**Comment by Leemoonsoo** [comment]
Thanks. I'm merging it.

**Pull request closed without merging**
