### PR TITLE
ZEPPELIN-445 Improve documentation menu

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-445

This PR improve menu of documentation.

Before
image

After
image

image

image

image

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
How Cool !!!

**Comment by bzz** [comment]
Tested, menu structure looks really great! 

May be I'm confusing something but in **local build** I can see

screen shot 2015-11-22 at 18 09 19

While **current website** looks like

screen shot 2015-11-22 at 18 09 38

Am I doing something wrong or do we want to lose Jumbotrone with video link as well as other menus, like "Apache", Download, Community?

A nit probably, but if some HTML ninja could help with 
 - vertical alignment of the version label in header with other menus
 - color\behavior of the triangles on the dropdowns (white by default, blue when clicked and point up)

that would make things a bit more polished.

**Comment by Leemoonsoo** [comment]
With ZEPPELIN-412, website is now maintained in gh-pages branch. /docs dir in master branch is only taking care of documentation for  individual version.

**Comment by jeffsteinmetz** [comment]
We could also reference the Vagrant virtual machine in this pr under Quickstart or More:   https://github.com/apache/incubator-zeppelin/pull/460

**Comment by felixcheung** [comment]
cool!

**Comment by Leemoonsoo** [comment]
@alex Changed the caret(triangles) color. 

Could't do 'vertical alignment of the version label in header with other menus', while it looks bit more weird when i trying it. I think it would be better someone who have better expertise in design handle this.

Now menu looks like
image

Ready to merge.

**Comment by corneadoug** [comment]
@Leemoonsoo Create an issue for the vertical align, and I will fix it

**Comment by Leemoonsoo** [comment]
@corneadoug Thanks. I have created issue https://issues.apache.org/jira/browse/ZEPPELIN-435
Then, I'm merging this PR.

**Pull request closed without merging**
