### PR TITLE
ZEPPELIN-176: fixing nav-bar for mobile and tabs

### PR DESCRIPTION
**Pull request by Madhuka**
Here is screen shoot of with issue and after fixing the issue.
screenshot from 2015-07-20 19_23_56

### CODE REVIEW

**Comment by corneadoug** [comment]
Could you also remove those 2 black lines?
And add margin on the left of connected

**Comment by Madhuka** [comment]
Here is changes and new look of zeppelin in mobile device.
@corneadoug: Both changes are done. 

fix-nav-bar

**Comment by corneadoug** [comment]
I guess this works as fix for now.
We never really worked on the mobile friendly version of zeppelin

+1 for merge

**Comment by Madhuka** [comment]
+1

**Comment by Leemoonsoo** [comment]
LGTM. Thanks @Madhuka for the Fix. I'm merging it.

**Pull request closed without merging**
