### PR TITLE
Fix for ZEPPELIN-478

### PR DESCRIPTION
**Pull request by Karuppayya**
Steps to repro the issue
The following is in case of FIFO scheduler
1.Run a  para(say para1-> %sh sleep 100). The status of the para is "RUNNING".
 A new last para(say para2) is created
2.Now run some thing from para2.(eg: %sh ls )(para1 should be "RUNNING")
Expected: The status of para2 should be "PENDING"
Current: The status of para2 is "READY"

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I have tested and it works really well.
Thanks for the nice description about the problem and good fix.

Looks good to me.

**Comment by Karuppayya** [comment]
Can we merge this, if there is no concerns?

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by corneadoug** [comment]
Its Merged (However the Mirror update seems slow today)

**Comment by Leemoonsoo** [comment]
@corneadoug In this case, you can resolve the problem by file an issue to INFRA (e.g. https://issues.apache.org/jira/browse/INFRA-9974)

**Comment by corneadoug** [comment]
@Leemoonsoo thank you, just created https://issues.apache.org/jira/browse/INFRA-10912

**Pull request closed without merging**
