### PR TITLE
[ZEPPELIN-835]Don't persist authentication info into note.json

### PR DESCRIPTION
**Pull request by mwkang**
### What is this PR for?
Don't persist authentication info into note.json

### What type of PR is it?
Bug Fix

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-835

### How should this be tested?
unit test

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@mwkang Thanks for the fix. It looks good. Do you mind re-trigger the CI?

**Comment by mwkang** [comment]
Of course. I close the PR and re-open to re-trigger the ci.

**Comment by mwkang** [comment]
@Leemoonsoo Part of Ci are failed. Because.. 
````
[ERROR] Failed to execute goal on project zeppelin-zrinterpreter: Could not resolve dependencies for project org.apache.zeppelin:zeppelin-zrinterpreter:jar:0.6.0-incubating-SNAPSHOT: Could not transfer artifact org.apache.spark:spark-core_2.10:jar:1.4.1 from/to central (http://repo.maven.apache.org/maven2): GET request of: org/apache/spark/spark-core_2.10/1.4.1/spark-core_2.10-1.4.1.jar from central failed: Connection reset -> [Help 1]
```
Is it Okay? I'm not sure it is not related this PR, isn't it?

**Comment by Leemoonsoo** [comment]
[The first CI profile](https://travis-ci.org/apache/incubator-zeppelin/jobs/132442409) runs this test and it is passing. Other CI failure is unrelated to this change.

LGTM

**Comment by bzz** [comment]
Guys, in effort to improve build stability, would it be reasonable to have some kind of agreement that in case of such build failures - we create a JIRA issues first, tag like flaky-build, link logs of failing build and only then proceed \w contributions that stumbled up on such issues?

That would help PMC a great deal to identify common infrastructure problems and focus on fixing them.

**Comment by mwkang** [comment]
@bzz I think I don't understand 100%. So I want to more clearly what you are saying.
If I am impolite, I am so sorry.
Is the meaning I make a JIRA issue about failing CI?

**Comment by bzz** [comment]
@mwkang no problem! 
yes, JIRA issue for failing CI with label `flaky-build` (even if it does not block this PR) would help us improving the CI

**Comment by mwkang** [comment]
@bzz Thanks for your comment. It is really helpful. and now I understand 100%! :smile:

**Comment by mwkang** [comment]
I made 2 issue for failing CI.
[ZEPPELIN-876](https://issues.apache.org/jira/browse/ZEPPELIN-876), [ZEPPELIN-877](https://issues.apache.org/jira/browse/ZEPPELIN-877)

**Comment by felixcheung** [comment]
thanks, looks like Selenium tests have been busted by a merged code change. thanks for opening ZEPPELIN-876.

**Comment by corneadoug** [comment]
@mwkang Could you rebase this PR please?

**Comment by mwkang** [comment]
While I rebase this PR, I found this issue was been resolved [AuthenticationInfo in master].
So I closed PR.

[AuthenticationInfo in master]: https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Paragraph.java#L53

**Comment by mwkang** [comment]
Related PR: https://github.com/apache/incubator-zeppelin/pull/860
Related Issue: https://issues.apache.org/jira/browse/ZEPPELIN-828

**Comment by corneadoug** [comment]
@Leemoonsoo Can we close this JIRA issue then? https://issues.apache.org/jira/browse/ZEPPELIN-835

**Comment by mwkang** [comment]
Oh.. I closed JIRA issue.
I am so sorry that I act at my discretion.

**Comment by corneadoug** [comment]
@mwkang It's fine, we can always reopen it if necessary. Just wanted @Leemoonsoo go to close it since he was the one to report it

**Pull request closed without merging**
