### PR TITLE
[HOTFIX] Code convention

### PR DESCRIPTION
**Pull request by jongyoul**
- Fixed style guide.
- Followed by #20

### CODE REVIEW

**Comment by jongyoul** [comment]
@anthonycorbacho I made it. Review this PR, please.

**Comment by anthonycorbacho** [comment]
looks better but every variable expansion must follow this variation:` ""$conf_dir""` became ` ""${conf_dir}""` for example

**Comment by jongyoul** [comment]
I hope this would be a final fix. :)

**Comment by anthonycorbacho** [comment]
look good now.
thanks

**Pull request closed without merging**
