### PR TITLE
ZEPPELIN-155 Handle port number 0

### PR DESCRIPTION
**Pull request by Leemoonsoo**
issue described https://issues.apache.org/jira/browse/ZEPPELIN-155.
Allow websocket bind to port 0

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Ready to merge.

**Comment by Leemoonsoo** [comment]
Merging if there's no more discussions.

**Comment by ashwinshankar77** [comment]
Hi @Leemoonsoo ,
Patch works perfect ! thanks. Minor comment : 
1. the logs prints out 0, when we set websocket to 0 instead of actual port
15/07/06 18:19:45 INFO socket.NotebookServer: Create zeppelin websocket on 0.0.0.0:0
2. When we start zeppelin using zeppelin-daemon.sh, would it make sense to print out "http://host:port"
that the browser should connect to ?

Thanks,
Ashwin

**Comment by Leemoonsoo** [comment]
@ashwinshankar77 
Thanks for the feedback.
I pushed a commit to print port number correctly.

To make zeppelin-daemon.sh print address, it'll need more work. it should aware system assigned port and ssl configuration. Do you mind creating a separate issue for it?

**Comment by ashwinshankar77** [comment]
@Leemoonsoo 
Thanks ! Patch looks good to me. I created separate jira for printing address : https://issues.apache.org/jira/browse/ZEPPELIN-159

**Pull request closed without merging**
