### PR TITLE
Don't set Dirty state if text is same as last save

### PR DESCRIPTION
**Pull request by corneadoug**
Previous Behavior
masterbranch

With this PR
prbranch

### CODE REVIEW

**Comment by felixcheung** [comment]
looks good

**Comment by prabhjyotsingh** [comment]
When I run a paragraph, it gets saved but $scope.originalText still has old value.

Steps to reproduce:
 1) on a new notebook, type "HelloWorld" in a new paragraph
 2) run the above
 3) paragraph gets saved
 4) now try changing it to "HelloWorld1" and then back to "HelloWorld" 
 5) now try changing it back to "" (blank)

**Comment by corneadoug** [comment]
Thanks, I just updated the value when we run and update the paragraph

**Comment by prabhjyotsingh** [comment]
Tested, LGTM.

**Comment by r-kamath** [comment]
:+1:

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by felixcheung** [comment]
is there performance implication with these copies btw? I for one have paragraphs that have 100s of lines of code...

**Comment by corneadoug** [comment]
It wouldnt be a big performance issue.

**Pull request closed without merging**
