### PR TITLE
Drag to resize paragraph

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
dragresizeparagraph

### CODE REVIEW

**Comment by corneadoug** [comment]
We already have one to resize the height of the paragraph result.
So there might be some conflicts

**Comment by prabhjyotsingh** [comment]
Yes, I've noticed it, but it only shows up when there is a table/graph in view. Should I try merge it here, or this there?

**Comment by corneadoug** [comment]
It's not too shocking to have both resize handles, however the resize graph height doesn't work anymore.
You might also want to rebase. (since we merged some graph width fix)
Maybe having one handle for both height and width could be better

**Comment by prabhjyotsingh** [comment]
Have updated this PR, instead of having multiple resize handles. Merged it into one. 

drag to resize paragraph

**Comment by Leemoonsoo** [comment]
I have tested and it works really well. Thanks @prabhjyotsingh for really improvement.

One thing is, resize drag handle is shown in report mode. But i think it more sense to hide there. What do you think?

**Comment by corneadoug** [comment]
Could you also un-commit the note.json?

**Comment by corneadoug** [comment]
Found plenty of issues:

1) Scrollbar when code line is too long on notebook refresh/load
screen shot 2015-12-15 at 3 29 52 pm

2) Resize to a size too small error
screen shot 2015-12-15 at 3 30 37 pm
screen shot 2015-12-15 at 3 30 53 pm

2) opposite effect resize
resize

**Comment by prabhjyotsingh** [comment]
Thanks for the review and finding bugs;
1) Scrollbar when code line is too long on notebook refresh/load  - Fixed
2) Resize to a size too small error - Fixed by having a minimum height, tried to use jQuery resizable minHeight but that cannot be used in out use case. Hence, fixed with following

    var adjustHeight = elem.height() - extraHeight;
    if (adjustHeight < 100) {
       scope.updateWidth({height: 100, width: Math.ceil(elem.width() / colStep)});
    } else {
       scope.updateWidth({height: adjustHeight, width: Math.ceil(elem.width() / colStep)});
    }
    
3) opposite effect resize - With above two this also got fixed.

**Comment by prabhjyotsingh** [comment]
Does this looks ok ?

**Comment by corneadoug** [comment]
@prabhjyotsingh I will test it again tomorrow, sorry for the delay

**Comment by corneadoug** [comment]
Tested, the bug are gone.
There is now a minimum size on the output.
However, would it be possible to apply the same limit to the dragging?
Right now, it looks like you can resize below that minimum height:
screen shot 2015-12-20 at 11 37 52 am

**Comment by prabhjyotsingh** [comment]
Thanks @corneadoug for the feedback and a providing me with a lot of test cases.
Have merged this with the latest master, which seems to solve the bug for me. 
Let me know if this works.

**Comment by Leemoonsoo** [comment]
I've found weird behaviors.
I can make paragraph width larger than the notebook width and resize proxy is displayed in correctly.
Please take a look following screenshot
paragraph_width

**Comment by Leemoonsoo** [comment]
Tested and LGTM.
Thanks @prabhjyotsingh for really useful feature

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by corneadoug** [comment]
Re-tested, +1

**Pull request closed without merging**
