### PR TITLE
Zeppelin-523 ] Table Header fixed and scrolling bug fixes.

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
For Table, reimplemented, scrolling, deleting a bug in the Table Header, Scrolling area expressed bugs have been fixed.

### What type of PR is it?
Bug Fix

### Todos
- [x] \(Re-modification\) always top fixed column title for table
- [x] table scrolling bug fixed. out of area scroll 
       https://github.com/apache/incubator-zeppelin/pull/556
- [x] After the re-run, remove the scroll bar
- [x] License Infomation
  - [x] record the license information of jquery.floatThead.
- [x] Browser Test
  - [x] Safari (9.0.2(11601.3.9)
  - [x] Firefox (43.0)
  - [x] Chrome (47.0.2526.106 (64-bit)

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-523
### How should this be tested?
Step 1. create table on zeppelin
           example query) 
``` python
%pyspark
TABLE = "%table Header1\tHeader2\n"
for x in range(1,51):
    #TABLE +=  "scroll";
    TABLE +=  str(x);
    if (x%2) == 0:
        TABLE += "\n"
    else:
        TABLE += "\t"
z.put("table_context", TABLE)

```
``` scala
println(z.get("table_context"))
```

Step 2. 
Scroll the mouse over the Table.

Step 3.
re Run Paragraph.

Step 4.
Scroll the mouse over the Table.

#### Before
before

#### After
bug_fix_table_sc

### Questions:
You are using an external source?
\- I used jquery.floatThead (MIT) Libraries.
  It helps to secure the Table Header.
Why did this problem occur?
\- ref. https://github.com/noraesae/perfect-scrollbar#how-to-use perfect scrollbar library. 
  height calculation miss.
Why it has created a new PR?
\- A problem with a private Git Repository to my mistakes.
  Please previous PR, see the following URL.
  https://github.com/apache/incubator-zeppelin/pull/556
In the ScreenShot, it seems to have changed color table. What changed things?
\- no. It's Animated Gif color problems.
  Changes that do not exist.

### CODE REVIEW

**Comment by cloverhearts** [comment]
Additional modifications
according to a floating Thead, Paragraph Option Fixes a problem.

#### before
before

#### after
after

This bug fixes to the table was completed.
I would like to discuss and review.

**Comment by Leemoonsoo** [comment]
Looks good to me.
Merge if there're no more discussions.

**Comment by corneadoug** [comment]
@Leemoonsoo 
I'd like to take a closer look, especially since it's adding a new library

**Comment by cloverhearts** [comment]
I'm sympathetic to your comments.
Note that I am so attached to a cord and library link.
I hope this helps to determine.

https://github.com/noraesae/perfect-scrollbar/issues/273
https://github.com/noraesae/perfect-scrollbar/issues/256
http://mkoryak.github.io/floatThead/examples/perfect-scrollbar/

**Comment by Leemoonsoo** [comment]
@corneadoug Sure, please take a look closer.

**Comment by mkoryak** [comment]
author of floatThead here. let me know if i can be of assistance (without installing anything). :cat2:

**Comment by corneadoug** [comment]
I tried it after rebasing with master (because of the resize that was just merged).
Everything seems to work fine, however I found a bug when we switch from table to graph:
screen shot 2015-12-30 at 11 09 05 am

**Comment by cloverhearts** [comment]
@corneadoug 
Thank you good feedback.
I will review that section again as your opinion.

**Comment by cloverhearts** [comment]
@corneadoug 

tablebug_fix_after

I have completed bug fixes.
Thank you for feedback.

**Comment by corneadoug** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
LGTM and merge into master

**Pull request closed without merging**
