### PR TITLE
ZEPPELIN-486 Paragraph menu does not disappear on selecting width

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
Paragraph menu does not disappear on selecting/altering width, and disappears on click of width icon/span.

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Also found this wired bug on resize

Before:
before


After:
after

**Comment by prabhjyotsingh** [comment]
Ready for review.

**Comment by jongyoul** [comment]
It looks good to me but I'm not a expert of this area. @corneadoug could you please review this?

**Comment by corneadoug** [comment]
@jongyoul Yeah, I'm already reviewing most of the front PR right now

**Comment by jongyoul** [comment]
@corneadoug Thanks for the quick reply. :-)

**Comment by corneadoug** [comment]
I couldn't reproduce the _wired bug on resize_, i did saw it a few times though.
Would love to have a scenario to reproduce and attest the fix.
Otherwise, It's good to merge.

**Comment by prabhjyotsingh** [comment]
Sure, @corneadoug steps to reproduce;
- query something that returns table/graph.
- change the height to rendered graph/chart/table
- now without refreshing or updating paragraph query, change the width of paragraph (say from 12 to 6, or 6 to 12)
here you will notice that paragraph width is decreased/increased but width of graph is same as it was earlier.

**Comment by corneadoug** [comment]
Checked.
Merging if there is no more discussions

**Pull request closed without merging**
