### PR TITLE
Remove author tag

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Remove author tag from java doc since Zeppelin doesn't encourage to use it

### What type of PR is it?
Documentation

### Is there a relevant Jira issue?
N

### Questions:
* Does the licenses files need update? N
* Is there breaking changes for older versions? N
* Does this needs documentation? N

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
+1 (non-binding)

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by jongyoul** [comment]
LGTM

**Comment by dlukyanov** [comment]
@minahlee , could the class comment `created by` be used instead of @author tag in zeppelin sources?

**Comment by minahlee** [comment]
@dlukyanov The reason I removed the author is not `@author` tag itself but because of ownership of the code. All code contributed to this repository is owned by Zeppelin community not by specific author.

I found one [jira issue](https://issues.apache.org/jira/browse/TAVERNA-897) from Apache Taverna community which listed out discussion around it. Hope this help you to understand why we don't leave footprint in the code.

**Pull request closed without merging**
