### PR TITLE
move noteName method from main to navbar.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
Notebook list doesn't show when you reload(F5) the zeppelin web page not in home.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-863

### How should this be tested?
Outline the steps to test the PR here.

### before
bug

### after
fix

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
It works well. Thanks for fixing this 👍

**Comment by prabhjyotsingh** [comment]
Good catch, LGTM

**Comment by cloverhearts** [comment]
LGTM. good fix

**Comment by r-kamath** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Tested and LGTM.
Merge it into master branch!

**Pull request closed without merging**
