### PR TITLE
[ZEPPELIN-319]wait an additional .5 seconds, if assertion will fail

### PR DESCRIPTION
**Pull request by RPCMoritz**
This test failed randomly during a build. To make sure this is not due to timing issues, we can optionally wait an additional .5 seconds.
This is a band-aid around bad design, but I'm pragmatically trying to get the build to be more stable. This should also help determine if there is an actual (randomly striking) issue in the underlying procedure being tested, by making the test more reliable.

Please review, and if you can come up with a better designed test (and avoid waiting for threads to finish in a fixed time interval) we should discuss it here or in the issue.

### CODE REVIEW

**Comment by corneadoug** [comment]
@Leemoonsoo any feedback on this PR?

**Comment by Leemoonsoo** [comment]
Purpose of `Thread.sleep(500)` at line 119 is waiting for the job finish.
So, how about replace it with 
```
    while (!job.isTerminated()) {
      Thread.sleep(100);
    }
```
?

**Comment by RPCMoritz** [comment]
Well, we do need some kind of way out of that loop, to get to the failure - stage. Infinite looping won't work.

**Comment by Leemoonsoo** [comment]
Then, you can break the loop, like
```
    // wait for job finish, maximum 10 seconds
    for (int i = 0 ; i < 100 && !job.isTerminated(); i++) {
      Thread.sleep(100);
    }
```

**Comment by RPCMoritz** [comment]
That's more reasonable,  I'll amend the commit.

**Comment by RPCMoritz** [comment]
Looks like npm-dependency-resolution broke the build - how can I trigger a re-check? (Ironic, that this happens, while I'm trying to stabilize the build ^^;)

**Comment by corneadoug** [comment]
@RPCMoritz you can close and reopen this PR to trigger the CI again

**Comment by RPCMoritz** [comment]
@corneadoug thanks!

**Comment by Leemoonsoo** [comment]
Thanks! LGTM

**Pull request closed without merging**
