### PR TITLE
ZEPPELIN-74 Change interpreter selection from %[Name] to %[Group].[Name]

### PR DESCRIPTION
**Pull request by Leemoonsoo**
This PR implements https://issues.apache.org/jira/browse/ZEPPELIN-74.

Plus, changing existing interpreter's name

spark.spark -> spark.scala
spark.pyspark -> spark.py
hive.hive -> hive.hql
tajo.tajo -> tajo.tql

All changes are backward compatible except for spark.pyspark -> spark.py.
User need either %spark.py, %py (when Spark is selected first) instead of %pyspark.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
all test are passed but travis is somehow goes to after_failure lifecycle.

**Comment by bzz** [comment]
Can you try 'close and re-open' this PR - this is a 'hack' to re-trigger the CI and see if that is reproducible?

**Comment by bzz** [comment]
Still failing :(

BTW shoud [docs update](http://zeppelin.incubator.apache.org/docs/development/writingzeppelininterpreter.html) be part of this PR or do you want to hande it in a sepate one?

**Comment by Leemoonsoo** [comment]
I'll handle it in separate PR.

**Comment by Leemoonsoo** [comment]
I have reverted interpreter name PysparkInterpreter name from py to pyspark. and SparkInterpreter from scala -> spark. So there will be no backward compatibility issue.

About renaming spark.pyspark->spark.py, spark.spark->spark.scala, I think i can still create separate issue and discuss there.

Now tests are passing. Ready to merge.

**Comment by Leemoonsoo** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
