### PR TITLE
[Zeppelin 329] Notebook copied in file system level should be reflected in notebook list

### PR DESCRIPTION
**Pull request by minahlee**
This PR enables Zeppelin to reflect addition/changes/removal of `{ZEPPELIN_NOTEBOOK_DIR}/{notebookId}/note.json` on the file system without restarting ZeppelinServer.

To activate this functionality, user needs to set `ZEPPELIN_NOTEBOOK_GET_FROM_REPO` to be true in conf/zeppelin-env.sh.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Nice improvement. Could you choose little more intuitive name than `ZEPPELIN_NOTEBOOK_GET_FROM_REPO` ?

**Comment by minahlee** [comment]
@Leemoonsoo @khalidhuseynov ready for review

**Comment by anthonycorbacho** [comment]
why do you need to activate this functionality? shouldnt be a expected behavior?

**Comment by minahlee** [comment]
Beacause PR will load notebooks from storage everytime client requests notebook list, which can be burden to Zeppelin with a bunch of notebooks. So I wanted to make as less effect as possible on current behavior. Would it be better to activate it by default?

**Comment by anthonycorbacho** [comment]
so why not using a watcher? like if someone drop a notebook in the notebook dir, you update the list of notebook.

**Comment by Leemoonsoo** [comment]
I think activating this function by default will brings some IO overhead in some cases. (large number of big notebooks). As @minahlee mentioned, it's better to keep it de-activated by default. When the implementation becomes more efficient it can be activated by default. That could be future work.
So, Looks good to me.

**Comment by Leemoonsoo** [comment]
Merging if there're no more discussions

**Pull request closed without merging**
