### PR TITLE
ZEPPELIN-413: Fix ability to link a single paragraph

### PR DESCRIPTION
**Pull request by bzz**
Fixes [ZEPPELIN-413](https://issues.apache.org/jira/browse/ZEPPELIN-413)

Relevant changes in `setNoteContent ` handler

Test plan:
 - Link a paragraph from Zeppelin Tutorial i.e [/#/notebook/2A94M5J1Z/paragraph/20150210-015302_1492795503?asIframe](http://localhost:9000/#/notebook/2A94M5J1Z/paragraph/20150210-015302_1492795503?asIframe)

\cc @minahlee @corneadoug for a review

### CODE REVIEW

**Comment by corneadoug** [comment]
Tried it, looks good

**Comment by minahlee** [comment]
Tested and LGTM

**Comment by r-kamath** [comment]
:+1: LGTM

**Comment by bzz** [comment]
Thank you for the reviews!

**Comment by prabhjyotsingh** [comment]
Works well, LGTM.

**Pull request closed without merging**
