### PR TITLE
ZEPPELIN-235: jscs in zeppelin-web

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
ZEPPELIN-235: jscs in zeppelin-web
used following for .jscsrc

{
  "preset": "google",
  "maximumLineLength": {
    "value": 120,
    "allExcept": [ "comments", "regex"]
  }
}

### CODE REVIEW

**Comment by corneadoug** [comment]
I guess there might be plenty of errors, do you need help cleaning them?

**Comment by prabhjyotsingh** [comment]
@corneadoug Intellij Idea fixed most if not all of the issues. However if build fails, or if there are errors in merging this to master, this will surly need help.

**Comment by corneadoug** [comment]
We might have to work on the configuration for indentation.

### Example:

#### current formatting in this branch
```
angular.module('zeppelinWebApp').controller('ParagraphCtrl',
  function($scope, $rootScope, $route, $window, $element, $routeParams, $location, $timeout, $compile,
           websocketMsgSrv) {
```
Gives a 4 spaces prefix indent for the function code


#### One line formatting
```
angular.module('zeppelinWebApp').controller('ParagraphCtrl', function($scope, $rootScope, $route, $window, $element, $routeParams, $location, $timeout, $compile, websocketMsgSrv) {
```
Gives a 2 spaces prefix indent for the function code but obviously more than 120 characters line.

#### Super line formatting
```
angular
  .module('zeppelinWebApp')
  .controller('ParagraphCtrl',
              function($scope, $rootScope, $route, $window, $element, $routeParams, $location, $timeout, $compile,
                        websocketMsgSrv) {
```
or
```
angular
  .module('zeppelinWebApp')
  .controller('ParagraphCtrl',
              function($scope,
                        $rootScope,
                        $route,
                        $window,
                        $element,
                        $routeParams,
                        $location,
                        $timeout,
                        $compile,
                        websocketMsgSrv) {
```
Then I have jscs errors asking for a 16 spaces prefix indent for the function code.


In the end, I'm not sure which indenting is the best.

**Comment by prabhjyotsingh** [comment]
Sure giving a 4 spaces prefix indent for the function code, makes code look slightly more cleaner. 

I thought of 120 characters in line, because in my view this should fit in most of the monitors. If not 120 characters what can be the right value?

But what I would prefer is using one of the standard template from the following list
https://github.com/jscs-dev/node-jscs/tree/master/presets

**Comment by corneadoug** [comment]
Our base is the google guideline, so using its prefix sounds good.
But I'm having some trouble when re-indenting the code in my text editor.
Especially when it comes to breaking down some lines.
So I think I'm gonna have to check how to do this more in the google rules, and see if it needs a few modifications. Maybe also checkout the other presets at the same time

**Comment by prabhjyotsingh** [comment]
Well I'm using Intellij Idea, and on pressing Control + Shift + A spawns up this menu, which does the job. I'm sure similar option should be available in other IDEs as well.

screen shot 2015-08-24 at 9 47 24 pm

If the plugin is not already installed here is how to:
https://www.jetbrains.com/idea/help/using-javascript-code-quality-tools.html#installJSCS

**Comment by prabhjyotsingh** [comment]
Can we start something basic, and then keep improvising it on the need basis?
Also, I thought  "preset": "google" will take care of  a lot of things.

**Comment by prabhjyotsingh** [comment]
Closing this, will open up again with fixed changes

**Pull request closed without merging**
