### PR TITLE
ZEPPELIN-404 Certain project dependencies are pulled from 3rd parties repos instead of ASF or public Maven 

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-404

This PR removes / move 3rd party repository into profile.
cloudera repo is disabled by default and can be activated by -Pvendor-repo

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Typo fixed. It is for convenience for user who trying to build Zeppelin with 3rd party artifacts (cdh, etc).
I think that's why Spark, Flink etc also keep 3rd party repository in their pom.xml file.

**Comment by c0s** [comment]
Thanks for the explanation! Good to go with the fix +!

**Comment by felixcheung** [comment]
looks good

**Comment by bzz** [comment]
looks good to me

**Pull request closed without merging**
