### PR TITLE
[MINOR] Remove redundant logic of JDBC Interpreter

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Removing redundant codes and expanding features for passing extra properties into JDBC driver

### What type of PR is it?
[Bug Fix | Improvement]

### Todos
* [x] - Removed logic

### What is the Jira issue?
* MINOR issue

### How should this be tested?
Just passed additional information into your JDBC 

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by jongyoul** [comment]
@wfhartford I think it's okay to satisfy your concern. Could you please review it?

**Comment by wfhartford** [comment]
Awesome, thanks. That looks great.

**Comment by jongyoul** [comment]
This PR is a very trivial. Merging if there's no more discussion.

**Comment by prabhjyotsingh** [comment]
Tested, LGTM!

**Comment by cloverhearts** [comment]
LGTM! +1

**Pull request closed without merging**
