### PR TITLE
ZEPPELIN-692 Add setting to set s3 endpoint

### PR DESCRIPTION
**Pull request by vgmartinez**
### What is this PR for?
Add setting to set endpoint in S3 storage.
[S3 Endpoint](http://docs.aws.amazon.com/es_es/general/latest/gr/rande.html#s3_region) 

### What type of PR is it?
Improvement

### What is the Jira issue?
* [ZEPPELIN-692](https://issues.apache.org/jira/browse/ZEPPELIN-692)

### How should this be tested?
set endpoint for your bucket in zeppelin-site.xml 

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Could you add new configuration to [docs/install/install.md](https://github.com/apache/incubator-zeppelin/blob/master/docs/install/install.md#zeppelin-configuration) and [conf/zeppelin-env.sh.template](https://github.com/apache/incubator-zeppelin/blob/master/conf/zeppelin-env.sh.template#L33), too?

**Comment by vgmartinez** [comment]
@Leemoonsoo of course I had forgotten...;)

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
