### PR TITLE
Bump nvd3 version

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
This PR is to remove the Errors message of nvd3 in the console.
It Bumps

### What type of PR is it?
Bug Fix

### Todos
* [x] - Bump NVD3 version to fix messages
* [x] - Update scatter chart tooltip to match new format

### Is there a relevant Jira issue?
No

### How should this be tested?
You can open the console, switch between a graph and table, then resize the paragraph

### Screenshots (if appropriate)
screen shot 2015-12-30 at 11 10 39 am

### Questions:
* Does the licenses files need update? Yes
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by corneadoug** [comment]
READY

@Leemoonsoo, could you tell me what is that license folder: https://github.com/apache/incubator-zeppelin/tree/master/zeppelin-distribution/src/bin_license/licenses ?
Should I update it also?

**Comment by prabhjyotsingh** [comment]
:+1:  for moving out from 1.5-beta to 1.7.1.

Few questions:
 - Any reason why 1.7.1 not 1.8.1
 - can we use .min.js and .min.css in  [Line113](https://github.com/corneadoug/incubator-zeppelin/blob/fix/nvd3ErrorMsg/zeppelin-web/src/index.html#L113)  and [Line40](https://github.com/corneadoug/incubator-zeppelin/blob/fix/nvd3ErrorMsg/zeppelin-web/src/index.html#L40) respectively

Otherwise tested, works well, LGTM

**Comment by Leemoonsoo** [comment]
@corneadoug we can use the license folder when license requires copy of the license. You may at least update name of the file zeppelin-distribution/src/bin_license/licenses/LICENSE-nvd3.js-1.1.15-beta

**Comment by corneadoug** [comment]
@prabhjyotsingh 
1) 1.8.1 has a new tooltip system, and I found some bug while trying it
2) This is auto-generated by bower, also all libraries are minified at build time so its not needed

**Comment by corneadoug** [comment]
License is updated, Good to go

**Comment by prabhjyotsingh** [comment]
@corneadoug  totally missed about grunt minification tasks. Also, can you take a look at https://github.com/corneadoug/incubator-zeppelin/pull/3

**Comment by prabhjyotsingh** [comment]
LGTM :)

**Comment by Leemoonsoo** [comment]
LGTM

**Pull request closed without merging**
