### PR TITLE
Fix restapi testcase

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
To fix REST API testcase.

### What type of PR is it?
Bug Fix

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-536

### How should this be tested?
Run testcase.

### Questions:
* Does the licenses files need update? n
* Is there breaking changes for older versions? n
* Does this needs documentation? n

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Looks good to me. Could you trigger Travis build by close - reopen?

**Comment by astroshim** [comment]
@HeartSaVioR Thank you for your reply.

**Comment by astroshim** [comment]
The build error is not related to this issue. But it occurred again!
```
...
15/12/28 04:23:52 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
15/12/28 04:24:07 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
15/12/28 04:24:22 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources


Your test run exceeded 120 minutes. 

One possible solution is to split up your test run.
```

**Comment by Leemoonsoo** [comment]
LGTM and merge if there're no more discussions

**Pull request closed without merging**
