### PR TITLE
ZEPPELIN-569 - website update for release 0.5.6-incubating 

### PR DESCRIPTION
**Pull request by bzz**
Vote for release 0.5.6-incubating has passed.

Dev list vote result : [dev@zeppelin.i.a.o](http://markmail.org/thread/i54nabcx5wa2kt5j)
IPMC vote result: [general@i.a.o](http://markmail.org/thread/xczosjtzjxpne262)

This is a last step of release process, before the public announcement - updating website with release notes and new version information.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Looks good to me

**Comment by felixcheung** [comment]
LGTM.

**Comment by jongyoul** [comment]
LGTM

**Comment by HeartSaVioR** [comment]
LGTM

**Comment by bzz** [comment]
Guys, thanks for the prompt reviews! 
Merging if there is no more discussion.

**Pull request closed without merging**
