### PR TITLE
[ZEPPELIN-7] Support yarn without SPARK_YARN_JAR

### PR DESCRIPTION
**Pull request by jongyoul**
- Removed SPARK_YARN_JAR dependencies

### CODE REVIEW

**Comment by jongyoul** [comment]
@Leemoonsoo This PR is related #3 . I removed SPARK_YARN_JAR dependencies. After you merge #3 , I'll fix the docs.

**Comment by jongyoul** [comment]
I've rebased this from current master to update `README.md`. @Leemoonsoo Review this PR, please.

**Comment by Leemoonsoo** [comment]
Thanks for contribution. Let me test this code.

**Comment by jongyoul** [comment]
I've rebased this because README.md was changed.

**Comment by Leemoonsoo** [comment]
Tested and looks good to me :+1:

**Pull request closed without merging**
