### PR TITLE
Fix ZEPPELIN-151

### PR DESCRIPTION
**Pull request by corneadoug**
Move the Font Imports to another file so it is not in the middle of minified css

### CODE REVIEW

**Comment by corneadoug** [comment]
CI Is Green, ready to merge

**Comment by Leemoonsoo** [comment]
Could you verify it? i tried this branch and layout looks broken

**Comment by corneadoug** [comment]
Do you have a screenshot for me to see what is the problem?

**Comment by Leemoonsoo** [comment]
Here's a screenshot
image

**Comment by corneadoug** [comment]
Thanks for checking it. Seems like new cssmin version I set when I was trying to fix the bug originally doesn't work properly with current usemin version.

I reversed the bower version of cssmin

**Comment by Leemoonsoo** [comment]
Still, font is unchanged. Could you check again?

**Comment by corneadoug** [comment]
Did you do a Bower cache clean and delete bower_components?

**Comment by Leemoonsoo** [comment]
After cleaning cache, i see the correct font. Thanks! i'm merging it.

**Comment by stumped2** [comment]
Closing as per https://issues.apache.org/jira/browse/INFRA-9976

**Pull request closed without merging**
