### PR TITLE
Add tooltip for notes reload button

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Notebook reload icon is not intuitive so add tooltip to it.

### What type of PR is it?
Improvement

### Screenshots (if appropriate)
screen shot 2016-04-04 at 4 23 10 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by sejunra** [comment]
looks great.

**Comment by bzz** [comment]
CI failure looks not relevant for this code, but @minahlee could you please create an issue for that in JIRA and label it with `flaky-test` and attach a link to raw log results?

Looks great to me!

**Comment by r-kamath** [comment]
LGTM :+1:

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by felixcheung** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
LGTM merging it into master.

**Pull request closed without merging**
