### PR TITLE
ZEPPELIN-307: Added a new empty paragraph at the end of the note

### PR DESCRIPTION
**Pull request by vgmartinez**
Add a new paragraph when the note is autosaved

images

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Change looks good. But can we have an unittest for it before merge?

**Comment by vgmartinez** [comment]
Hi @Leemoonsoo,
I'm not sure but the test should not be used commitParagraph ....? which is exactly what I should do .... I'm a little confused.

**Comment by Leemoonsoo** [comment]
Basically, a unittest that fails without this patch and passes with this patch.

I thought little bit more about this action. Current rule of paragraph creation is

1. automatically adds one after execution of last paragraph.
2. manually inserts between paragraphs.

And this patch changes to

1. automatically adds one, after execution of last paragraph.
2. manually inserts between paragraphs.
3. automatically adds one, after saving non empty last paragraph.


I think it could be confusing, if i see a new paragraph created automatically, while editing the last paragraph. Another strategy, with less confusing(i think) is, 

1. automatically adds one, after execution of last paragraph.
2. manually inserts between paragraphs.
3. automatically adds one, when user starts editing the last paragraph.


I personally prefer the current rule, but what do you guys think?

**Comment by vgmartinez** [comment]
I also prefer the current rule

**Comment by felixcheung** [comment]
Since the auto-save is timer based, I do agree it is confusing to see a new paragraph appearing by itself.
I agree with @Leemoonsoo that the 'add paragraph when editing last' is more predictable and potentially less confusing.

**Comment by felixcheung** [comment]
And sometimes one does not want a new paragraph created automatically

**Pull request closed without merging**
