### PR TITLE
add keyboard shortcut for toggling run paragraph

### PR DESCRIPTION
**Pull request by MikeTYChen**
### What is this PR for?
Added a keyboard shortcut to toggle enable/disable of running a paragraph

### What type of PR is it?
Improvement

### Is there a relevant Jira issue? 
https://issues.apache.org/jira/browse/ZEPPELIN-608

### How should this be tested?
Click in paragraph and press ctrl+alt+s

### Screenshots (if appropriate)
after

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
It's not been merged yet but checkpoint feature is working in progress at https://github.com/apache/incubator-zeppelin/pull/577. How about keep Ctrl-Alt-s for the checkpoint? Ipython/Jupyter also uses 's' for save/checkpoint.

**Comment by MikeTYChen** [comment]
@Leemoonsoo- gotcha. that makes sense. how about ctrl+alt+r? I changed it in the newest update, but open to other shortcut keys too.

**Comment by felixcheung** [comment]
+1 on ctrl-alt-r
btw, should we have these mapping for Mac (doesn't have alt key)

**Comment by Leemoonsoo** [comment]
ctrl+alt+r.
Looks good to me.

on osx, option key works instead of alt key.

**Comment by MikeTYChen** [comment]
yup. on mac option works for alt. Should we have a line on the keyboard-shortcut modal to clarify that alt can be replaced by option on macs?

**Comment by Leemoonsoo** [comment]
Yes, if we have a line for using option key on macs, that definitely would help

**Comment by felixcheung** [comment]
is it possible show different key name in the shortcut list based on the platform the user is on? this could be a separate PR.

Merging this if there is no more discussion.

**Comment by MikeTYChen** [comment]
@felixcheung : good suggestion on the shortcut list. Thanks. I opened a separate PR for it here: https://github.com/apache/incubator-zeppelin/pull/665

**Pull request closed without merging**
