### PR TITLE
[ZEPPELIN-461] fix typos in geode doc

### PR DESCRIPTION
**Pull request by felixcheung**

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Looks good to me

**Comment by r-kamath** [comment]
LGTM :+1:

**Comment by prabhjyotsingh** [comment]
Found some more;
Line 88: creaate - create
 colocated - collocated
Line 113: regionEmploee - regionEmployee
Line 163: Zepplein - Zeppelin
 not sure about parametrization - parameterization

**Comment by jongyoul** [comment]
+1 @prabhjyotsingh

**Comment by felixcheung** [comment]
thanks. I fixed others but I think colocate is fine https://www.google.com/search?q=colocated

**Comment by Leemoonsoo** [comment]
LGTM :+1:

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
