### PR TITLE
Zeppelin-web Spring Cleaning

### PR DESCRIPTION
**Pull request by corneadoug**
After so much time in the Wild Wild West of Internet, It's Time for the Spring Cleaning of Zeppelin-web.
This PR will be taking care of cleaning the code, architecture, cutting code into smaller pieces etc...

* [x] - Change Code Folder Structure to a Folder Tree Style
* [x] - Change original code and compiled code folder names
* [x] - Update Contributing README.md to explain most of changes
* [x] - Organize well the components and app folders

We will do a first merge and handle this part in a different PR:
* [ ] - Replace as much code as possible by their lodash.js counterpart
* [ ] - Cut the code into more smaller components (who said paragraph.js?)
* [ ] - Move Jquery code out of the controllers (by directive when possible or to somewhere else)

Needs to make sure that:
* [x] - #127 is handled

### CODE REVIEW

**Comment by felixcheung** [comment]
where did controllers/notebook.js or controllers/paragraph.js go?

**Comment by corneadoug** [comment]
Didn't update the doc to explain the folder strcture yet.

But now, src is the source folder, and the generated code on build go to dist folder.

For the source code, you will find it organised by module (home.html, home.css, home.controller.js for example) either in the src/app folder or src/components folder.

Src/app is for page related content, and each page is containing its own modules. Src/components is for modules used in different places (navbar for example).

Now you can place files wherever you want in app and components, folders and have as much sub folder as you want, however you will need to register the .js files in index.html

**Comment by felixcheung** [comment]
thanks for the explanation. I saw other files 'moved' but these two were 'deleted' as per git, so just want to check.

**Comment by corneadoug** [comment]
@felixcheung looks like you were right, paragraph.js and notebook.js were not there. Realized that after git clean.

**Comment by felizbear** [comment]
@corneadoug I skimmed through the last three commits. It looks like you did a nice job. Using `controller as` pattern is definitely an improvement. The other thing I have to mention that services are singletons (https://github.com/johnpapa/angular-styleguide#singletons), so you'll be better off returning an object instead of using `this`.
E.g.
```javascript
this.deleteNotebook = function(noteId) {}
this.getNotebookList = function() {}
```
would become
```javascript
return {
  deleteNotebook = function() {},
  getNotebookList = function() {}
}
```

**Comment by corneadoug** [comment]
Yeah, but like your link show, services while being a singleton (just like everything in angular) are usually use as public functions only (transformation functions mainly) and do not hold any variables.

**Comment by felizbear** [comment]
It's okay. I just have an aversion to `this` and try to eliminate it from my code. Up to you.

**Comment by corneadoug** [comment]
This is what the Paragraph Form changes looks like.
Before, The label used to be squashed by the input, and on big screen they would not take 100% width and be under each other

screen shot 2015-06-15 at 3 52 43 pm

**Comment by felizbear** [comment]
Looks good!

**Comment by corneadoug** [comment]
I think I'm gonna Rebase master in this PR, and then it will be good to go.
This is a good base, and already a lot of work has been done here.
We can continue working on cleaning more the code in Other smaller PR.

**Comment by felizbear** [comment]
@corneadoug go for it man!

**Comment by corneadoug** [comment]
@Madhuka Not really. There is only some ng-doc on some controllers, not all (they were generated by yeoman), so it doesn't really document much. Also we don't use ng-doc in our grunt file, so its not even generating documentation out of it.

**Comment by corneadoug** [comment]
Just Rebased it all, Need to verify and modify some previous pull requests now

**Comment by corneadoug** [comment]
This is good for Test and Merge :)

**Comment by felizbear** [comment]
Is it okay that Travis is complaining?

**Comment by corneadoug** [comment]
I forgot to do the mvn verify. It could be the license check failing.
Anyway, I will fix it

**Comment by corneadoug** [comment]
CI is green!

**Comment by felizbear** [comment]
Looks like it's ready for merge!

**Comment by Leemoonsoo** [comment]
LGTM let's merge

**Comment by Madhuka** [comment]
Great, Seems I can start my work on here.

On Thu, Jul 2, 2015 at 9:31 AM, Lee moon soo <notifications@github.com>
wrote:

> LGTM let's merge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-zeppelin/pull/56#issuecomment-117898562>
> .
>



-- 
Cheers,
Madhuka Udantha
http://madhukaudantha.blogspot.com

**Pull request closed without merging**
