### PR TITLE
ZEPPELIN-401 Improve autoscroll

### PR DESCRIPTION
**Pull request by Leemoonsoo**
Addresses https://issues.apache.org/jira/browse/ZEPPELIN-401

This PR improves autoscroll behavior when using keyboard navigation (up/down key)

* When cursor closes to edge of top/bottom of notebook, autoscroll triggers
* Autoscroll will scroll notebook to position cursor to the middle of browser window
* When last paragraph is executed, a new paragraph is inserted after. now notebook autoscrolls to newly inserted paragraph.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Ready to merge

**Comment by corneadoug** [comment]
I will take a look at this PR too then

**Comment by corneadoug** [comment]
Awesome, makes everything smoother.

One bug I found though, Is that the cursor cannot move to a paragraph where the output is hidden.

**Comment by Leemoonsoo** [comment]
@corneadoug Thanks for testing. pushed a commit to address the bug.

**Comment by corneadoug** [comment]
Good For Merge

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by gauravkumar37** [comment]
Thanks for the bug fix.
I noticed that it works great when there is no horizontal scrolling. However, when there is output of paragraphs which extends beyond horizontal screen, it scrolls the window horizontally as well.

**Comment by Leemoonsoo** [comment]
@gauravkumar37 Thanks for sharing a problem. I have created a fix https://github.com/apache/incubator-zeppelin/pull/419

**Pull request closed without merging**
