### PR TITLE
[ZEPPELIN-576] Support Apache Drill Interpreter

### PR DESCRIPTION
**Pull request by malur**
### What is this PR for?
Supports Apache Drill Interpreter

### What type of PR is it?
Improvement, Feature

### Todos
* [ ] - Documentation with Screenshots on how to use the Interpreter

### Is there a relevant Jira issue?
Yes. ZEPPELIN-576

### How should this be tested?
Choose a new Interpreter and provide the required details, necessary to connect to a running Apache Drill Instance. After which you can start firing Queries

### Questions:
* Does the licenses files need update?
**No**

* Is there breaking changes for older versions?
**No**

* Does this needs documentation?
**Yes**

### CODE REVIEW

**Comment by felixcheung** [comment]
Previously we have a contribution for Drill interpreter (PR #110) and it seems we have concluded that it should be on top of a generic JDBC interpreter - what you think about that approach?

In any case, the use of `org.apache.drill.exec` would need to be added to licenses, could you look into that?

**Comment by malur** [comment]
I looked into the Generic JDBC approach. Looks good.
So, 
* We need to use the Generic JDBC Interpreter code & extend that to provide specific properties of Drill?
* I should wait for the pull request #361 to be merged to work on this?

Drill JDBC driver is Apache 2.0 License. Do we still need to add entry in Licenses folder? I can add it. Please confirm.

**Comment by vgmartinez** [comment]
Hi @malur,
I think it's a good idea to wait to be done merge the Generic JDBC and work on that to add support for everything related to JDBC connectors. What do you think...?

**Comment by malur** [comment]
@vgmartinez, that would be right approach. I will wait for the merge to happen.

**Comment by jongyoul** [comment]
@malur Sorry for late reply. In my opinion, JDBCInterpreter can cover this feature. If it's not, please let me know. Otherwise, how about updating docs for using Drill with JDBC? https://github.com/apache/incubator-zeppelin/blob/master/docs/interpreter/hive.md will help you improve docs because the configuration of JDBCInterpreter is based on HiveInterpreter.

**Comment by malur** [comment]
@jongyoul Sure. I will check the latest code with Drill & Update docs, if needed.

**Comment by jongyoul** [comment]
@malur Thanks for positive answer. And could you please close this PR?

**Comment by malur** [comment]
Closing this PR, as generic JDBC provides the needed functionality.

**Comment by tmx11** [comment]
Are you using the psql or hive interpreter for this to work?

Also presumably we need to copy in the drill-jdbc-all-1.1.0.jar or drill-jdbc-1.1.0.jar into the classpath.

Putting the all-jar under zeppelin/lib means the daemon can't start.

If only the other one is under lib you get commons-lang3 errors but when putting this under lib also seems to still not find.

**Comment by jongyoul** [comment]
@tmx11 Hi, could you please those jars under `/interpreters/jdbc/`? I think this would be more general position to use that interpreter. If it still doesn't work, tell me again. Thanks.

**Comment by smartinsightsfromdata** [comment]
@jongyoul @malur  I think the relevance of Apache Drill deserves at the very least a document with a dedicated set of instructions on how to configure a Drill interpreter (i.e. a mini-tutorial).  

At the moment this is missing but it would be great to have it.

**Comment by malur** [comment]
Agreed.
I had this in my list of TODO. Will take some time out over weekend & try to add this information.

**Comment by jongyoul** [comment]
@smartinsightsfromdata @malur I also have a plan to enable customization for specific jdbc driver, for example, completers and dedicated word and so on. Jdbc interpreter will get better.

**Comment by malur** [comment]
Cool.
Meanwhile I have added documentation around using Drill with JDBC Interpreter via PR #718

**Pull request closed without merging**
