### PR TITLE
ZEPPELIN-928: fix flaky ZeppelinIT test for Spark interpreter

### PR DESCRIPTION
**Pull request by bzz**
### What is this PR for?
Fix flaky Integration Test by adding new id to HTML (as of HTML5 it can be [any non-empty string](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute)) and liverage it in tests for simpler XPath statements that pick only 1 candidate.

### TODO
 - [x] fix test
 - [x] update New Interpreter form validation and error message
 
### What type of PR is it?
Bug Fix

### What is the Jira issue?
[ZEPPELIN-928](https://issues.apache.org/jira/browse/ZEPPELIN-928)

### How should this be tested?
CI should pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
CI passes, ready to be merged. 

This should fix CI on #860

**Comment by khalidhuseynov** [comment]
thanks for fixing this flaky test, LGTM

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by cloverhearts** [comment]
LGTM

**Comment by bzz** [comment]
Thank you for prompt reviews!
Merging if there is no more disucssion

**Pull request closed without merging**
