### PR TITLE
ZEPPELIN-294 Enable karma code coverage plugin

### PR DESCRIPTION
**Pull request by r-kamath**
- grunt build generates the coverage report for js in zeppelin-web
- to view the report open `zeppelin-web/reports/coverage/PhantomJS 1.9.8 (Mac OS X 0.0.0)/index.html` in browser

screen shot 2015-09-10 at 12 45 28 pm

### CODE REVIEW

**Comment by corneadoug** [comment]
I wouldn't export the report in the ``dist`` directory since it is not directly related to zeppelin usage.
Maybe ``reports/coverage`` instead. (and have reports folder in .gitignore)

Can you also add in this PR's description a small explanation on how the report is generated, and some explanations or link about how to read that report.

**Comment by r-kamath** [comment]
@corneadoug Thanks for the comment. Updated in 5316b61

**Comment by Leemoonsoo** [comment]
Change looks good to me

**Comment by corneadoug** [comment]
I still would love to know how to read that report, and could be added to our docs

**Comment by r-kamath** [comment]
http://stackoverflow.com/a/26635182

**Comment by r-kamath** [comment]
@corneadoug let me know if I have missed anything here

**Comment by corneadoug** [comment]
@r-kamath I think it is good like that
We can't really use it without us activating coveralls on that repository, but it will be the work of another issue.

**Pull request closed without merging**
