### PR TITLE
ZEPPELIN-305 Do not add jvm memory option when using spark-submit

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-305

When `SPARK_HOME` is defined and `bin/interpreter.sh` is launching interpreter process using spark-`submit` command, Jvm memory option from `bin/interpreter.sh` and from `spark-submit` command conflicts.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Ready to review

**Comment by bzz** [comment]
Looks good to me

**Comment by minahlee** [comment]
LGTM

**Comment by felixcheung** [comment]
looks good

**Pull request closed without merging**
