### PR TITLE
ZEPPELIN-447: removing of redundant "$" in jshintrc

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
Allow only jQuery, so that its always more readable.

### CODE REVIEW

**Comment by corneadoug** [comment]
No jQuery either, only angular.element

**Comment by prabhjyotsingh** [comment]
I was thinking to do that in a separate PR. Can do it here as well. 

What about perfectScrollbar, can I just remove all references of that as well ?

**Comment by corneadoug** [comment]
@prabhjyotsingh if we want to unify it all, better doing it once, and the way it should be (angular.element)
Not sure what you mean by perfectScrollbar, it is used only twice and not as a keyword (and it is needed)

**Comment by prabhjyotsingh** [comment]
Done, replaced jQuery with angular.element.
Please ignore perfectScrollbar thing, got it confused with something else.

**Comment by corneadoug** [comment]
Alright, just tell us when your PR is finished so that we can review/test it

**Comment by prabhjyotsingh** [comment]
Yes, was waiting for travis to complete.
Ready for review.

**Comment by corneadoug** [comment]
I think thats good for merge

**Comment by prabhjyotsingh** [comment]
Thanks for the quick review :smile:

**Comment by r-kamath** [comment]
:+1:

**Comment by Leemoonsoo** [comment]
:+1:

**Comment by corneadoug** [comment]
I will merge if there is no more comments

**Pull request closed without merging**
