### PR TITLE
ZEPPELIN-358: Jetty server is HTTP ERROR 404

### PR DESCRIPTION
**Pull request by mwkang**
[ZEPPELIN-358](https://issues.apache.org/jira/browse/ZEPPELIN-358)
Define local jetty temp directory.
`varName: zeppelin.war.tempdir`
`default varValue: webapps`
Zeppelin create temp directory in `{zeppelin.home}/webapps` when zeppelin server start.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks. I have tested. works nicely and got this log

```
 INFO [2015-12-02 11:06:22,383] ({main} WebInfConfiguration.java[unpack]:478) - Extract jar:file:/zeppelin-0.6.0-incubating-SNAPSHOT/zeppelin-web-0.6.0-incubating-SNAPSHOT.war!/ to /zeppelin-0.6.0-incubating-SNAPSHOT/webapps/webapp
```

Looks good to me.


One minor thing is, do you mind add the environment variable to
https://github.com/apache/incubator-zeppelin/blob/master/conf/zeppelin-env.sh.template#L27

and the property to 
https://github.com/apache/incubator-zeppelin/blob/master/conf/zeppelin-site.xml.template

and update documentation 
https://github.com/apache/incubator-zeppelin/blob/master/docs/install/install.md

**Comment by mwkang** [comment]
Thanks for your review.
I update the documents.

**Comment by mwkang** [comment]
I update the documents.

**Comment by Leemoonsoo** [comment]
Thanks for the contribution.
Looks good to me and merge if there're no more discussions.

**Comment by bzz** [comment]
Looks great to me, merging if there are no other discussions.

**Pull request closed without merging**
