### PR TITLE
[ZEPPELIN-434] Fix website build warning due to depecrated settings

### PR DESCRIPTION
**Pull request by lresende**
pygment has been depecrated in favor of highlighter attribute

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks. It would be more appreciated there is a corresponding issue in JIRA.
It's still okay without creating an issue, but having issue would help people track which version ships this fix and helps this fix included in release note generated by JIRA.

**Comment by lresende** [comment]
@Leemoonsoo I'll create a jira and update this PR

**Comment by lresende** [comment]
@Leemoonsoo , ZEPPELIN-434 created and pr title updated

**Comment by corneadoug** [comment]
Hi @lresende,
This option should be deprecated starting from jekyll 2.0,
however we are using version 1.3 in this doc, so I'm not seeing any warning on my side

**Pull request closed without merging**
