### PR TITLE
ZEPPELIN-16 Some failures from Spark and SparkSql note execution are not reported

### PR DESCRIPTION
**Pull request by RamVenkatesh**
... reported

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM!

**Comment by RamVenkatesh** [comment]
@felixcheung  thank you for the review. If there are no other comments, can we please get this checked in? Many of our users are running into this issue.

**Comment by Leemoonsoo** [comment]
Thanks for the cool fix!
I've tested and LGTM.
merging it.

**Comment by swkimme** [comment]
Awesome!

**Pull request closed without merging**
