### PR TITLE
Fix notebook folder structure name match bug

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Current regex match rule for notebook folder takes not only `/` as delimiter but also `[` and `]`.

### What type of PR is it?
Bug Fix

### How should this be tested?
Try to create notebook that contains `[` or `]` in name and see if the folder structure is correct.

### Screenshots (if appropriate)
With notebook name `/A/B[C]D`
**Before**
screen shot 2016-05-11 at 3 00 42 pm

**After**
screen shot 2016-05-11 at 3 01 31 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the fix. How about add a test case to https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-web/test/spec/factory/notebookList.js#L15 ?

**Comment by minahlee** [comment]
@Leemoonsoo Just added test. Please review

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge it into master if there're no more discussions

**Pull request closed without merging**
