### PR TITLE
[ZEPPELIN-754]Cannot use S3 seoul region (ap-northeast-2)

### PR DESCRIPTION
**Pull request by mwkang**
### What is this PR for?
Update AWS SDK version.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-754

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the patch. Could you also update [zeppelin-distribution/src/bin_license/LICENSE#L3](https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-distribution/src/bin_license/LICENSE#L3) ?

**Comment by mwkang** [comment]
Oh I'm so sorry. I updated the file.

**Comment by Leemoonsoo** [comment]
@mwkang No worries. Thanks for taking care of the license.

I have checked aws-java-sdk-s3:1.10.62 brings no new/changes of transitive dependency.
Single test failure https://travis-ci.org/apache/incubator-zeppelin/jobs/118149866 is irrelevant to this pullrequest.

Looks good to me.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by bzz** [comment]
Somehow CI is failing =\

**Comment by Leemoonsoo** [comment]
@bzz Yes, that seems flaky test.

**Pull request closed without merging**
