### PR TITLE
zeppelin-61: added lens interpreter

### PR DESCRIPTION
**Pull request by praagarw**
Kindly review and let me know if any issues.

Regards,
-Pranav.

### CODE REVIEW

**Comment by sharadag** [comment]
the test case is failing for me.

**Comment by praagarw** [comment]
The pull request for based on 2.1.0-beta-incubating-SNAPSHOT, however this version is no longer available in repo. There are two changes that needs to be done to make it work:
1. set the lens dependency as  2.2.0-beta-incubating-SNAPSHOT
2. Merge the fix for JIRA LENS-549 in lens.

I'll be sending the patch for LENS-549 today. Once its available then I'll fix this patch to point to newer Lens version.

**Comment by praagarw** [comment]
Travis CI logs suggest that the failure is not cause of my changes. Its failing cause of selenium test issue.  

Jun 04, 2015 6:49:27 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
*** RUN ABORTED ***
  java.lang.NoSuchFieldError: INSTANCE
  at org.apache.http.impl.conn.HttpClientConnectionOperator.<init>(HttpClientConnectionOperator.java:75)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:151)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
  at org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnectionManager(HttpClientFactory.java:68)
  at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:54)
  at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:98)
  at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:81)
  at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:93)
  at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [  5.504 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 16.822 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [  7.673 s]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 40.577 s]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  3.564 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  2.877 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  2.715 s]
[INFO] Zeppelin: Hive interpreter ......................... SUCCESS [  3.715 s]
[INFO] Zeppelin: Tajo interpreter ......................... SUCCESS [  3.056 s]
## [INFO] Zeppelin: Lens interpreter ......................... SUCCESS [  7.305 s]
[INFO] Zeppelin: web Application .......................... SUCCESS [ 39.981 s]
[INFO] Zeppelin: Server ................................... FAILURE [  5.331 s]
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by Leemoonsoo** [comment]
Current master branch has some problem with automated test. 
#88 includes fix for the problem.

You can rebase this branch and see if CI passes after #88 is merged.

**Comment by praagarw** [comment]
After rebasing with apache master, I was getting issues in pushing the changes. I then took a easy route and created a new pull request -> https://github.com/apache/incubator-zeppelin/pull/100.

**Pull request closed without merging**
