### PR TITLE
Adding leaflet and data validator - Testing CI

### PR DESCRIPTION
**Pull request by Madhuka**
- [x] Adding leaflet for map
 - [x]  Adding map UI for zeppelin
 - [x] Adding map chart for zeppelin
 - [x] Adding sample tutorial for notebook on map
 - [x] Adding SQL for tutorial
 - [x] Adding data validation 
 - [x] Test Cases

This PR is CI fixing for PR#152 for data validation and adding leaflet map for zeppelin

### CODE REVIEW

**Comment by Madhuka** [comment]
All data validation are added completed. (factories, services, config), Test cases also added
`grunt test` out put.


screenshot from 2015-08-21 23 40 23

**Comment by bzz** [comment]
@Madhuka can you please rebase it on\merge in a latest master?
\cc @corneadoug for the review

**Comment by Madhuka** [comment]
@bzz : we can close this. 
#262 contains the data validation features

**Comment by datagiraffe** [comment]
Map Visualization for Zeppelin would be a great addition!
I've tried the code and ran into several problems.

I don't think it's good to select the lat and lon statically like so:
https://github.com/Madhuka/incubator-zeppelin/blob/milestone05-map/zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js#L866
It would be nice if they were detected automatically. Maybe if there are columns lat, latitude, lon, long or longitude, pick them?

The same goes for the key:
https://github.com/Madhuka/incubator-zeppelin/blob/milestone05-map/zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js#L863
If a key exists twice, it obviously breaks. Key and message are the same though, but I may be interested in the same message at different locations.

There should be a settings drop down like for the other chart types where this can be configured. With the current version, that doesn't seem to work. (Only for me?)

**Pull request closed without merging**
