### PR TITLE
[ZEPPELIN-428] Support Python programmatic access to dynamic form

### PR DESCRIPTION
**Pull request by felixcheung**
https://issues.apache.org/jira/browse/ZEPPELIN-428

This is what it looks like:
image

image

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Working really well.

Looks good to me.

**Comment by Leemoonsoo** [comment]
Merging if there're no more discussions

**Comment by corneadoug** [comment]
Maybe we should also update the documentation so people know they can use it on python

**Comment by felixcheung** [comment]
I agree - in the existing doc the code is in images - should we double those with python version? I'd prefer having text for code - it would be easier to copy/paste to test it out
https://zeppelin.incubator.apache.org/docs/manual/dynamicform.html

**Comment by Leemoonsoo** [comment]
Text one could be better.

**Comment by jongyoul** [comment]
I've tested it. LGTM with adding a tutorial in dynamicform

**Comment by felixcheung** [comment]
added doc and rebased

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by jongyoul** [comment]
LGTM

**Pull request closed without merging**
