### PR TITLE
ZEPPELIN-412 Documentation based on Zeppelin version

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-412

To provide documentation based on Zeppelin version, like Spark, Flink project does, it need to separate documentations from website.

* docs will be kept in Zeppelin main source tree and being built and published under 'docs' menu on website with specific version number.
* website will be kept in gh-pages branch and provides menu for multiple version of docs.

This PR removes unnecessary pages, which is provided by website. (for example download page)

This is the screenshot after applying this PR

image

image

### CODE REVIEW

**Comment by jongyoul** [comment]
Basically, this approach looks good to show docs, but could you tell me how to show the information of versions in the website? For example, if I want to see the old versions docs, how can I do?

**Comment by Leemoonsoo** [comment]
Website is now stored in gh-pages branch. It's got link to all version of docs.  See #431.

So you'll see all versions in the website. To generate docs locally, you'll need to switch soure code branch/tag to the version you want.

**Comment by corneadoug** [comment]
So, doesn't master need to have a folder with docs for each version already generated since #431 links are pointing on them ?

**Comment by Leemoonsoo** [comment]
When Zeppelin releases a new version, documentation will be build from master brach under 'docs' directory and deployed into https://svn.apache.org/repos/asf/incubator/zeppelin/docs/[version].

And website (gh-pages branch) will add a link to the new version of documentation.

So 'docs' in master branch will only need documentation for the current version.

**Comment by corneadoug** [comment]
I see, so to update previous versions doc, we will have to make a PR on that tag, and it will be directly deployed on the svn

**Comment by Leemoonsoo** [comment]
Merging #430 and #431 if there're no more discussions

**Pull request closed without merging**
