### PR TITLE
ZEPPELIN-220 Correct multiple directives error in navbar.html

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by corneadoug** [comment]
Can you tell me more about that multiple directive error?

**Comment by fjini** [comment]
I'm running the master version on Chrome version 44.0.2403.155.
On the first page, there's an error like this. I think this is a simple mistake.
--------------------------------------------------------------------------------------
Error: [$compile:multidir] Multiple directives [dropdown, dropdown] asking for 'dropdown' controller on: <li class="dropdown" dropdown="">
http://errors.angularjs.org/1.3.8/$compile/multidir?p0=dropdown&p1=dropdown&p2='dropdown'ontroller&p3=%3Cli%class%3D%dropdown%22%20dropdown%3D%22%22%3E
    at http://192.168.56.2:7070/bower_components/angular/angular.js:63:12
    at assertNoDuplicate (http://192.168.56.2:7070/bower_components/angular/angular.js:7990:15)
    at applyDirectivesToNode (http://192.168.56.2:7070/bower_components/angular/angular.js:7339:11)
    at compileNodes (http://192.168.56.2:7070/bower_components/angular/angular.js:6997:15)
    at compileNodes (http://192.168.56.2:7070/bower_components/angular/angular.js:7009:15)
    at compileNodes (http://192.168.56.2:7070/bower_components/angular/angular.js:7009:15)
    at compileNodes (http://192.168.56.2:7070/bower_components/angular/angular.js:7009:15)
    at compileNodes (http://192.168.56.2:7070/bower_components/angular/angular.js:7009:15)
    at compile (http://192.168.56.2:7070/bower_components/angular/angular.js:6904:15)
    at link (http://192.168.56.2:7070/bower_components/angular/angular.js:23785:9)(anonymous function) @ angular.js:11594

**Comment by Leemoonsoo** [comment]
I'm also using Chrome 44.0.2403.155 and can't see such an error. Is error supposed to be displayed in Javascript Console?

**Comment by fjini** [comment]
Yes. I'm testing after the patch 'https://github.com/apache/incubator-zeppelin/pull/212.patch'.

err-msg

**Comment by anthonycorbacho** [comment]
I bet its because of that line https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-web/bower.json#L14

moon, i guess you can try something like
`rm -rf bower_components && bower cache clean && bower install`

**Comment by corneadoug** [comment]
Never saw that error, maybe you don't have the right version of some bower dependencies

**Comment by Leemoonsoo** [comment]
@anthonycorbacho I did `rm -rf bower_components && bower cache clean && bower install`. still can not see the error.

**Comment by corneadoug** [comment]
@Leemoonsoo I thing it actually was targeted to @gliptak

**Pull request closed without merging**
