### PR TITLE
ZEPPELIN-558 ] that is missing on geode travis test.

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
Zeppelin supports geode interpreter.
However, for this test environment it is not reflected in Travis.

I added a geode for travis test environment.

### What type of PR is it?
Improvement

### Todos
* [x] - Add geode build on .travis

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-558
### How should this be tested?
only travis.
and 
added geode interpreter for travis.

### Screenshots (if appropriate)
no
### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by bzz** [comment]
Great find!
Can you please post here how this affects the CI build time?

Also, could you explain a bit how is the problem whit bytecode version compatibility resolved? ([ZEPPELIN-375](https://issues.apache.org/jira/browse/ZEPPELIN-375) which was the main reason it is hidden under profile)

**Comment by bzz** [comment]
Great find!
Can you please post here how this affects the CI build time?

Also, what about all other interpreters like Elasticsearch, Lense, etc

**Comment by cloverhearts** [comment]
@bzz 
Thank you for feed back.
I'm sorry, problem with bytecode version compatibility for I did not know.
First, I'll post the build time change.
And we'll check for your feedback.
Thank you!

**Comment by Leemoonsoo** [comment]
I think ```mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.3 -Ppyspark -Pscalding -Pgeode -B``` skip tests because of we defined [`-Pbuild-distr` to do so](https://github.com/apache/incubator-zeppelin/blob/master/pom.xml#L648).

[Line 35](https://github.com/apache/incubator-zeppelin/blob/master/.travis.yml#L35) will run actual test. If we put -Pgeode in this line, it'll fail while ZEPPELIN-375 is not resolved.

I think this PR make sure geode module is able to build (without test).
it looks good to me.

**Comment by cloverhearts** [comment]
This is Local build for my machine.
Previous .m2 must build directory has been removed.


### Except Geode
#### mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.3 -Ppyspark -Pscalding -B
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [01:00 min]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 16.319 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [ 14.119 s]
[INFO] Zeppelin: Spark dependencies ....................... SUCCESS [02:12 min]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 44.425 s]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  0.475 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  0.245 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  0.205 s]
[INFO] Zeppelin: Hive interpreter ......................... SUCCESS [ 15.394 s]
[INFO] Zeppelin: Apache Phoenix Interpreter ............... SUCCESS [ 29.486 s]
[INFO] Zeppelin: PostgreSQL interpreter ................... SUCCESS [  1.057 s]
[INFO] Zeppelin: Tajo interpreter ......................... SUCCESS [  3.388 s]
[INFO] Zeppelin: Flink .................................... SUCCESS [01:03 min]
[INFO] Zeppelin: Apache Ignite interpreter ................ SUCCESS [  9.179 s]
[INFO] Zeppelin: Kylin interpreter ........................ SUCCESS [  0.210 s]
[INFO] Zeppelin: Lens interpreter ......................... SUCCESS [ 17.994 s]
[INFO] Zeppelin: Cassandra ................................ SUCCESS [01:11 min]
[INFO] Zeppelin: Elasticsearch interpreter ................ SUCCESS [ 18.994 s]
[INFO] Zeppelin: web Application .......................... SUCCESS [ 44.206 s]
[INFO] Zeppelin: Server ................................... SUCCESS [ 26.893 s]
[INFO] Zeppelin: Packaging distribution ................... SUCCESS [ 46.882 s]
[INFO] Zeppelin: Scalding interpreter ..................... SUCCESS [ 27.048 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:46 min
[INFO] Finished at: 2016-01-06T00:58:10-08:00
[INFO] Final Memory: 81M/1144M
[INFO] ------------------------------------------------------------------------


### Add Geode
#### mvn package -Pbuild-distr -Pspark-1.5 -Phadoop-2.3 -Ppyspark -Pscalding -Pgeode -B
[INFO] Zeppelin ........................................... SUCCESS [ 46.638 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 13.173 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [ 14.187 s]
[INFO] Zeppelin: Spark dependencies ....................... SUCCESS [02:04 min]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 41.207 s]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  0.468 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  0.183 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  0.265 s]
[INFO] Zeppelin: Hive interpreter ......................... SUCCESS [ 13.129 s]
[INFO] Zeppelin: Apache Phoenix Interpreter ............... SUCCESS [ 26.696 s]
[INFO] Zeppelin: PostgreSQL interpreter ................... SUCCESS [  1.041 s]
[INFO] Zeppelin: Tajo interpreter ......................... SUCCESS [  3.077 s]
[INFO] Zeppelin: Flink .................................... SUCCESS [ 46.497 s]
[INFO] Zeppelin: Apache Ignite interpreter ................ SUCCESS [  8.136 s]
[INFO] Zeppelin: Kylin interpreter ........................ SUCCESS [  0.199 s]
[INFO] Zeppelin: Lens interpreter ......................... SUCCESS [ 10.452 s]
[INFO] Zeppelin: Cassandra ................................ SUCCESS [ 53.405 s]
[INFO] Zeppelin: Elasticsearch interpreter ................ SUCCESS [ 10.892 s]
[INFO] Zeppelin: web Application .......................... SUCCESS [ 41.659 s]
[INFO] Zeppelin: Server ................................... SUCCESS [ 23.084 s]
[INFO] Zeppelin: Packaging distribution ................... SUCCESS [ 51.294 s]
**[INFO] Zeppelin: Apache Geode interpreter ................. SUCCESS [ 59.974 s]**
[INFO] Zeppelin: Scalding interpreter ..................... SUCCESS [ 20.238 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:11 min
[INFO] Finished at: 2016-01-06T00:30:48-08:00
[INFO] Final Memory: 81M/1037M
[INFO] ------------------------------------------------------------------------


**Finding it difficult for meaningful change in the time to build additional Geode.**

**Comment by Leemoonsoo** [comment]
I'm merging it if there're no more discussions

**Comment by jongyoul** [comment]
Geode requires JDK 1.8, thus I think some tests would be failed because Z uses 1.7 when it compiles. And the reason that command doesn't have any error is that command doesn't do any tests. See below,

```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ zeppelin-geode ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ zeppelin-geode ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/jl/local/src/g/incubator-zeppelin/geode/src/test/resources
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ zeppelin-geode ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ zeppelin-geode ---
[INFO] Tests are skipped.
```

Is it intended behaviour?

**Comment by felixcheung** [comment]
and maybe rebase to latest? I think to move to the Spark 1.6 line instead?

**Comment by cloverhearts** [comment]
@jongyoul 
The only part of the PR will check only build success.
I've inserted the code for a test build of the geode.

**Comment by cloverhearts** [comment]
@felixcheung Thank you, but I've created new PR for Spark 1.6 
https://github.com/apache/incubator-zeppelin/pull/621

**Comment by cloverhearts** [comment]
Sorry, everyone.
My mistake as 'rebase' that seems to have caused problems.
So I made a new PR.
I'm sorry to everyone.
In the future, I would like to comment here.
The contents are the same.
Sorry again.

new PR (https://github.com/apache/incubator-zeppelin/pull/621)

**Comment by jongyoul** [comment]
@cloverhearts I see. I just wonder what the purpose is.

**Pull request closed without merging**
