### PR TITLE
ZEPPELIN-387 Allow enable/disable of specific paragraphs

### PR DESCRIPTION
**Pull request by r-kamath**
- When "run all" is called the disabled paragraphs are not executed.
- There is no "run" button for a disabled paragraph.

Disabled paragraph menu item
screen shot 2015-11-09 at 10 30 42 pm
---
Enabled paragraph menu item
screen shot 2015-11-09 at 10 30 26 pm

### CODE REVIEW

**Comment by corneadoug** [comment]
Hi,
Maybe you could keep the same style as the other (without checkbox) and with an icon (like the run button).
Also that menu position could be lower in the list (I think between ``Show line numbers`` and ``Link this paragraph`` is a good spot)

**Comment by r-kamath** [comment]
Hi @corneadoug,
That sounds like a right spot for the enable/disable menu item. Updated in 87aa4e8. Please take a look at the new screenshots. Thanks!

enabled
screen shot 2015-11-10 at 4 09 26 pm

disabled
screen shot 2015-11-10 at 4 09 15 pm

**Comment by corneadoug** [comment]
After thinking about it more, _Enable paragraph_ and _Disable paragraph_ can be a bit confusing since the paragraph is still shown.

_Enable run_ and _Disable run_ would be more meaningfull. And for the Icon, we should have the same as the run button, not an icon that change.

**Comment by Leemoonsoo** [comment]
+1 for Enable/Disable run than Enable/Disable paragraph.

**Comment by jongyoul** [comment]
+1 for `Enable/Disable run`

**Comment by r-kamath** [comment]
@Leemoonsoo @corneadoug @jongyoul updates from 3a7175a

screen shot 2015-11-16 at 11 49 30 am
screen shot 2015-11-16 at 11 49 21 am

**Comment by corneadoug** [comment]
I tried it, and there might be another case we should handle:
z.run(4) (for example) will run your paragraph.
I think it could be better if this kind of could not run it either

**Comment by r-kamath** [comment]
@corneadoug fixed the z.run() case in bdf703d

**Comment by corneadoug** [comment]
@r-kamath seems there is some test failing

**Comment by r-kamath** [comment]
@corneadoug @Leemoonsoo build issues are fixed

**Comment by prabhjyotsingh** [comment]
Tested, works as expected on FF, chrome, safari, IE10 and Edge (12)

**Comment by Leemoonsoo** [comment]
Tested, working nicely. Looks good to me.

**Comment by Leemoonsoo** [comment]
merging if there're no more discussions

**Pull request closed without merging**
