### PR TITLE
Change website menu caret color

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
One of the menu from the website has a wrong caret color, this fixed it.

### What type of PR is it?
Bug Fix

### How should this be tested?
You can build the website locally and run it, then check the top menu caret color

### Screenshots
Before:
screen shot 2016-05-24 at 10 21 29 pm

After:
screen shot 2016-05-24 at 10 21 37 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by corneadoug** [comment]
This is Ready

**Comment by AhyoungRyu** [comment]
Looks good :)

**Comment by cloverhearts** [comment]
Looks good +1

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by corneadoug** [comment]
Merging if there is no other discussion

**Pull request closed without merging**
