### PR TITLE
Improve travis build script

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Recent Travis CI build is failing with 

```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```

### What type of PR is it?
Improvement

### Todos
* [x] - Update .travis.yml to use build matrix

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Also how about;

    env:
      global:
      - TERM=dumb

read that on stackoverflow, but couldn't find much doc related to it.
or  `   -Dinvoker.debug=false` with mvn command ?

**Comment by Leemoonsoo** [comment]
Now .travis.yml creates each build job for each build profile instead of run every build profile in a single job. So output message is splitted into different build job.

**Comment by minahlee** [comment]
+1 let's merge it

**Comment by Leemoonsoo** [comment]
While every CI test is failing, i'm merging this patch as a hotfix.

**Comment by elbamos** [comment]
+1

**Pull request closed without merging**
