### PR TITLE
Tested with local LDAP configurations.

### PR DESCRIPTION
**Pull request by rconline**
### What is this PR for?
@hayssams @Leemoonsoo Just tested https://github.com/apache/incubator-zeppelin/pull/586 with a local LDAP, works well for me. Included a sample config. 

### What type of PR is it?
Documentation / Sample testing. 

### How should this be tested?
Change configs to point to a local/available LDAP, uncomment the parameters, replacing the individual values.

### CODE REVIEW

**Comment by hayssams** [comment]
@rconline 
You should probably leave "authcBasic" commented and "anon" uncommented.

**Comment by rconline** [comment]
@hayssams thanks for pointing out. Made the change.

**Comment by Leemoonsoo** [comment]
@rconline Thanks a lot for sharing this documentation. CI build failing is irrelevant.
LGTM

**Comment by prabhjyotsingh** [comment]
Tested, LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Pull request closed without merging**
