### PR TITLE
Fixed some documentation

### PR DESCRIPTION
**Pull request by michrawson**
### What is this PR for?
Fixed some documentation

### What type of PR is it?
Documentation

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the fix. LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions.

**Comment by felixcheung** [comment]
test failure - possibly a bug in the test?
```
17:40:41,096 ERROR org.apache.zeppelin.rest.NotebookRestApi:404 - Exception in NotebookRestApi while moveParagraph 
java.lang.IndexOutOfBoundsException: paragraph size is 2 , index is 10
	at org.apache.zeppelin.notebook.Note.moveParagraph(Note.java:319)
	at org.apache.zeppelin.rest.NotebookRestApi.moveParagraph(NotebookRestApi.java:398)
```

**Comment by Leemoonsoo** [comment]
@felixcheung  I think that's expected exception from https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java#L666

**Pull request closed without merging**
