### PR TITLE
Return the new setting ID in the response call in the REST API

### PR DESCRIPTION
**Pull request by eranwitkon**
This PR changes the JSON body of the create setting REST api to return the new created setting ID.
the new return body looks like the following:
```
{"status":"CREATED","message":"","body":"2AWGRNYY3"}
```
The documentation will be updated on a different PR once this is merged.
The unit testing is updated on PR 241 together with other REST API test.
Ready for review

### CODE REVIEW

**Comment by eranwitkon** [comment]
CI failed due to a download problem:
```Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) on project zeppelin-web: Could not download Node.js: Could not download http://nodejs.org/dist/v0.10.18/node-v0.10.18-linux-x64.tar.gz: Connect to nodejs.org:80 [nodejs.org/165.225.133.150] failed: Connection timed out -> [Help 1]```

Which has nothing to do with my code.
How do we trigger CI build again?

**Comment by djoelz** [comment]
Just remove an empty line in one of your files and push again it will trigger a new build. That file has been failing on my builds too. We should look into the resiliency of the build.

**Comment by Leemoonsoo** [comment]
Looks good to me.

**Comment by eranwitkon** [comment]
This PR is integrated into PR #266

**Pull request closed without merging**
