### PR TITLE
[ZEPPELIN-826] Run scheduled notes with a user

### PR DESCRIPTION
**Pull request by prasadwagle**
### What is this PR for?
As a user, I would like to run scheduled note paragraphs with my user. This user information is passed to data sources like presto by the HiveInterpreter.

### What type of PR is it?
Improvement

### Todos
* [ ] - Investigate better ways of cronExecutingUser input

### What is the Jira issue?
[ZEPPELIN-826](https://issues.apache.org/jira/browse/ZEPPELIN-826)

### How should this be tested?
Outline the steps to test the PR here.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
I think #860 is related to this issue, too.
After Zeppelin restarts, scheduled notebooks are going to be executed. However credentials from #860 might not be available unless user login and provide credentials again. @prasadwagle Do you have any good idea on it?

**Comment by prasadwagle** [comment]
@Leemoonsoo I added "Save user credentials in a file with encryption" TODO in [#860](https://github.com/apache/incubator-zeppelin/pull/860). We decided to hold off on this feature since our security team told us that the risks were high (even with encryption) and we would have to deal with regulatory requirements. I will implement this feature with an option to turn it off.

**Comment by prasadwagle** [comment]
I made the change to save user credentials in #860. Two instances of the build are failing due to the reasons below:
10548 Unable to extract spark-1.5.2-bin-hadoop2.3.tgz^M

13614 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.16:integration-test (default) on project zeppelin-server:        Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.      apache.maven.surefire:surefire-junit4:jar:2.16: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit4:jar:2.16: Could not         transfer artifact org.apache.maven.surefire:surefire-junit4:pom:2.16 from/to central (https://repo.maven.apache.org/maven2): Connection          reset^M

Are these failures related to this PR? I am going to close/reopen the PR to kick off another build to check if the errors go away.

**Comment by bzz** [comment]
Looks good to me. Merging if there is no more discussion.

**Pull request closed without merging**
