### PR TITLE
Fix NotebookList Ordering

### PR DESCRIPTION
**Pull request by corneadoug**
In the notebook list, the notebooks that have been created without name (empty name) and prefixed with 'Note' are not ordered correctly with the others.

The reason behind it, is that when notebook doesn't have a name, we use the notebook id and prefix it by 'Note'. At that time the list was already ordered and therefore the Name shown doesn't match the position in the list.

Before:
screen shot 2015-08-22 at 2 48 56 pm

After:
screen shot 2015-08-22 at 2 30 26 pm

The Fix I have is to have an ordering function at the place we prefix the 'Note' on the front side.
Another solution could be to just to have by default the notebook name as 'Note ' + note.id when we create a note. The second option could probably be better performance wise, however it wouldn't be backward compatible.

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
A better way would be show this in a tabular with at-least following fields; Name, Created on, Last edited on. And then put a table sorter on the header.

**Comment by r-kamath** [comment]
Is there a way to avoid calling sort from the template. How about sorting it as soon as we receive `NOTES_INFO` ?

**Comment by corneadoug** [comment]
If we plan on using multiple type of ordering, then using orderBy is how it should be done.
However I don't think it's a feature coming soon since we are trying to bring folder structure in a different PR.
Even without multiple ordering, the orderBy function was made for this kind of cases, and have the same effect than pre-sorting the list. The ordering function being pretty simple, I doubt it would have impact on performances.

**Comment by Leemoonsoo** [comment]
Changes looks good to me. 
Could you rebase with master? To resolve conflict and trigger ci again.

**Comment by corneadoug** [comment]
I will, I also want make another commit to set the notebook name by default on the Java side (for notebook create).

**Comment by Madhuka** [comment]
+1 for

**Comment by prabhjyotsingh** [comment]
The way I imagined is like this:

| Name  | Created on  | Actions |
|:------------- |:---------------:|:-------------:|
| 12345      | Aug 04, 2015, 02:12PM | [Edit]() [Delete]() [Export]()|
| Bacon      | Aug 20, 2015, 02:12PM | [Edit]() [Delete]() [Export]()|
| Note 1Z12312 | Aug 24, 2015, 02:12PM| [Edit]() [Delete]() [Export]()|


So we can have more actions on the dashboard.

**Comment by corneadoug** [comment]
Ready to Merge

**Pull request closed without merging**
