### PR TITLE
Corrected and updated the MapR Distribution profiles

### PR DESCRIPTION
**Pull request by pfcurtis**
Completed the necessary Spark dependency profiles for the MapR distribution. Also added commented out MapR artifact IDs for the Hive interpreter.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Looks good. Do you mind add simple description for the profiles (mapr40, mapr50) for users? README.md could be one place.

**Comment by pfcurtis** [comment]
Added MapR specific Maven command lines to the README.md

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by Leemoonsoo** [comment]
According to https://issues.apache.org/jira/browse/ZEPPELIN-404, MapR maven repository shouldn't be activated by default. Could you move MapR repository into profile, like https://github.com/apache/incubator-zeppelin/pull/404 did for cloudera repo?

**Comment by pfcurtis** [comment]
I have updated the Spark POM (spark-dependencies) to move the MapR repositories to the individual profiles. I have pushed the changes to my fork.

Regards.

**Comment by Leemoonsoo** [comment]
Thanks, Could you also handle repository section in hive/pom.xml?

**Comment by Leemoonsoo** [comment]
Thanks for taking care profiles for MapR distribution.
Looks good to me and merge if there're no more discussions.

**Pull request closed without merging**
